import { useState } from "react";
import { ArrowRight, ChevronDown } from "lucide-react";
import { brandingFaqs } from "../brandingFaqs";
import "./WebDevelopmentPage.css";
import "./BrandingPage.css";

const process = [
  ["1. Discovery and Goals", "We begin by understanding the business, audience, challenges and desired outcomes. Existing materials and stakeholder input are reviewed."],
  ["2. Research and Analysis", "We examine the market, competitors, customers and current brand where relevant. Findings are organised into practical insights."],
  ["3. Strategy and Positioning", "The brand’s audience, position, value, personality and decision principles are defined."],
  ["4. Messaging Direction", "Key messages, tone of voice and verbal priorities are developed where included."],
  ["5. Visual Exploration", "Creative directions are developed from the approved strategy. Concepts are evaluated against the brief rather than personal preference alone."],
  ["6. Identity Development", "The selected direction is refined into a complete visual system with relevant components and applications."],
  ["7. Guidelines and Handoff", "Approved assets, usage rules and agreed files are organised for delivery."],
  ["8. Rollout Support", "Where included, we support website, social, presentation or campaign implementation and answer questions during rollout."],
];

function List({items}) { return <ul className="wd-checklist">{items.map(item=><li key={item}>{item}</li>)}</ul>; }
function Section({title,children,tinted=false}) { return <section className={`wd-section branding-section${tinted?" wd-tinted":""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="branding-prose">{children}</div></section>; }
function Faq({faq,index}) { const [open,setOpen]=useState(index===0); const id=`branding-faq-${index}`; return <article className="branding-faq"><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)}>{faq.question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}>{faq.answer.map(p=><p key={p}>{p}</p>)}</div></article>; }

export default function BrandingPage() {
  return <main className="web-development-page branding-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Branding</span></li></ol></nav>
    <section className="wd-hero branding-hero"><div className="wd-hero-copy"><h1>Strategic Branding Services for Growing Businesses</h1><p>Vorevix provides branding services that connect research, positioning, messaging and visual identity into one practical brand system. We help businesses clarify what they stand for, communicate consistently and apply their identity across digital and physical touchpoints.</p><p>A strong brand is more than a logo. It is how a business is understood, remembered and experienced. Whether you are launching, refining or rebranding, we build the process around your goals, audience and market.</p><div className="wd-actions"><a className="primary" href="/contact">Start Your Branding Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-branding.png" alt="Branding services for strategy identity and growth" width="1182" height="1330" fetchPriority="high"/></div></section>

    <Section title="Why Inconsistent Branding Creates Business Problems"><p>A business can offer a strong product or service and still appear unclear. Different messages, mismatched visuals, weak positioning and inconsistent customer touchpoints can make the brand difficult to understand or trust.</p><p>These problems often grow over time as teams create inconsistent presentations, social posts, website graphics and documents.</p><p>Our approach addresses the system behind these issues. We define how the brand should communicate, look and behave so internal teams and external partners can work from the same direction.</p></Section>

    <Section title="What Our Branding Services Include" tinted><p>The exact scope depends on the project, but a complete engagement may include discovery, research, brand strategy, positioning, messaging, visual identity, guidelines and rollout support.</p><p>Some businesses need a complete brand, while others need clearer strategy, stronger consistency or an updated visual system. We shape the scope around the real problem. This keeps the engagement focused, avoids unnecessary deliverables and gives every creative decision a clear connection to the approved strategy.</p></Section>

    <Section title="Brand Strategy and Visual Identity Are Different"><p>Brand strategy defines what the brand means and how it should compete. It covers audience, positioning, value, personality, messaging and the principles that guide future decisions.</p><p>Visual identity defines how the brand is expressed through design. It includes logo systems, colour, typography, imagery, graphic language and application rules.</p><p>Both are important. A polished identity without strategy may feel generic, while strategy without a usable visual system may be hard to express. Our process brings both together.</p></Section>

    <Section title="Brand Discovery and Research" tinted><p>Discovery helps us understand goals, history, challenges, offers, audience and future plans. Research may include stakeholder discussions, brand reviews, competitor analysis and audience insights. The objective is to identify patterns, risks and opportunities that should guide strategy and design.</p></Section>

    <Section title="Audience and Competitor Analysis"><p>Audience work examines customer needs, motivations, objections and expectations. Competitor analysis identifies category conventions, crowded messages and opportunities for distinction. These insights support our brand strategy services by clarifying who the brand is for and what it should communicate.</p></Section>

    <Section title="Brand Positioning" tinted><p>Positioning explains how the business should be understood in relation to alternatives. It clarifies the audience, category, customer need, key difference and value promise.</p><p>Positioning should guide website messaging, service descriptions, sales conversations and visual expression. The outcome should help teams explain the brand more clearly and make consistent choices.</p></Section>

    <Section title="Brand Personality, Purpose and Values"><p>Brand personality describes the human qualities the brand should express. It influences tone, design and the way the business interacts with customers.</p><p>Purpose and values can support direction, but they should reflect real priorities and behaviours rather than generic statements.</p></Section>

    <Section title="Brand Messaging and Tone of Voice" tinted><p>Brand messaging turns strategy into language. It may include the value proposition, key messages, messaging pillars, service narratives and supporting proof.</p><p>Tone of voice defines how the brand communicates across channels. Our brand development services can include messaging frameworks for websites, presentations, social media and campaigns.</p><p>Naming and tagline development can be included as optional work. These services do not guarantee trademark availability, legal clearance or domain registration. Specialist legal checks may still be required.</p></Section>

    <Section title="Visual Identity Design"><p>Visual identity translates strategy into a recognisable design system. It should support the brand’s position, personality and audience rather than follow trends without purpose.</p><p>Our brand identity services may include:</p><List items={["Logo design and logo variations","Colour palette","Typography system","Graphic language","Icon or illustration direction","Image style","Layout principles","Digital application examples"]}/><p>The goal is a consistent system that remains flexible across platforms and formats.</p></Section>

    <Section title="Logo Design as Part of a Complete Identity" tinted><p>A logo is an important brand asset, but it is not the entire brand. It works best when supported by positioning, messaging, colour, typography and usage rules.</p><p>Logo and branding services may include a primary mark, alternative layouts, symbols and monochrome versions. The identity must work across websites, social platforms, presentations and documents.</p></Section>

    <Section title="Colour, Typography and Graphic Language"><p>Colour and typography shape recognition, readability and tone. Graphic language may include shapes, patterns, icons, image treatments, spacing and layout principles.</p><p>Our brand design services organise these components into a coherent system rather than treating them as isolated creative choices.</p></Section>

    <Section title="Brand Guidelines" tinted><p>Brand guidelines explain how the identity should be used. They create a reference for internal teams, designers, developers, printers and marketing partners.</p><p>Guidelines may cover:</p><List items={["Logo usage and clear space","Approved colour values","Typography hierarchy","Graphic language","Imagery direction","Tone of voice","Layout examples","Digital and print applications","Incorrect-use examples"]}/><p>The level of detail depends on the brand’s size and governance needs. This makes the system easier to apply consistently when new materials are created by different teams.</p></Section>

    <Section title="Digital and Print Brand Applications"><p>Digital applications may include websites, social media, presentations and campaign assets. Print applications may include stationery, brochures or packaging concepts where scoped. Vorevix can provide print-ready files, but physical printing and production are not automatically included.</p><p>Digital rollout can connect with our <a href="/services/web-design">web design services</a>, <a href="/services/ui-ux-design-services">UI UX design services</a>, <a href="/services/web-development-services">web development services</a> and <a href="/services/digital-marketing">digital marketing services</a>.</p></Section>

    <Section title="Rebranding Services" tinted><p>Rebranding may be appropriate when the business has changed, the audience has shifted or the existing identity no longer reflects the organisation.</p><p>A rebrand can involve strategy, messaging, visual identity or all three. Useful assets can be retained while weaker parts are improved. We can support either a focused refresh or a complete transformation.</p></Section>

    <section className="wd-section branding-section"><div className="wd-section-heading"><h2>Our Branding Services Process</h2></div><div className="wd-process-grid">{process.map(([title,body])=><article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <Section title="What You Receive" tinted><p>Depending on scope, deliverables may include:</p><List items={["Discovery findings","Competitor and audience review","Brand positioning","Value proposition","Brand personality","Messaging pillars","Tone-of-voice guidance","Logo system","Colour palette","Typography system","Graphic language","Image direction","Digital application examples","Brand guidelines","Final approved files","Rollout recommendations"]}/><p>Optional deliverables may include naming, taglines, packaging, extended templates, print collateral and ongoing support.</p></Section>

    <Section title="Why Choose Vorevix as Your Branding Agency?"><p>Vorevix connects strategy, design, content and digital implementation so the brand can work across websites, marketing materials and customer experiences.</p><p>Businesses choose our branding services for:</p><List items={["Strategy before visual execution","Clear project scope","Research-informed direction","Practical brand systems","Digital-first application thinking","Structured feedback and approvals","Organised file handoff","Collaboration across design and development"]}/><p>We do not promise guaranteed recognition, sales growth or market leadership. Branding can improve clarity and consistency, but business outcomes also depend on the product, service, customer experience and marketing execution.</p></Section>

    <Section title="Branding Pricing Factors" tinted><p>Branding cost depends on research depth, strategy scope, number of decision-makers, identity complexity, applications and guideline requirements.</p><p>A visual refresh requires less work than a complete project involving research, positioning, messaging, naming and rollout. Vorevix recommends scope after reviewing the requirements. Wider search support can be scoped through our <a href="/services/seo-services">SEO services</a>.</p></Section>

    <Section title="Timelines, Feedback and Revisions"><p>Timelines depend on complexity, stakeholder availability and feedback speed. Feedback rounds are defined in scope, and additional changes may affect cost or timing. Concepts should be reviewed against the agreed strategy, audience and goals.</p></Section>

    <Section title="Ownership and File Handoff" tinted><p>Final approved files are delivered according to the contract, scope and payment terms. Editable files are included only where specified. Third-party materials remain subject to their own licences, and legal trademark clearance is not included unless separately arranged.</p></Section>

    <section className="wd-section branding-section"><div className="branding-prose"><p>Vorevix works with businesses worldwide, including organisations seeking <a href="/australia/branding-services">branding services across Australia</a>, New Zealand and the United Arab Emirates.</p></div></section>

    <section className="wd-section branding-section"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="branding-faq-list">{brandingFaqs.map((faq,index)=><Faq faq={faq} index={index} key={faq.question}/>)}</div></section>

    <section className="wd-final-cta"><h2>Build a Clearer, More Consistent Brand</h2><p>Vorevix provides branding services for businesses that need stronger positioning, clearer communication and a visual identity built for real-world use.</p><p>We can review your current brand, identify what needs to change and recommend a practical scope for strategy, identity and rollout.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Branding Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></section>
  </main>;
}
