import { useState } from "react";
import { ArrowRight, ChevronDown, Palette } from "lucide-react";
import { brandingNewZealandFaqs } from "../brandingNewZealandFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./BrandingPage.css";

const questions = ["What should the business be known for?", "Which audiences matter most?", "What problems does it solve?", "How is it currently perceived?", "Which competitors influence customer expectations?", "What should remain consistent?", "What needs to change?", "Where will the brand be used?"];
const messages = ["a clear value proposition", "audience-focused key messages", "service or product messages", "brand-story direction", "supporting proof points", "tagline exploration", "tone-of-voice principles", "suitable and unsuitable wording examples"];
const guidelines = ["brand foundations", "positioning and personality", "messaging principles", "logo usage", "clear space and minimum sizes", "colour specifications", "typography", "imagery direction", "graphic elements", "digital applications", "print applications", "incorrect usage"];
const rollout = ["websites and digital interfaces", "social-media profiles and templates", "proposals and presentations", "stationery and documents", "marketing materials", "signage", "packaging", "internal templates", "email signatures"];
const costs = ["discovery and workshop requirements", "number of stakeholders", "audience and competitor research", "brand-audit depth", "positioning and messaging requirements", "naming or tagline exploration", "identity-system complexity", "colour and typography requirements", "guideline depth", "application examples", "rebranding and rollout requirements", "number of review stages", "file preparation and handoff"];
const reasons = ["structured discovery and stakeholder alignment", "audience and competitor research", "brand strategy and positioning", "value-proposition development", "messaging and tone of voice", "coherent visual identity systems", "logo systems within a wider identity", "colour, typography and graphic-language guidance", "practical brand guidelines", "rebranding and refresh support", "rollout planning", "remote collaboration across New Zealand business hours", "qualified recommendations without guaranteed outcomes"];
const process = [["Discovery", "We review the business, audience, competitors, existing identity, priorities and intended applications."], ["Strategy", "Positioning, value, personality and core brand direction are clarified according to the project scope."], ["Messaging", "Key messages, value propositions and tone-of-voice principles are developed where required."], ["Identity Development", "Visual concepts are explored and developed into a coherent identity system."], ["Review and Refinement", "Stakeholder feedback is organised through agreed review stages to reduce conflicting or fragmented direction."], ["Guidelines and Handoff", "Approved identity elements, specifications and usage guidance are prepared for implementation."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section branding-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="branding-prose">{children}</div></section>; }

export default function BrandingNewZealandPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page branding-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/branding">Branding</a></li><li aria-hidden="true">/</li><li><span aria-current="page">New Zealand</span></li></ol></nav>
    <section className="wd-hero branding-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Branding New Zealand</span><h1>Branding Services for New Zealand Businesses</h1><p>For organisations comparing brand design NZ providers, the right partner should do more than create an attractive logo. Strong branding connects business direction, audience understanding, positioning, messaging and visual identity so customers receive a more consistent impression across websites, campaigns, proposals, packaging and other touchpoints.</p><p>Vorevix provides branding services for New Zealand businesses through a structured remote process. We help organisations clarify how they want to be understood, define the messages they need to communicate and translate those decisions into practical visual systems.</p><p>Our brand design NZ approach does not promise guaranteed awareness, sales, loyalty or market growth. Instead, we focus on strategic clarity, coherent identity systems and guidelines that can support more consistent communication as a business develops.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Branding Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-branding.png" alt="Brand identity system designed by Vorevix" width="1182" height="1330" fetchPriority="high"/></div></section>

    <Section title="Brand Design NZ Built Around Strategy"><p>A brand design NZ project should begin with the business, not with colours or logo concepts. Before visual decisions are made, it is important to understand the organisation, its audience, competitors and intended market position.</p><p>Vorevix connects strategic and creative work so the identity is based on clear reasoning. Depending on scope, a project may include discovery, stakeholder workshops, audience research, competitor review, positioning, messaging, visual identity, logo systems and brand guidelines.</p><p>This helps prevent the brand from becoming a collection of disconnected design choices that look appealing individually but do not communicate one clear direction.</p></Section>
    <Section title="Brand Discovery and Stakeholder Alignment" tinted><p>Brand discovery creates a shared foundation for the project. We review the business model, services, products, audience, market context, current identity and future direction.</p><p>Stakeholder workshops can surface different expectations and priorities before major decisions are made. Important questions may include:</p><List items={questions}/><p>For brand design NZ projects, workshops and review sessions can be organised around New Zealand business hours. Decisions, feedback and next actions are documented so teams can review progress clearly without relying only on meetings.</p></Section>
    <Section title="Audience and Competitor Research"><p>Audience research can clarify what customers value, how they compare options and which language feels relevant.</p><p>Competitor research may reveal common messages, visual conventions and opportunities for clearer positioning. Vorevix may review existing research, customer feedback, sales information, competitor websites and stakeholder knowledge within the agreed scope.</p><p>Research does not guarantee success. Its purpose is to support better-informed positioning, messaging and identity decisions.</p></Section>
    <Section title="Brand Strategy and Positioning" tinted><p>Brand strategy defines how the business wants to be understood and how that direction should guide communication.</p><p>Positioning helps express the place a brand intends to occupy in the minds of its audience. It may consider the audience, market category, value offered, relevant differences and reasons customers may find the business credible.</p><p>Our brand design NZ work may include brand purpose, values, personality, attributes, audience definition and value-proposition development. Not every organisation requires every framework. The process should remain proportionate to the size, maturity and needs of the business.</p><p>A strategy is useful only when it can guide practical decisions. It should help teams decide what to say, how to present the business and which opportunities fit the intended direction.</p></Section>
    <Section title="Brand Messaging and Tone of Voice"><p>Visual identity is only one part of a brand. The language used across websites, presentations, campaigns and customer communication also influences how the business is understood.</p><p>Brand messaging may include:</p><List items={messages}/><p>Tone of voice should reflect the brand personality while remaining appropriate for the audience and channel. A professional-services company may require a different communication style from a retail, hospitality or technology business.</p><p>Clear messaging can make a business’s value easier to communicate, but it cannot guarantee attention, trust or conversion.</p></Section>
    <Section title="Visual Identity Design" tinted><p>Visual identity translates strategy into a coherent system of logo relationships, colour, typography, graphics, imagery and layout principles.</p><p>Our brand design NZ process creates a recognisable, flexible system for websites, social channels, proposals, presentations, advertising, packaging and internal documents.</p><p>Brand identity should support the intended positioning rather than follow visual trends without a strategic reason.</p></Section>
    <Section title="Logo Systems Within a Broader Identity"><p>A logo is an important identifier, but it is not the entire brand. Customers also experience messaging, service, behaviour, imagery, content and the consistency of each touchpoint.</p><p>Vorevix treats logo design as part of a wider identity system. A project may include primary and secondary logo configurations, icon or symbol use, spacing guidance, minimum sizes, colour variations and background rules.</p><p>Although logo design NZ has higher exposed search demand, it should not define the scope of this page. The purpose of the service is strategic branding rather than low-cost, template-based or standalone logo production.</p></Section>
    <Section title="Colour, Typography and Graphic Language" tinted><p>Colour and typography influence recognition, hierarchy and personality and should reflect the intended direction and practical requirements.</p><p>A colour system may define primary, secondary and supporting colours for digital and print use. Typography guidance may cover display, heading, body and accent usage while considering readability, licensing and availability.</p><p>Shapes, patterns, iconography, illustration, image treatment and layout principles can create continuity beyond the logo.</p></Section>
    <Section title="Brand Guidelines and Identity Manuals"><p>Brand guidelines explain how the identity should be applied. They can help internal teams, agencies, designers, developers, printers and external partners use the brand more consistently.</p><p>Depending on scope, guidelines may cover:</p><List items={guidelines}/><p>A complex organisation may require a broader identity manual or toolkit, while a smaller business may need a focused set of practical rules.</p></Section>
    <Section title="Rebranding and Brand Refresh Projects" tinted><p>Rebranding may suit a business whose strategy, audience, services or market position has changed; others may need only a focused refresh.</p><p>We review what should be retained, updated or replaced so useful recognition is not discarded without reason. The process may include an audit, stakeholder alignment, positioning, messaging, identity development and rollout planning.</p><p>Rebranding can reflect a changed direction, but it cannot guarantee sales, loyalty, awareness or market-share improvements.</p></Section>
    <Section title="Brand Rollout and Implementation Planning"><p>A new identity becomes useful when it is applied consistently across real touchpoints.</p><p>Rollout planning may identify priority assets, responsible teams, implementation stages and areas where old and new materials may temporarily overlap.</p><p>Applications can include:</p><List items={rollout}/><p>Vorevix can prepare assets, specifications and implementation guidance included within the agreed scope. Production, printing, development and third-party execution may require separate coordination.</p><p>When the brand system is ready to be applied online, our <a href="/new-zealand/web-design">web design services for New Zealand businesses</a> can translate it into a responsive website experience.</p><p>Digital products requiring user research, flows, prototypes or interface systems can be supported through our <a href="/new-zealand/ui-ux-design">New Zealand UI/UX design service</a>.</p><p>Approved brand and website designs can be implemented through our <a href="/new-zealand/web-development">New Zealand website-development service</a>.</p><p>After launch, the brand system can support more consistent campaigns through our <a href="/services/digital-marketing">digital marketing services</a>.</p></Section>
    <section className="wd-section branding-section wd-tinted"><div className="wd-section-heading"><h2>Our Branding Process for New Zealand Teams</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p className="wda-note">Businesses needing a broader view of the global methodology can <a href="/services/branding">explore our complete branding services</a>.</p></section>
    <Section title="Remote Branding Collaboration Across New Zealand"><p>Vorevix supports brand design NZ projects through remote workshops, video meetings, shared presentations and documented reviews.</p><p>We collaborate with founders, directors, marketing teams and stakeholders across New Zealand business hours. Consolidated feedback helps resolve conflicts between personal preferences and strategic requirements.</p><p>National availability does not imply a New Zealand office, local phone number or New Zealand-based branding team. Services are delivered remotely.</p></Section>
    <Section title="What Influences Branding Cost in New Zealand?" tinted><p>The cost of brand design NZ work depends on the depth of strategy, number of deliverables and complexity of the organisation.</p><p>Important factors may include:</p><List items={costs}/><p>Each brand design NZ engagement is scoped around the actual work required. Vorevix prepares a tailored proposal after reviewing the business, existing materials and expected deliverables.</p><p>We do not publish unsupported NZD prices, GST statements or fixed timelines for every branding project.</p></Section>
    <section className="wd-section"><div className="wd-section-heading"><h2>Why Choose Vorevix for Brand Design NZ?</h2><p>Our brand design NZ approach connects strategic thinking, messaging and visual identity instead of treating branding as a logo-only exercise.</p></div><div className="wd-card-grid">{reasons.map((reason) => <article className="wd-card" key={reason}><Palette className="wd-card-icon" size={25} aria-hidden="true"/><h3>{reason}</h3></article>)}</div></section>
    <section className="wd-section branding-section wda-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions About Branding in New Zealand</h2></div><div className="wda-faq-list">{brandingNewZealandFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `branding-nz-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Build a Brand With Clearer Direction</h2><p>A strong brand design NZ project should connect business goals, audience understanding, positioning, messaging and visual identity.</p><p>Vorevix helps New Zealand businesses develop brand systems that are easier to understand, apply and manage across different channels.</p><p>Share your current brand, business goals, audience, challenges and required deliverables. We will review the information and discuss an appropriate next step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Branding Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
