import { useState } from "react";
import { ArrowRight, ChevronDown, Palette } from "lucide-react";
import { brandingFaqs } from "../brandingFaqs";
import "./WebDevelopmentPage.css";
import "./BrandingPage.css";

const services = [
  { title: "Brand Discovery and Research", paragraphs: ["Effective branding begins with understanding the business and the environment in which it operates.", "Our discovery and research stage gathers the information required to make informed strategic and creative decisions. We explore the organisation, its audience, competitors, current communication and future ambitions.", "This stage may include:"], items: ["stakeholder discovery", "business and service analysis", "audience research", "customer needs and motivations", "competitor analysis", "market and category research", "existing brand assessment", "communication review", "visual landscape research", "brand opportunity identification"], closing: ["The purpose of research is not to create unnecessary documentation.", "It is to establish the context needed to determine how the brand should be positioned, what it should communicate and how it should be expressed visually.", "These findings become the foundation for the strategy, messaging and identity developed during the next stages."] },
  { title: "Brand Strategy Services", paragraphs: ["Brand strategy defines the principles and decisions that guide how a business presents itself, communicates and grows.", "It creates a shared direction for leadership, marketing, sales, design, content and customer-facing teams. Without this foundation, different areas of a business may communicate in inconsistent or conflicting ways.", "Our brand strategy work may include:"], items: ["brand purpose", "vision and mission", "brand values", "audience definition", "competitive differentiation", "brand promise", "brand personality", "strategic priorities", "brand architecture", "customer perception goals", "positioning direction"], closing: ["These branding services help teams make more consistent decisions as the organisation grows.", "The final strategy is designed to be practical rather than theoretical. It should support clearer decisions about communication, services, campaigns, partnerships and customer experiences."] },
  { title: "Brand Positioning", paragraphs: ["Brand positioning defines how a business should be understood within its market.", "It identifies the space the brand can credibly occupy and clarifies why customers should consider it instead of available alternatives.", "Our positioning process may explore:"], items: ["audience priorities", "customer problems", "category expectations", "competitor positioning", "market opportunities", "business strengths", "value proposition", "proof points", "differentiation", "positioning statements"], closing: ["Strong positioning must be relevant to the audience and believable for the business.", "It should not depend only on broad terms such as innovative, premium or customer-focused. These ideas need a clearer meaning supported by the business offer, experience and evidence.", "We translate strategic insights into positioning that can guide messaging, visual identity, content and future brand decisions."] },
  { title: "Brand Messaging and Tone of Voice", paragraphs: ["A visual identity can attract attention, but language helps people understand what the brand means.", "Our branding services include messaging and verbal identity systems that help businesses communicate more clearly across websites, presentations, proposals, campaigns, sales materials and customer interactions.", "Brand messaging may include:"], items: ["value proposition", "brand story", "core messages", "audience-specific messaging", "service or product messaging", "tagline exploration", "elevator pitch", "key proof points", "campaign language", "tone-of-voice principles", "writing examples", "language to use and avoid"], closing: ["Tone of voice defines how the brand should sound in different situations.", "The right tone should reflect the personality of the business while remaining appropriate for its audience, industry and communication channel.", "The aim is not to make every sentence sound identical. It is to create a recognisable communication style that teams can apply naturally."] },
  { title: "Brand Naming", paragraphs: ["A strong name can make a business, product or service easier to recognise, communicate and remember.", "Naming requires more than producing a list of creative words. The selected direction must support the wider brand strategy, remain relevant to the intended audience and work practically across digital and physical communication.", "Our naming process may include:"], items: ["naming criteria", "creative territories", "name generation", "descriptive names", "suggestive names", "invented names", "compound names", "shortlist development", "linguistic considerations", "preliminary domain searches", "initial search checks", "naming rationale", "tagline exploration"], extraLabel: "Potential names may be assessed against:", extraItems: ["relevance", "memorability", "distinctiveness", "pronunciation", "flexibility", "market suitability", "future growth", "digital usability"], closing: ["Initial searches can help identify obvious conflicts, but they do not replace professional legal clearance."] },
  { title: "Logo and Visual Identity Design", paragraphs: ["A logo is an important brand asset, but it is only one part of a complete identity.", "Visual identity design defines how the brand should appear across different formats and environments. It creates a connected visual language that supports recognition while giving the brand enough flexibility to communicate across multiple touchpoints.", "Our visual identity work may include:"], items: ["primary logo", "secondary logo", "responsive logo variations", "colour palette", "typography", "graphic language", "shapes and patterns", "imagery direction", "photography style", "illustration direction", "iconography", "layout principles", "motion direction", "digital interface considerations"], closing: ["Our branding services connect visual choices with positioning, audience expectations and practical business applications.", "Every creative decision should support the intended personality and perception of the brand rather than relying on personal preference alone."] },
  { title: "Brand Guidelines", paragraphs: ["Brand guidelines turn strategic and creative decisions into a practical system.", "They help employees, designers, developers, content creators, printers, agencies and external partners apply the brand consistently without needing constant direction.", "Depending on the project, guidelines may cover:"], items: ["brand foundations", "purpose and values", "positioning", "brand messaging", "tone of voice", "logo usage", "clear space", "minimum sizes", "incorrect logo usage", "colour specifications", "typography", "imagery", "graphic elements", "iconography", "layout principles", "digital applications", "print applications", "presentation examples", "social media examples"], closing: ["The required level of detail depends on the size and complexity of the organisation.", "A smaller business may need a focused visual guide, while a larger organisation may require a comprehensive identity system with detailed governance and application standards."] },
  { title: "Brand Applications and Rollout", paragraphs: ["A brand becomes useful when it can be applied consistently in real situations.", "Our branding services can include the practical materials required to launch, introduce or manage the identity across priority customer touchpoints.", "Brand applications may include:"], items: ["business stationery", "presentation templates", "proposal templates", "company profiles", "social media templates", "campaign assets", "website direction", "digital advertising assets", "email signatures", "brochures", "reports", "packaging", "signage", "uniforms", "event materials", "environmental graphics"], closing: ["The exact application set is defined according to the needs of the business.", "Rather than producing every possible item, we prioritise the touchpoints that have the greatest influence on customer perception, business communication and internal adoption."] },
];

const launchGrowth = [
  ["Branding for New Businesses", "New businesses need more than an attractive logo.", "They need a clear explanation of what they offer, who they serve and why the market should pay attention.", ["audience definition", "competitor research", "brand positioning", "naming", "messaging", "logo and visual identity", "launch applications", "brand guidelines"], "These branding services create a more consistent foundation before wider marketing and communication activity begins."],
  ["Branding for Growing Businesses", "Growth can expose inconsistencies that were manageable when a business was smaller.", "Teams may begin using different messages, existing materials may no longer match and the original identity may not support new services, audiences or markets.", ["clearer brand architecture", "updated positioning", "stronger messaging", "a more flexible identity system", "expanded brand guidelines", "consistent sales materials", "marketing templates", "website alignment", "internal brand adoption"], "The objective is to build a practical system capable of supporting a larger and more complex organisation."],
  ["Branding for Established Organisations", "Established organisations often have valuable awareness and reputation that should not be removed without a clear reason.", "Brand evolution may involve:", ["modernising the identity", "clarifying the value proposition", "aligning multiple divisions", "entering a new market", "improving digital consistency", "simplifying complex messaging", "updating customer perception"], "We approach these projects carefully, balancing the need for change with the value already associated with the existing brand."],
];

const process = [
  ["1. Discovery and Research", "We begin by learning about the business, audience, competitors, challenges and future goals.", "This stage may include:", ["discovery workshops", "stakeholder discussions", "existing-material reviews", "audience research", "competitor analysis", "market research"], "The purpose is to establish what the brand needs to achieve before deciding how it should look or sound."],
  ["2. Strategy and Positioning", "We define the strategic direction of the brand.", "This may include:", ["audience priorities", "purpose", "values", "differentiation", "personality", "value proposition", "positioning", "brand architecture"], "The agreed strategy creates a reference point for messaging and design decisions."],
  ["3. Messaging and Identity", "We translate the strategy into verbal and visual expression.", "Depending on the project, this stage may include:", ["naming", "brand story", "core messaging", "tone of voice", "logo design", "colour", "typography", "imagery", "graphic language"], "Creative directions are presented with reasoning connected to the agreed strategy rather than visual preference alone."],
  ["4. Guidelines and Applications", "Once the identity direction is approved, we create the tools needed for consistent use.", "This may include:", ["brand guidelines", "presentation templates", "digital assets", "print materials", "social templates", "company profiles", "priority brand applications"], ""],
  ["5. Activation and Rollout", "We support the transition from an approved brand system to practical use.", "Activation may include:", ["launch planning", "file preparation", "internal handover", "website coordination", "template delivery", "supplier support", "staged rollout recommendations", "brand migration guidance"], "The final identity should be practical for the people responsible for managing and applying it."],
];

const deliverables = [
  ["Strategic Deliverables", ["discovery findings", "audience definition", "competitor analysis", "brand purpose", "positioning", "value proposition", "brand personality", "brand architecture", "strategic recommendations"]],
  ["Verbal Identity Deliverables", ["brand story", "messaging framework", "tagline", "elevator pitch", "core messages", "tone-of-voice guidelines", "sample copy"]],
  ["Visual Identity Deliverables", ["primary logo", "secondary logo", "responsive logo variations", "colour palette", "typography system", "graphic elements", "imagery direction", "iconography", "layout examples"]],
  ["Implementation Deliverables", ["brand guidelines", "business stationery", "presentation templates", "social media templates", "company profile", "website direction", "packaging or print applications", "launch assets", "organised brand files"]],
];

const why = [
  ["Strategy Before Design", "We establish the business, audience and positioning context before developing visual concepts.", "This helps ensure design decisions support the wider objectives of the brand."],
  ["Connected Brand Thinking", "Our branding services consider strategy, messaging, visual identity, digital experience and implementation as parts of one connected system."],
  ["Clear Creative Rationale", "Creative concepts are not presented as unexplained personal preferences.", "We connect design decisions with the agreed positioning, audience, personality and intended customer perception."],
  ["Practical Brand Systems", "A brand must be usable by the people responsible for managing it.", "We create systems and guidelines that support consistency without making the identity unnecessarily restrictive."],
  ["Digital Experience Capability", "Modern brands need to work across websites, digital products, social media, campaigns and online content.", "Our design and development capabilities help connect brand decisions with practical digital implementation."],
  ["Transparent Collaboration", "We define the project process, deliverables, responsibilities and feedback stages clearly."],
];

function Checklist({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, intro, children, tinted = false }) { return <section className={`wd-section branding-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro && <p>{intro}</p>}</div>{children}</section>; }
function Card({ title, paragraphs = [], items, closing = [], children }) { return <article className="wd-card"><Palette className="wd-card-icon" aria-hidden="true" /><h3>{title}</h3>{paragraphs.map((p) => <p key={p}>{p}</p>)}{items && <Checklist items={items} />}{closing.map((p) => <p key={p}>{p}</p>)}{children}</article>; }

export default function BrandingPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page branding-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Branding</span></li></ol></nav>
    <section className="wd-hero branding-hero"><div className="wd-hero-copy"><h1>Branding Services for Distinct and Confident Businesses</h1><p>Build a brand that communicates clearly, stands apart and creates a consistent experience across every customer touchpoint.</p><p>Vorevix provides strategic branding services for businesses that are launching, growing or evolving. We combine research, positioning, messaging, visual identity and practical brand systems to create brands that are easier to understand, recognise and apply.</p><p>Our work goes beyond designing a logo. We help define what your brand represents, who it serves, how it should communicate and how it should appear across digital and physical experiences.</p><p>Whether you are creating a new brand, refreshing an existing identity or repositioning an established organisation, we develop the strategic and creative foundation needed to move forward with clarity.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Branding Project <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">Explore Our Work</a></div></div><div className="wd-hero-visual branding-hero-art" aria-hidden="true"><Palette /></div></section>

    <Section title="Build a Brand with Clarity, Relevance and Purpose"><div className="branding-prose"><p>A strong brand gives people a clear reason to notice, understand and remember a business.</p><p>It brings strategy, language, design and customer experience together into one connected system. When these elements work consistently, customers can understand what the business offers, why it is relevant and how it differs from available alternatives.</p><p>Without that clarity, businesses often experience:</p><Checklist items={["inconsistent messaging", "disconnected visual materials", "unclear market positioning", "weak differentiation", "an outdated identity", "difficulty explaining their value", "inconsistent customer experiences"]} /><p>Our branding services help address these challenges through a structured process.</p><p>We begin by understanding the business, audience, market, competitors and future goals. We then create a strategic and visual foundation that can guide communication across websites, presentations, campaigns, packaging, social media and other brand touchpoints.</p><p>The result is not simply a collection of attractive assets. It is a practical brand system designed to help the business communicate more clearly and consistently.</p></div></Section>

    <Section title="Our Branding Services" intro="Every branding project begins from a different point."><div className="branding-prose branding-intro"><p>Some businesses need to define their strategy and positioning before creative work begins. Others already have a clear direction but require a stronger visual identity, updated messaging or practical guidelines their teams can use consistently.</p><p>Our branding services can be delivered as a complete engagement or structured around specific strategic and creative requirements.</p></div><div className="wd-card-grid">{services.map((service) => <Card key={service.title} {...service}>{service.extraLabel && <><p>{service.extraLabel}</p><Checklist items={service.extraItems} /></>}{service.title === "Brand Naming" && <p>Businesses can explore international trademark records through the <a href="https://branddb.wipo.int/" target="_blank" rel="noopener noreferrer">WIPO Global Brand Database</a>. Final trademark and legal checks should be completed by a suitably qualified professional.</p>}{service.title === "Logo and Visual Identity Design" && <><p>Where the identity will be applied to a new website or digital product, our <a href="/services/web-design">web design services</a> and <a href="/services/ui-ux-design-services">UI/UX design services</a> can help translate it into a consistent digital experience.</p><img className="branding-content-image" src="/service-branding.png" alt="Branding services by Vorevix" title="Vorevix Branding Services" width="1182" height="1330" loading="lazy" /></>}{service.title === "Brand Applications and Rollout" && <p>Where website implementation is required, our <a href="/services/web-development-services">web development services</a> can support the digital rollout.</p>}</Card>)}</div></Section>

    <Section title="Rebranding Services" tinted><div className="branding-prose"><p>Businesses change, and their brands sometimes need to change with them.</p><p>A rebrand may be appropriate when:</p><Checklist items={["the business has changed direction", "the target audience has evolved", "new markets are being entered", "products or services have expanded", "the identity feels outdated", "communication has become inconsistent", "different business units require alignment", "a merger or acquisition has taken place", "customers misunderstand the offer", "the current name or identity restricts growth"]} /><p>Rebranding does not always mean removing everything that already exists.</p><p>In many cases, the strongest approach is to preserve valuable recognition while improving the elements that no longer support the business.</p><p>Our branding services for established organisations may include:</p><Checklist items={["existing brand audit", "stakeholder consultation", "customer and competitor research", "repositioning", "messaging refinement", "naming assessment", "identity refresh", "complete visual redesign", "brand architecture", "updated guidelines", "rollout planning", "migration support"]} /><p>We assess which elements should be retained, refined or replaced.</p><p>This reduces unnecessary change and helps protect useful brand equity while creating a clearer foundation for future communication.</p></div></Section>

    <Section title="Branding for Launch, Growth or Change" intro="Different stages of business create different branding requirements."><div className="wd-card-grid">{launchGrowth.map(([title, a, b, items, closing]) => <Card key={title} title={title} paragraphs={[a, b]} items={items} closing={[closing]} />)}</div></Section>
    <Section title="Our Branding Process" intro="A structured process keeps strategic and creative decisions connected throughout the project." tinted><div className="wd-process-grid">{process.map(([title, a, label, items, closing]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{a}</p><p>{label}</p><Checklist items={items} />{closing && <p>{closing}</p>}</article>)}</div></Section>
    <Section title="What Can a Branding Project Include?" intro="Project deliverables are defined according to the selected scope."><div className="wd-card-grid">{deliverables.map(([title, items]) => <Card key={title} title={title} items={items} />)}</div><p className="branding-note">The project proposal will clearly define the deliverables included before work begins.</p></Section>
    <Section title="Why Choose Vorevix as Your Branding Agency?" tinted><div className="branding-why-grid">{why.map(([title, ...paragraphs]) => <Card key={title} title={title} paragraphs={paragraphs} />)}</div><div className="branding-prose"><p>Vorevix combines strategy, design, technology and performance to create connected digital solutions for growing businesses.</p><p>Learn more <a href="/about">about Vorevix</a>.</p></div></Section>

    <Section title="Branding Work and Case Studies"><div className="branding-prose"><p>Branding work is best understood through the challenge, strategy and system behind the finished visuals.</p><p>Relevant portfolio projects can demonstrate:</p><Checklist items={["the original business challenge", "audience and market context", "strategic direction", "positioning and messaging", "identity development", "brand applications", "rollout considerations", "verified outcomes"]} /><p>We only present project results and performance claims that can be supported by the actual work.</p><a className="wd-text-link" href="/portfolio">Explore Our Portfolio <ArrowRight size={18} aria-hidden="true" /></a></div></Section>

    <Section title="Branding Services Pricing" tinted><div className="branding-prose"><p>The cost of branding services depends on the depth of research, strategic work, creative development and implementation required.</p><p>A focused visual identity project will have a different scope from a complete rebrand involving multiple stakeholders, research, positioning, messaging, architecture, brand guidelines and rollout support.</p><p>Pricing may be influenced by:</p><Checklist items={["project type", "business size", "number of stakeholders", "research requirements", "strategy depth", "naming requirements", "messaging scope", "number of creative directions", "number of applications", "guideline complexity", "packaging or print requirements", "website coordination", "rollout support", "project timeline"]} /><p>Engagements may include:</p><Checklist items={["brand audit", "brand strategy project", "naming project", "visual identity project", "complete branding programme", "rebranding project", "brand guideline development", "brand rollout support"]} /><p>The price of professional branding services should reflect the actual scope and deliverables rather than relying on a generic package that may not match the needs of the business.</p><p>Before work begins, we provide a proposal outlining the scope, deliverables, process, estimated timeline and responsibilities.</p><a className="wd-text-link" href="/contact">Request a Branding Estimate <ArrowRight size={18} aria-hidden="true" /></a></div></Section>

    <Section title="Frequently Asked Questions About Branding Services"><div className="branding-faq-list">{brandingFaqs.map((faq, index) => { const open = openFaq === index; const panelId = `branding-faq-panel-${index}`; return <article className="branding-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={panelId} onClick={() => setOpenFaq(open ? -1 : index)}>{faq.question}<ChevronDown aria-hidden="true" /></button></h3><div id={panelId} hidden={!open}>{faq.answer.map((p) => <p key={p}>{p}</p>)}</div></article>; })}</div></Section>

    <section className="wd-final-cta"><h2>Explore Branding Services Built Around Your Business</h2><p>A strong brand should help your organisation communicate more clearly, appear more consistently and make a more distinctive impression.</p><p>Whether you are launching something new, preparing for growth or evolving an established organisation, Vorevix can create the strategic and creative foundation needed to move forward with confidence.</p><p>Explore branding services designed around your business, audience and future direction.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Branding Project <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">Explore Our Portfolio</a></div></section>
  </main>;
}
