import { useState } from "react";
import { ArrowRight, ChevronDown } from "lucide-react";
import { digitalMarketingUaeFaqs } from "../digitalMarketingUaeFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./DigitalMarketingPage.css";

const scope = ["campaign discovery", "audience research", "competitor analysis", "channel planning", "media planning", "paid search", "paid social", "content marketing", "email marketing", "lead-generation support", "remarketing", "eCommerce campaigns", "analytics and reporting", "monthly testing and optimisation"];
const discovery = ["business objectives", "priority products or services", "target audiences", "geographic priorities", "previous campaigns", "available creative", "website and landing pages", "tracking setup", "sales process", "budget expectations", "internal approval requirements"];
const channels = ["Google Ads", "paid social", "email marketing", "remarketing", "content distribution", "eCommerce campaigns", "display advertising", "video advertising", "supporting organic content"];
const paidSearch = ["keyword research for paid campaigns", "campaign structure", "ad-group planning", "search-ad copy", "negative keywords", "audience signals", "location targeting", "conversion actions", "bidding recommendations", "search-term review", "campaign optimisation"];
const socialPlatforms = ["Facebook", "Instagram", "LinkedIn", "TikTok", "YouTube", "other suitable advertising platforms"];
const content = ["educational posts", "promotional assets", "landing-page copy", "articles", "email content", "short-form video concepts", "campaign graphics", "product-focused content", "lead magnets", "remarketing messages"];
const email = ["audience segmentation", "campaign planning", "email sequences", "promotional campaigns", "welcome emails", "abandoned-cart communication", "re-engagement campaigns", "performance reporting"];
const leads = ["campaign targeting", "lead-form planning", "landing-page recommendations", "offer positioning", "conversion tracking", "follow-up coordination", "lead-source reporting"];
const remarketing = ["website visitors", "product viewers", "cart abandoners", "previous leads", "existing customers", "video viewers", "engaged social users"];
const ecommerce = ["product feed quality", "category priorities", "stock availability", "product margins", "average order value", "seasonal demand", "promotional offers", "checkout experience", "repeat purchase opportunities"];
const landing = ["page messaging", "visual hierarchy", "offer clarity", "forms", "calls to action", "trust content", "mobile experience", "tracking"];
const tracking = ["conversion-event definitions", "campaign parameters", "analytics requirements", "platform tracking", "CRM reporting needs", "data-layer recommendations", "attribution review"];
const reporting = ["spend", "impressions", "reach", "clicks", "click-through rate", "conversion activity", "cost per result", "landing-page performance", "audience performance", "creative performance", "completed tests", "next priorities"];
const multilingual = ["campaign structure", "audience segmentation", "ad copy", "landing pages", "visual hierarchy", "keyword research", "reporting"];
const collaboration = ["video meetings", "shared campaign plans", "structured approval rounds", "creative review", "performance reports", "budget discussions", "optimisation reviews", "collaboration during suitable UAE business hours"];
const costs = ["number of platforms", "campaign objectives", "audience complexity", "number of markets", "media budget", "creative volume", "landing-page requirements", "email sequences", "tracking setup", "CRM integration", "reporting depth", "testing requirements", "stakeholder approvals", "campaign duration"];
const process = [["Discovery", "We review business goals, audiences, offers, previous activity, website readiness and tracking."], ["Research and Planning", "We assess competitors, channels, campaign opportunities, budget priorities and measurement requirements."], ["Campaign Setup", "We organise approved campaign structures, targeting, messaging, creative and conversion actions."], ["Launch", "Campaigns are reviewed and activated after required access, tracking and approvals are confirmed."], ["Testing and Optimisation", "We review audiences, search terms, creative, placements, budgets and conversion signals."], ["Reporting", "We document activity, performance indicators, limitations and next recommendations."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section dm-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="dm-prose">{children}</div></section>; }

export default function DigitalMarketingUaePage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page digital-marketing-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/digital-marketing">Digital Marketing</a></li><li aria-hidden="true">/</li><li><span aria-current="page">United Arab Emirates</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Digital Marketing United Arab Emirates</span><h1>Digital Marketing Services for UAE Businesses</h1><p>For organisations comparing digital marketing agency UAE providers, the right partner should offer more than isolated ads or scheduled social posts. Effective digital marketing requires a clear strategy, suitable channels, useful creative, reliable tracking and ongoing optimisation based on evidence.</p><p>Vorevix supports UAE startups, SMEs, eCommerce brands, SaaS companies, professional-service firms and established organisations through remote digital-marketing collaboration. Our work can include campaign discovery, audience research, competitor analysis, channel planning, paid search, paid social, content distribution, email marketing, remarketing, eCommerce marketing, analytics, reporting and monthly optimisation.</p><p>We do not promise guaranteed leads, fixed conversion numbers, instant sales or positive return on investment. Campaign performance depends on the offer, audience, budget, competition, creative, landing pages, tracking and sales process.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UAE Marketing Priorities <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-social.png" alt="Digital campaign planning by Vorevix" width="1182" height="1330" fetchPriority="high"/></div></section>

    <Section title="Digital Marketing Built Around Business Goals"><p>Digital marketing should begin with a clear business objective. A campaign may generate enquiries, promote a service, support an eCommerce store, build demand, re-engage visitors, launch an offer or improve visibility among a defined audience.</p><p>A digital marketing agency UAE engagement may include:</p><List items={scope}/><p>The right mix depends on the audience, offer, assets, tracking quality, budget and sales process.</p></Section>
    <Section title="Planning Campaigns for Competitive UAE Markets" tinted><p>UAE markets can be highly competitive across real estate, retail, hospitality, technology, healthcare, professional services, fashion, education and eCommerce.</p><p>A strong campaign needs more than broad targeting. It should define the audience, problem, suitable channels and desired action.</p><p>Campaigns may create opportunities for traffic, enquiries or sales, but outcomes cannot be guaranteed. Platform costs, competition, seasonality, creative quality and landing-page performance affect results.</p><p>A professional digital marketing company in UAE markets should explain these dependencies before presenting forecasts.</p></Section>
    <Section title="Discovery, Audience and Competitor Research"><p>Discovery creates the foundation for campaign planning.</p><p>We may review:</p><List items={discovery}/><p>Audience research may examine interests, needs, behaviours, buying considerations and channel usage. Competitor analysis may identify messaging, offers, calls to action, creative formats and channel opportunities.</p><p>Research does not guarantee campaign success, but supports more informed planning.</p></Section>
    <Section title="Channel Planning and Media Strategy" tinted><p>Not every business needs every digital channel. Channel planning allocates budget and effort according to audience behaviour, campaign goals and resources.</p><p>The recommended mix may include:</p><List items={channels}/><p>A digital marketing agency UAE strategy should separate agency fees from media budget and explain each channel's role.</p></Section>
    <Section title="Paid Search and Google Ads"><p>Paid search can help businesses appear when users actively search for relevant products or services.</p><p>Work may include:</p><List items={paidSearch}/><p>Google Ads is not SEO. Paid search provides advertising visibility, while SEO focuses on organic search.</p><p>Ad approval remains subject to platform policies and review. Vorevix does not guarantee approval, fixed cost per lead or immediate success.</p></Section>
    <Section title="Paid Social Campaigns" tinted><p>Paid social can support awareness, traffic, lead generation, remarketing and eCommerce campaigns.</p><p>Depending on audience and scope, platforms may include:</p><List items={socialPlatforms}/><p>Work may include audience planning, structure, creative requirements, ad copy, testing, budget allocation and performance review.</p><p>Estimated reach depends on budget, targeting, competition and platform inventory. A digital marketing agency in UAE markets should not treat every platform as equally relevant.</p></Section>
    <Section title="Content Marketing and Distribution"><p>Content marketing can support audiences at different stages of consideration.</p><p>Campaign content may include:</p><List items={content}/><p>Creation and distribution should be scoped separately where appropriate. Campaign content on this page is distinct from complete organic-search content strategy, which belongs to SEO.</p></Section>
    <Section title="Email Marketing and Lifecycle Communication" tinted><p>Email marketing can support lead nurturing, customer communication, product promotion and re-engagement.</p><p>Work may include:</p><List items={email}/><p>Automation may require an approved platform, CRM or eCommerce system. Results depend on list quality, consent, deliverability, relevance, offer and timing.</p><p>Vorevix does not imply legal or privacy compliance expertise.</p></Section>
    <Section title="Lead Generation and Demand Support"><p>Digital campaigns can support lead generation by connecting suitable audiences with a clear offer and conversion path.</p><p>Work may involve:</p><List items={leads}/><p>Campaigns cannot guarantee lead quantity or quality. Outcomes depend on demand, targeting, offer relevance, forms, response time and the client's sales process.</p><p>Vorevix provides marketing support rather than sales outsourcing or call-centre services.</p></Section>
    <Section title="Remarketing and Audience Re-engagement" tinted><p>Remarketing can reconnect with users who previously visited a website, viewed a product or interacted with content.</p><p>Possible audiences include:</p><List items={remarketing}/><p>Remarketing requires suitable consent, platform access, tracking and audience size. Availability and delivery remain subject to platform rules and privacy settings.</p></Section>
    <Section title="eCommerce Marketing"><p>eCommerce marketing may include paid search, Shopping Ads, paid social, remarketing, promotional email and campaign analysis.</p><p>Important considerations include:</p><List items={ecommerce}/><p>A broad digital marketing agency UAE page covers eCommerce at a high level. Complex stores may need specialist scope depending on platform, catalogue size, integrations and reporting.</p></Section>
    <Section title="Landing-Page and Conversion Recommendations" tinted><p>Campaign performance can be limited by unclear landing pages, weak calls to action, slow loading, poor mobile presentation or complicated forms.</p><p>Digital marketing may recommend improvements to:</p><List items={landing}/><p>Campaigns requiring new pages can connect with our <a href="/united-arab-emirates/web-design">web design services for UAE businesses</a>.</p><p>Products or journeys requiring research, prototypes or interface improvements can use our <a href="/united-arab-emirates/ui-ux-design">UI/UX design services for UAE businesses</a>.</p></Section>
    <Section title="Tracking, Analytics and Attribution"><p>Tracking helps teams understand what happened after users interacted with a campaign.</p><p>Planning may include:</p><List items={tracking}/><p>Tracking, CRM or technical requirements can be implemented through our <a href="/united-arab-emirates/web-development">web development services for UAE businesses</a>.</p><p>Attribution is rarely perfect. Privacy settings, multiple devices, offline conversions and incomplete integrations affect reporting.</p></Section>
    <Section title="Reporting, Testing and Monthly Optimisation" tinted><p>Digital marketing reporting should explain delivery, performance and next actions.</p><p>Reports may include:</p><List items={reporting}/><p>For digital marketing agency UAE engagements, Vorevix can coordinate reviews during suitable UAE business hours.</p><p>New campaigns may require a learning period. Cost per lead or acquisition can fluctuate as campaigns learn and markets change.</p></Section>
    <Section title="Arabic and Multilingual Campaign Planning"><p>UAE businesses may need English, Arabic or multilingual campaign assets.</p><p>Multilingual planning can affect:</p><List items={multilingual}/><p>Arabic campaign management and copywriting require verified language capability. Where approved Arabic content is supplied by a qualified partner, Vorevix can coordinate campaign structure and visual application.</p><p>Native Arabic campaign expertise is not claimed without verification.</p></Section>
    <Section title="Remote Collaboration Across the UAE" tinted><p>Vorevix works remotely with organisations across the United Arab Emirates.</p><p>A digital marketing agency UAE engagement may include:</p><List items={collaboration}/><p>National availability does not imply a UAE office, UAE-based team, local phone number, UAE clients or regional awards unless independently verified.</p></Section>
    <Section title="Digital Marketing Cost Factors in the UAE"><p>Digital marketing cost depends on campaign scope, channels, creative requirements, media budget and reporting needs.</p><p>Common factors include:</p><List items={costs}/><p>Agency fees and media spend should be shown separately.</p><p>A digital marketing agency UAE proposal should clarify whether creative production, landing-page design, development, platform fees and third-party tools are included.</p><p>Vorevix does not publish invented AED pricing, VAT statements, guaranteed cost-per-lead figures or fixed media outcomes.</p></Section>
    <section className="wd-section dm-section wd-tinted"><div className="wd-section-heading"><h2>Our Digital Marketing Process</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="wd-section dm-section"><div className="wd-section-heading"><h2>Why Work With Vorevix?</h2><p>Our digital marketing agency UAE approach combines campaign strategy, channel planning, paid media, content distribution, email, remarketing, analytics and ongoing optimisation without promising guaranteed commercial results.</p></div><div className="dm-prose"><p>Businesses may work with Vorevix for discovery, audience research, competitor analysis, paid search, paid social, content, email, lead-generation support, remarketing, eCommerce marketing, tracking, reporting and optimisation.</p><p>Long-term organic-search support is available through our <a href="/united-arab-emirates/seo-services">SEO services for UAE businesses</a>.</p><p>Campaigns requiring clearer positioning or visual identity can begin with our <a href="/united-arab-emirates/branding-services">branding services for UAE businesses</a>.</p><p>For the complete global approach, <a href="/services/digital-marketing">explore our complete digital marketing services</a>.</p></div></section>
    <section className="wd-section dm-section wda-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="wda-faq-list">{digitalMarketingUaeFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `digital-marketing-uae-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan Your UAE Digital Marketing Campaign</h2><p>Effective digital marketing requires clear objectives, suitable channels, useful creative, reliable tracking and ongoing review.</p><p>Vorevix helps UAE businesses plan, launch and optimise coordinated campaigns across paid search, paid social, content, email and remarketing.</p><p>Share your business goals, target audiences, current channels, media budget expectations and existing campaign challenges. We will review the requirements and recommend the next practical step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UAE Marketing Priorities <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
