import { useState } from "react";
import { ArrowRight, BarChart3, ChevronDown } from "lucide-react";
import { digitalMarketingAustraliaFaqs } from "../digitalMarketingAustraliaFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";

const problems = [["No Clear Strategy", "Campaigns may begin because a platform is popular, without a defined audience, action, channel role, message, budget, measurement plan or lead follow-up."], ["Disconnected Marketing Channels", "SEO, Google Ads, social media, email and website activity can create conflicting messages, weak landing experiences and inconsistent reporting when managed separately."], ["Traffic Without Conversion", "More visits do not create value when the offer, page relevance, trust, forms, mobile usability, pricing, next steps or performance create friction."], ["Weak Tracking", "Missing or duplicated events, unrecorded forms and calls, incomplete ecommerce data, absent UTM parameters and internal traffic can weaken decision-making."], ["Poor Landing Pages", "Generic headlines, weak ad relevance, unclear benefits, missing proof, long forms, poor mobile layouts and competing actions can restrict campaign performance."], ["Inconsistent Content", "Content should support awareness, customer questions, evaluation, objections, conversion, follow-up and retention rather than filling a publishing schedule."], ["Budget Spread Too Thinly", "Dividing limited resources across too many platforms can prevent any channel from receiving enough data, creative or attention to learn effectively."], ["Reporting Without Insight", "Useful reporting should identify meaningful activity, audience response, landing-page problems, wasted budget, next tests and remaining uncertainty."]];
const services = [
  ["Digital Marketing Strategy", "Connect business goals, audience research, competitors, customer journeys, channel selection, offers, messaging, budget, conversion paths and measurement in a practical roadmap."],
  ["Search Engine Optimisation", <>Improve organic discovery through keyword research, technical SEO, on-page work, content, internal links, local and ecommerce SEO. Explore <a href="/services/seo-services">SEO services</a> and <a href="/services/seo-services-australia">SEO Services Australia</a>.</>],
  ["Google Ads and Paid Search", "Support account review, campaign structure, keywords, negative terms, ad copy, tracking, audiences, budgets, bidding, remarketing, landing pages and ongoing optimisation without promising a fixed return."],
  ["Social Media Advertising", "Plan suitable audiences, campaigns, creative, copy, lead forms, website campaigns, remarketing, budgets, testing and reporting across relevant social platforms."],
  ["Content Marketing", "Use service pages, landing pages, articles, guides, lead magnets, email and social content to support search, education, campaign messaging and decision-making."],
  ["Email Marketing and Automation", "Develop campaigns, welcome journeys, lead nurturing, segmentation, abandoned-cart sequences, customer communication, re-engagement and reporting."],
  ["Ecommerce Marketing", "Coordinate shopping campaigns, ecommerce SEO, paid social, remarketing, product pages, email automation, promotions and conversion tracking."],
  ["Lead Generation Campaigns", "Connect audience targeting, offers, paid media, forms, landing pages, tracking, qualification and follow-up around useful business actions."],
  ["Landing Pages and Conversion Optimisation", <>Improve messaging, hierarchy, trust, forms, mobile usability and tracking. Wider support can connect with <a href="/services/web-design">web design services</a>, <a href="/services/web-design-australia">Web Design Australia</a>, <a href="/services/web-development-services">web development services</a> and <a href="/services/web-development-australia">Web Development Australia</a>.</>],
  ["Analytics, Tracking and Reporting", "Define relevant events, campaign parameters, platform tracking, reporting and analysis so activity can be connected with meaningful outcomes."],
  ["Campaign Creative Support", "Coordinate message, format, brand presentation and variations needed for structured campaign testing."],
  ["Ongoing Campaign Management", "Review performance, budgets, audiences, search terms, creative, landing experiences and changing priorities through an agreed management cycle."],
];
const channels = [["Paid Channels", "Google Ads and paid social can create targeted visibility and faster campaign data, but require controlled budgets, suitable landing pages and reliable tracking."], ["Organic Channels", "SEO, useful content and organic social can strengthen discovery, education and brand visibility over a longer period."], ["Owned Channels", "The website, landing pages, email list and customer data give the business direct channels for communication, conversion and retention."]];
const journey = [["Awareness", "Introduce a relevant problem, category, product or service to suitable audiences."], ["Consideration", "Help people compare options, understand benefits and resolve important questions or objections."], ["Conversion", "Provide a clear, usable route to enquire, register, book or purchase."], ["Retention", "Use relevant communication, support, offers and customer journeys to encourage continued engagement."]];
const process = [["1. Discovery and Goal Setting", "Understand the business, audience, offer, current activity, budget, constraints and meaningful outcomes."], ["2. Market and Competitor Research", "Review the market, competitor messages, channel activity, offers and observable opportunities."], ["3. Audience and Customer Journey Planning", "Define audience needs, intent, objections, touchpoints and the information needed at each stage."], ["4. Channel and Campaign Strategy", "Select channels, offers, messages, assets, landing experiences, priorities and budget allocation."], ["5. Tracking and Measurement Setup", "Define events, analytics, campaign parameters, platform tracking and reporting requirements before launch."], ["6. Campaign Build and Launch", "Prepare audiences, campaigns, creative, copy, landing pages, forms and quality checks for controlled delivery."], ["7. Testing and Optimisation", "Review audiences, messages, search terms, creative, budgets, landing pages and conversion behaviour through defined tests."], ["8. Reporting and Strategy Review", "Explain results, completed work, uncertainty, next actions and changes required in the wider strategy."]];
const models = [["Small Businesses", "Keep scope and budget focused on the channels most closely connected to genuine customer demand."], ["Professional Services", "Support trust, expertise, qualified enquiries and longer evaluation journeys."], ["Ecommerce Brands", "Coordinate product discovery, paid shopping, remarketing, email, conversion tracking and repeat-purchase activity."], ["B2B Companies", "Combine targeted media, useful content, landing pages and nurturing for longer sales cycles."], ["SaaS Companies", "Support demonstrations, trials, registrations, product education, onboarding and customer acquisition journeys."], ["Startups", "Test priority audiences, offers and messages without spreading early resources across every platform."], ["Multi-Location Businesses", "Coordinate central campaigns and accurate regional relevance without false office claims."], ["Established Brands", "Audit existing channels, tracking, customer data and campaign history before expanding or restructuring activity."]];
const why = [["Strategy Before Channel Selection", "We begin with goals, audience, offer and measurement rather than recommending every available platform."], ["Connected Channel Planning", "SEO, paid media, social, content, email and website journeys are considered as parts of one customer experience."], ["Clear Measurement", "Tracking and reporting are connected with defined business actions wherever technically possible."], ["Budget Responsibility", "Budgets are reviewed according to campaign priorities and available performance evidence."], ["Honest Expectations", "We do not guarantee leads, sales, rankings or return on ad spend."], ["Ongoing Optimisation", "Campaigns are adjusted as data, business priorities and market conditions change."], ["Broader Digital Capability", <>Marketing can connect with <a href="/services/seo-services">SEO services</a>, <a href="/services/seo-services-australia">SEO Services Australia</a>, <a href="/services/web-design">web design services</a>, <a href="/services/web-design-australia">Web Design Australia</a>, <a href="/services/web-development-services">web development services</a>, <a href="/services/web-development-australia">Web Development Australia</a>, <a href="/services/ui-ux-design">UI/UX design services</a> and <a href="/services/branding">branding services</a>.</>]];

function List({items}){return <ul className="wd-checklist">{items.map(x=><li key={x}>{x}</li>)}</ul>}
function Section({title,intro,children,tinted=false}){return <section className={`wd-section wda-section${tinted?" wd-tinted":""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro&&<p>{intro}</p>}</div>{children}</section>}
function Cards({items}){return <div className="wd-card-grid">{items.map(([title,body])=><article className="wd-card" key={title}><BarChart3 className="wd-card-icon" aria-hidden="true"/><h3>{title}</h3><p>{body}</p></article>)}</div>}

export default function DigitalMarketingAustraliaPage(){const[openFaq,setOpenFaq]=useState(0);return <main className="web-development-page wda-page">
  <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Digital Marketing Services Australia</span></li></ol></nav>
  <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Digital Marketing Services Australia</span><h1>Digital Marketing Services for Businesses in Australia</h1><p>Vorevix provides digital marketing services Australia businesses can use to attract relevant audiences, improve campaign visibility and create clearer paths from interest to enquiry or purchase.</p><p>Our work can connect SEO, Google Ads, social media advertising, content, email, landing pages, analytics and ongoing campaign optimisation.</p><p>Instead of managing every channel separately, we build strategies around the customer journey, business goals, available budget and the data needed to measure progress.</p><p>Vorevix works remotely with businesses across Australia through structured planning, shared reporting, scheduled reviews and clearly defined campaign priorities.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Marketing Goals <ArrowRight size={18}/></a><a href="/services/digital-marketing">Explore Digital Marketing Services</a></div><ul className="wda-trust"><li>Strategy based on audience and business goals</li><li>SEO, paid media, social, content and email coverage</li><li>Clear tracking and campaign reporting</li><li>Ongoing testing and optimisation</li></ul></div><div className="wd-hero-visual"><img src="/service-social.png" alt="Digital marketing services for businesses in Australia by Vorevix" width="1182" height="1330" fetchPriority="high"/></div></section>
  <Section title="Digital Marketing for Australian Businesses That Need a Clearer Growth Strategy"><div className="wda-prose"><p>Digital marketing can become expensive and difficult to manage when channels operate without a shared strategy.</p><p>A business may be running Google Ads, publishing social content, sending emails and investing in SEO, yet still be unable to explain which activities are contributing to enquiries, sales or long-term growth.</p><p>Common digital marketing problems include:</p><List items={["Campaigns launching without clear goals","Marketing channels working in isolation","Traffic increasing without more enquiries","Paid advertising running without reliable tracking","Weak or inconsistent messaging","Landing pages failing to support campaign intent","Budgets being spread across too many channels","Content being published without a defined purpose","Email lists being underused","Campaign reports showing activity without useful insight","Different agencies or teams working without coordination","No clear process for testing and optimisation"]}/><p>Our digital marketing services Australia approach begins with the business, audience and customer journey.</p><p>We review what the business is trying to achieve, how customers currently find it, which channels are already in use and where the biggest gaps or opportunities may exist.</p><p>The objective is not to use every available platform. It is to select the channels, messages and campaign priorities that make sense for the market, budget and stage of growth.</p><p>For broader location-neutral support, explore our <a href="/services/digital-marketing">general digital marketing services</a>.</p></div></Section>
  <Section title="Common Digital Marketing Problems That Limit Campaign Performance" tinted><Cards items={problems}/></Section>
  <Section title="What Effective Digital Marketing Should Support"><Cards items={[["Audience Reach","Place relevant messages in front of people likely to need the offer."],["Qualified Traffic","Evaluate traffic according to relevance and intent, not only volume."],["Stronger Messaging","Help customers understand the problem, offer, benefit and next step."],["Better Customer Journeys","Connect discovery, evaluation, conversion and retention."],["Lead Generation","Create clear routes for suitable prospects to make contact."],["Ecommerce Sales","Support product discovery, consideration, checkout and repeat purchase."],["Campaign Learning","Use testing to understand audiences, messages and offers."],["Channel Coordination","Help SEO, paid advertising, social, content and email reinforce one another."],["Measurement","Connect campaigns to suitable events, outcomes and reporting."],["Ongoing Improvement","Adapt when data, audience behaviour or priorities change."]]}/><p className="wda-note">No provider can guarantee a fixed number of leads, sales or a specific return.</p></Section>
  <Section title="Digital Marketing Services for Australian Businesses" intro="Vorevix provides a connected range of services across strategy, search, paid media, social, content, email, conversion and reporting." tinted><Cards items={services}/></Section>
  <Section title="How Paid, Organic and Owned Channels Work Together"><Cards items={channels}/></Section>
  <Section title="Digital Marketing Across the Customer Journey" tinted><Cards items={journey}/></Section>
  <Section title="Our Digital Marketing Process"><Cards items={process}/></Section>
  <Section title="Digital Marketing for Different Australian Business Models" tinted><Cards items={models}/></Section>
  <Section title="Audience and Market Research Before Campaign Launch"><div className="wda-prose"><p>Research should clarify audience needs, search and platform behaviour, objections, competitors, market expectations and the information needed before action.</p><p>This provides a stronger basis for channel, offer, message and budget decisions.</p></div></Section>
  <Section title="Campaign Tracking That Connects Activity With Outcomes" tinted><div className="wda-prose"><p>Tracking may include analytics, campaign events, forms, calls, ecommerce transactions, UTM parameters and platform integrations.</p><p>Our measurement approach follows established platforms such as <a href="https://support.google.com/analytics/answer/10089681" target="_blank" rel="noopener noreferrer">Google Analytics 4</a>, while recognising that attribution can remain imperfect.</p></div></Section>
  <Section title="Landing Pages Designed to Support Campaign Conversion"><div className="wda-prose"><p>Landing pages should connect the campaign promise with clear messaging, useful proof, usable forms, mobile layouts and an appropriate next action.</p><p>Improvement should be guided by user needs and evidence rather than unsupported conversion guarantees.</p></div></Section>
  <Section title="How Digital Marketing Budgets Are Prioritised" tinted><div className="wda-prose"><p>Budget decisions consider audience size, platform costs, competition, creative requirements, testing needs, sales cycles and available performance evidence.</p><p>A focused allocation can provide clearer learning than dividing limited resources across every channel.</p></div></Section>
  <Section title="Digital Marketing Reporting That Explains What Is Working"><div className="wda-prose"><p>Reporting should connect spend and activity with audiences, landing pages, tracked outcomes, completed changes, uncertainty and recommended next actions.</p></div></Section>
  <Section title="How Long Does Digital Marketing Take to Show Results?" tinted><div className="wda-prose"><p>Timelines vary by channel, budget, audience, offer, sales cycle, tracking quality and available campaign data.</p><p>Paid campaigns can provide data quickly, while SEO, content, email and conversion improvements often require longer-term work.</p></div></Section>
  <Section title="How Digital Marketing Services Pricing Is Determined"><div className="wda-prose"><p>Pricing depends on selected channels, campaign complexity, research, creative, landing pages, tracking, reporting, advertising budget and the level of ongoing management.</p><p>Vorevix prepares a tailored proposal after reviewing the business and campaign requirements.</p></div></Section>
  <Section title="Clear Campaign Scope, Responsibilities and Expectations" tinted><div className="wda-prose"><p>The agreed scope should define channels, deliverables, advertising spend, approvals, implementation responsibilities, tracking, reporting and review stages before activity begins.</p></div></Section>
  <Section title="Digital Marketing Support Across Australia"><div className="wda-prose"><p>Vorevix works remotely with businesses across Australia through online meetings, shared documentation, approval stages, regular reporting and structured reviews.</p><p>This supports clear delivery without claiming an Australian office or physical presence.</p></div></Section>
  <Section title="Why Choose Vorevix for Digital Marketing Services in Australia" tinted><Cards items={why}/><p className="wda-note">Learn more <a href="/about">about Vorevix</a>.</p></Section>
  <Section title="Selected Digital Marketing and Website Work"><div className="wda-prose"><p>Explore selected Vorevix work across campaign strategy, SEO, website design, development and brand communication.</p><p>Published examples should use verified information about the challenge, scope, channels, completed work, timeline, results and limitations.</p><a className="wd-text-link" href="/portfolio">View Our Portfolio <ArrowRight size={18}/></a></div></Section>
  <Section title="Digital Marketing Services Australia FAQs" tinted><div className="wda-faq-list">{digitalMarketingAustraliaFaqs.map((faq,i)=>{const open=openFaq===i,id=`dm-au-faq-${i}`;return <article className="wda-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={()=>setOpenFaq(open?-1:i)}>{faq.question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}>{faq.answer.map(p=><p key={p}>{p}</p>)}</div></article>})}</div></Section>
  <section className="wd-final-cta"><h2>Plan Your Digital Marketing Strategy in Australia</h2><p>Tell us which channels you are currently using, what you want to improve and where your campaigns are underperforming.</p><p>Vorevix will review your goals, audience, website, tracking and existing marketing activity before recommending a practical strategy.</p><p>Whether you need SEO, paid advertising, social media campaigns, email automation, better landing pages or clearer reporting, our digital marketing services Australia approach can be structured around your priorities, budget and available resources.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Marketing Goals <ArrowRight size={18}/></a><a href="/services/digital-marketing">Explore Digital Marketing Services</a></div></section>
</main>}
