import { useState } from "react";
import { ArrowRight, BarChart3, ChevronDown } from "lucide-react";
import { digitalMarketingNewZealandFaqs } from "../digitalMarketingNewZealandFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./DigitalMarketingPage.css";

const costs = ["number of channels", "campaign objectives", "media budget", "audience complexity", "research requirements", "campaign structure", "creative and copy requirements", "landing-page needs", "email or automation scope", "tracking and analytics setup", "reporting depth", "optimisation frequency", "stakeholder complexity", "ongoing management"];
const reasons = ["structured discovery and campaign planning", "audience and competitor research", "channel selection based on business needs", "paid search and paid social coordination", "content and campaign messaging", "email marketing and lead nurturing", "lead-generation planning", "remarketing", "landing-page coordination", "analytics and reporting", "ongoing optimisation", "coordination with SEO, branding, design and development", "remote collaboration across New Zealand business hours", "practical recommendations without guaranteed outcomes"];
const process = [["Discovery", "We review the business, audience, offer, current activity, budget considerations and objectives."], ["Audit and Analysis", "Existing channels, tracking, assets, messaging and competitor activity are assessed where relevant."], ["Strategy and Channel Planning", "Suitable channels, campaign stages, responsibilities, timelines and measurement requirements are defined."], ["Campaign Development", "Audiences, messaging, creative needs, landing pages and tracking plans are prepared."], ["Launch and Monitoring", "Approved campaigns are launched and monitored according to the agreed scope."], ["Reporting and Optimisation", "Available data is reviewed, findings are communicated and practical adjustments are recommended."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section dm-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="dm-prose">{children}</div></section>; }

export default function DigitalMarketingNewZealandPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page digital-marketing-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/digital-marketing">Digital Marketing</a></li><li aria-hidden="true">/</li><li><span aria-current="page">New Zealand</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Digital Marketing New Zealand</span><h1>Digital Marketing Services for New Zealand Businesses</h1><p>For businesses comparing digital marketing agency NZ providers, the right partner should do more than manage isolated campaigns. Effective digital marketing connects strategy, audience understanding, channel selection, creative execution, tracking and ongoing optimisation so every activity supports a commercial objective.</p><p>As a digital marketing agency NZ partner, Vorevix supports New Zealand businesses through remote collaboration. We help organisations plan campaigns, choose suitable channels, coordinate content, manage paid media, support lead generation and improve visibility into campaign performance.</p><p>Our digital marketing agency NZ approach does not promise guaranteed leads, sales, revenue or return on ad spend. Instead, we focus on informed planning, practical execution, measurable activity and refinement based on available data.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Digital Marketing Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-social.png" alt="Digital campaign planning by Vorevix" width="1182" height="1330" fetchPriority="high"/></div></section>

    <Section title="Digital Marketing Built Around Business Objectives"><p>A digital marketing agency NZ engagement should begin with a clear understanding of the business, its audience, offer and campaign objectives.</p><p>Vorevix connects strategy with execution so campaigns are not launched simply because a channel is popular. Depending on scope, our work may include audience research, competitor analysis, channel planning, paid search, paid social, content marketing, email marketing, remarketing, lead generation and reporting.</p><p>This reduces fragmented activity and clarifies how channels support a wider plan.</p></Section>
    <Section title="Discovery, Audits and Campaign Planning" tinted><p>A strong campaign begins with discovery. We review the business, current marketing activity, audience, competitors, website, available assets, budget considerations and priorities.</p><p>Where useful, an initial digital audit may identify gaps in targeting, messaging, landing pages, tracking, channel mix or reporting. The aim is to identify what works, what is unclear and what should change.</p><p>For digital marketing agency NZ projects, workshops and review sessions can be scheduled around New Zealand business hours. Decisions, responsibilities and approval stages are documented to reduce avoidable delays.</p></Section>
    <Section title="Audience Research and Channel Selection"><p>Audiences use platforms, messages and buying journeys differently.</p><p>Audience research may review customer profiles, motivations, objections, existing data and common decision factors. Competitor research can reveal how similar businesses position offers.</p><p>Channel selection should follow the evidence available. A business may need paid search to capture existing demand, paid social to reach defined audiences, email to nurture enquiries or content to support education and consideration.</p><p>The selected mix should reflect the audience, offer, budget and available resources.</p></Section>
    <Section title="Paid Search and Google Ads" tinted><p>Paid search can help businesses appear when potential customers are actively searching for relevant products or services.</p><p>Our work may include campaign structure, keyword selection, ad groups, ad copy, negative keywords, audience settings, location targeting, conversion actions and ongoing optimisation.</p><p>Google Ads may support search, shopping, display or remarketing activity where appropriate. Microsoft Ads may also be considered when it suits the audience and scope.</p><p>Paid media can create immediate visibility, but it does not guarantee enquiries, sales or profitable returns. Results depend on the market, offer, competition, budget, website experience, tracking quality and execution.</p></Section>
    <Section title="Paid Social Campaigns"><p>Paid social allows businesses to reach audiences based on interests, behaviours, demographics, professional attributes and previous interactions.</p><p>Campaigns may use Meta, LinkedIn or other suitable networks. Work may include campaign objectives, audience structure, creative direction, ad copy, testing plans and reporting.</p><p>Paid social can support awareness, promotion, retargeting or demand creation. A digital marketing agency NZ campaign should not rely on one creative or audience indefinitely because performance can change over time.</p></Section>
    <Section title="Content Marketing and Campaign Messaging" tinted><p>Content marketing can support awareness, education and consideration by answering relevant questions and communicating the value of an offer.</p><p>Campaign content may include landing-page copy, blog content, social posts, downloadable resources, ads, email sequences and supporting visuals.</p><p>Clear messaging matters because targeting cannot fix an unclear offer.</p><p>Vorevix can coordinate campaign messaging with the approved brand direction. Campaigns requiring deeper positioning, messaging or visual identity can connect with our <a href="/new-zealand/branding-services">branding services for New Zealand businesses</a>.</p></Section>
    <Section title="Email Marketing and Lead Nurturing"><p>Email marketing can help businesses maintain communication with prospects, customers and subscribers when suitable lists, consent and relevant content are available.</p><p>A campaign may include welcome sequences, lead nurturing, promotional emails, product updates or re-engagement communication. Work can involve content planning, sequence structure, campaign copy, segmentation and performance review.</p><p>Email results depend on list quality, consent, deliverability, relevance and timing. It should not be treated as a guaranteed source of revenue.</p></Section>
    <Section title="Lead Generation and Remarketing" tinted><p>Lead-generation campaigns are designed to create and capture demand through relevant offers, targeting, landing pages and follow-up processes.</p><p>A professional-services firm may use consultation requests or downloadable resources, while an eCommerce business may focus on product discovery, remarketing or email capture.</p><p>Vorevix may help plan campaign stages, calls to action, forms, qualification steps and follow-up requirements.</p><p>Remarketing can reconnect with people who previously visited a website or interacted with a campaign where platform rules, privacy requirements and consent allow.</p><p>Lead quantity, quality and conversion cannot be guaranteed. Outcomes depend on the offer, demand, budget, competition, targeting, landing-page experience and sales process.</p></Section>
    <Section title="Landing Pages and Website Coordination"><p>Campaign performance can be affected by the page users reach after clicking an ad.</p><p>A landing page should communicate the offer clearly, remain consistent with the advertisement and make the next action easy to understand. Page speed, mobile usability, form length, trust information and content hierarchy may all influence behaviour.</p><p>Digital marketing can define campaign objectives, required content, tracking needs and conversion actions. Complete website planning and visual design remain within our <a href="/new-zealand/web-design">New Zealand web-design service</a>.</p><p>Tracking, integrations and landing pages requiring technical implementation can be supported through our <a href="/new-zealand/web-development">New Zealand web-development service</a>.</p><p>Complex journeys or usability concerns can be investigated through our <a href="/new-zealand/ui-ux-design">New Zealand UI/UX design service</a>.</p></Section>
    <Section title="Analytics, Tracking and Reporting" tinted><p>Measurement helps teams understand campaign activity and identify areas for review.</p><p>Depending on scope, reporting may include spend, impressions, clicks, engagement, conversions, cost per action, revenue data and channel-level observations.</p><p>Tracking may use analytics platforms, advertising pixels, tag-management tools, CRM data or other sources. However, tracking is rarely complete. Consent choices, device changes, platform restrictions and attribution models can limit visibility.</p><p>Vorevix treats attribution as an informed estimate rather than perfect proof of every customer interaction.</p></Section>
    <Section title="Campaign Optimisation and Testing"><p>Campaign optimisation uses performance data to inform decisions about budget, targeting, creative, messaging and landing pages.</p><p>Adjustments may include pausing weak elements, testing alternatives, refining audiences or reallocating spend. A/B testing can help compare variations, but it does not always produce a reliable winner.</p><p>Our digital marketing agency NZ process favours documented decisions and meaningful changes rather than constant adjustments without enough evidence.</p></Section>
    <Section title="SEO Coordination Without Service Overlap" tinted><p>Organic search can support the wider marketing plan, but complete SEO methodology should remain separate from campaign management.</p><p>Technical SEO, keyword research, on-page optimisation, crawling, indexing, structured data and backlink strategy require a dedicated SEO engagement.</p><p>This separation gives each service a clear purpose while allowing both areas to support shared commercial goals.</p></Section>
    <section className="wd-section dm-section wd-tinted"><div className="wd-section-heading"><h2>Our Digital Marketing Process for New Zealand Teams</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><BarChart3 className="wd-card-icon" aria-hidden="true"/><h3>{title}</h3><p>{body}</p></article>)}</div><p className="wda-note">For broader methodology, <a href="/services/digital-marketing">explore our complete digital marketing services</a>.</p></section>
    <Section title="Remote Collaboration Across New Zealand"><p>As a digital marketing agency NZ partner, Vorevix works with New Zealand organisations through remote meetings, shared documents, dashboards, written updates and agreed approval stages.</p><p>We can collaborate with founders, directors, marketing teams, sales teams, designers and developers across New Zealand business hours.</p><p>National availability does not imply a New Zealand office, local phone number or New Zealand-based marketing team. Services are delivered through remote collaboration.</p></Section>
    <Section title="What Influences Digital Marketing Cost in New Zealand?" tinted><p>The cost of working with a digital marketing agency NZ depends on campaign scope, channel complexity and management requirements.</p><p>Important factors may include:</p><List items={costs}/><p>Media spend and agency fees should be considered separately.</p><p>Vorevix prepares a tailored proposal after reviewing the business, objectives and expected scope. We do not publish unsupported NZD prices, GST statements, guaranteed results or fixed timelines for every campaign.</p></Section>
    <section className="wd-section"><div className="wd-section-heading"><h2>Why Choose Vorevix as Your Digital Marketing Agency NZ?</h2><p>Our digital marketing agency NZ approach combines strategy, multi-channel planning, execution and reporting without forcing every business into the same package.</p></div><div className="wd-card-grid">{reasons.map((reason) => <article className="wd-card" key={reason}><BarChart3 className="wd-card-icon" aria-hidden="true"/><h3>{reason}</h3></article>)}</div></section>
    <section className="wd-section dm-section wda-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="wda-faq-list">{digitalMarketingNewZealandFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `digital-marketing-nz-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan Your Next Digital Campaign</h2><p>A strong digital marketing agency NZ engagement should connect business objectives, audience understanding, channel selection, campaign execution and measurement.</p><p>Vorevix helps New Zealand businesses plan and manage activity across paid media, content, email, lead generation, remarketing and reporting.</p><p>Share your current marketing activity, target audience, campaign objectives, available channels and expected budget range. We will review it and discuss the next step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Digital Marketing Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
