import { useState } from "react";
import { ArrowRight, BarChart3, ChevronDown } from "lucide-react";
import { digitalMarketingFaqs } from "../digitalMarketingFaqs";
import "./WebDevelopmentPage.css";
import "./DigitalMarketingPage.css";

const services = [
  { title: "Digital Marketing Strategy", paragraphs: ["A digital marketing strategy defines what your business needs to achieve, who the campaign must reach and which channels are most suitable for that objective.", "We review your business model, target audience, current marketing activity, competitive environment and available resources before recommending a campaign direction.", "Strategy work may include:"], items: ["Business and campaign objectives", "Audience and customer research", "Customer journey planning", "Competitor and market analysis", "Channel selection", "Campaign priorities", "Budget guidance", "Key performance indicators", "Content and creative requirements", "Measurement planning"], closing: ["Our digital marketing services begin with strategy so campaigns are connected to a practical roadmap instead of being managed as unrelated marketing tasks.", "A clear strategy also helps identify which channels should not be used. This prevents budget from being divided between platforms that are unlikely to support your business goals."] },
  { title: "Paid Search and PPC Management", paragraphs: ["Our PPC management services help businesses reach people actively searching for relevant products, services or solutions.", "Depending on the campaign, paid search activity may include Google Ads, Microsoft Advertising, search campaigns, display campaigns, shopping campaigns and remarketing.", "Paid search support may include:"], items: ["Keyword and search-intent research", "Campaign and ad-group structure", "Search-term reviews", "Advertisement copy", "Negative keyword management", "Audience targeting", "Conversion tracking", "Budget monitoring", "Landing-page recommendations", "Campaign testing", "Ongoing optimisation"], closing: ["The goal is not simply to generate clicks. These digital marketing services connect paid traffic with valuable actions such as enquiries, purchases, bookings, sign-ups or qualified leads.", "Campaigns are monitored so budgets can be directed towards suitable search terms, relevant audiences and advertisements that contribute to the campaign objective."] },
  { title: "Paid Social Advertising", paragraphs: ["Paid social advertising can help businesses reach selected audiences, create demand, promote offers, support product launches and reconnect with previous website visitors.", "Depending on your audience and campaign objective, suitable platforms may include Meta, LinkedIn or TikTok.", "Paid social support may include:"], items: ["Campaign objective selection", "Audience segmentation", "Core audience targeting", "Custom audiences", "Lookalike audiences", "Remarketing audiences", "Campaign copy", "Creative direction", "Budget allocation", "Conversion tracking", "Creative testing", "Ongoing campaign optimisation"], closing: ["We do not recommend every platform for every business. Channel selection depends on the audience, offer, sales process, campaign goal, available creative assets and advertising budget.", "Paid social can also support awareness campaigns where users may not already be searching for your product or service. This makes it useful for introducing an offer before capturing demand through other channels."] },
  { title: "Social Media Marketing", paragraphs: ["Our social media marketing services help businesses communicate consistently, support campaigns and connect brand activity with audience interests.", "The service scope may include:"], items: ["Social media strategy", "Platform selection", "Content planning", "Campaign messaging", "Organic content direction", "Brand consistency", "Paid and organic coordination", "Promotional campaign support", "Reporting and recommendations"], closing: ["Social media may support visibility, customer communication, audience engagement, lead generation or remarketing. Its role should be clearly defined within the wider marketing strategy.", "For some businesses, social media mainly supports brand communication. For others, it can contribute to direct-response campaigns, product education, customer retention or lead generation.", "We identify the role each platform needs to perform before planning content or campaign activity."] },
  { title: "Content Marketing", paragraphs: ["Our content marketing services help businesses create useful material that supports awareness, consideration, lead generation and conversion.", "Content may support landing pages, advertising, social media, email and long-term organic visibility.", "Content support may include:"], items: ["Content strategy", "Campaign messaging", "Website copy", "Landing-page copy", "Articles and guides", "Lead magnets", "Email content", "Social media content", "Promotional copy", "Distribution planning"], closing: ["These digital marketing services treat content as a campaign asset with a clear purpose rather than material produced only to fill a publishing schedule.", "Each piece of content should support a specific customer need, campaign message or stage of the decision-making journey."] },
  { title: "Email Marketing and Lead Nurturing", paragraphs: ["Our email marketing services help businesses continue the conversation after someone submits an enquiry, downloads a resource, joins a mailing list or completes a purchase.", "Email activity may include:"], items: ["Campaign planning", "Welcome emails", "Promotional campaigns", "Lead-nurturing sequences", "Audience segmentation", "Re-engagement campaigns", "Customer communication", "Message testing", "Performance reporting", "Ongoing optimisation"], closing: ["Email is particularly useful where customers require more information or time before making a decision.", "It can also support retention by helping businesses communicate with previous customers, share relevant offers and encourage repeat action.", "When connected with other digital marketing services, email can support the customer journey after paid campaigns, social activity, content downloads or lead-generation forms have captured initial interest."] },
  { title: "Lead Generation Campaigns", paragraphs: ["Our lead generation services are designed to turn audience attention into useful business actions such as enquiries, consultations, quotations, bookings and sales conversations.", "A lead-generation campaign may involve:"], items: ["Audience research", "Campaign offers", "Paid search", "Paid social", "Lead forms", "Landing pages", "Campaign messaging", "Conversion tracking", "Remarketing", "Lead-quality reviews", "Cost-per-lead analysis", "Ongoing optimisation"], closing: ["Traffic alone is not the final measure of success. We focus on actions that contribute to the sales process and identify where campaign performance can be improved.", "Lead volume should also be reviewed alongside lead quality. Generating more enquiries is not useful when the audience, offer or qualification process is poorly aligned with the business.", "Our digital marketing services connect campaign targeting with landing pages, forms and tracking so lead-generation decisions can be based on meaningful data."] },
];

const process = [
  ["Understand the Business", "We begin by understanding your products or services, target markets, sales process, existing marketing activity and commercial priorities. This establishes what marketing needs to achieve and highlights the challenges or opportunities that should influence campaign planning. We may also review current campaigns, website journeys, landing pages, tracking setup and available creative assets."],
  ["Research the Audience", "We examine who the campaign needs to reach, what matters to that audience and how potential customers research or evaluate solutions. Research may consider customer needs, common questions, search intent, platform behaviour, purchase motivations, objections, decision factors and customer journey stages."],
  ["Define Goals and KPIs", "Clear goals help determine which channels, campaign formats and measurement methods should be used. Goals may include qualified enquiries, purchases, bookings, demonstrations, registrations, downloads, lead volume, cost per lead, cost per acquisition, conversion rate or return on advertising spend."],
  ["Select the Right Channels", "Channel selection depends on the target audience, product or service, campaign objective, available budget, sales cycle, existing assets, competition and available performance data. The strategy may use one focused channel or a coordinated combination."],
  ["Plan Campaigns and Assets", "Before launch, we identify campaign structure, audience segments, offers, advertisement messaging, creative assets, landing pages, lead forms, conversion tracking, email follow-up and supporting content."],
  ["Launch, Test and Optimise", "Campaigns are launched with a controlled structure. Optimisation may involve audience refinement, creative testing, budget and bid adjustments, keyword changes, exclusions, message improvements, conversion reviews, landing-page recommendations and remarketing updates."],
  ["Report and Plan the Next Actions", "Reports clarify which campaigns performed, how audiences responded, where budget was used, which conversions occurred, what changed, what should be tested next and where problems or opportunities may exist."],
];

const channels = [
  ["Paid Search", "Paid search is useful when users are actively looking for a product, service or solution. It can support direct enquiries, purchases, bookings and other high-intent actions."],
  ["Paid Social", "Paid social can help reach selected audiences, generate awareness, introduce offers and support remarketing. It is particularly useful when audience interests, job roles, behaviours or demographic characteristics are important to targeting."],
  ["Organic Social Media", "Organic social media supports brand communication, content distribution and regular audience interaction. Its role depends on the platform, audience and type of business."],
  ["Content Marketing", "Content helps businesses educate audiences, answer questions, demonstrate knowledge and support longer buying journeys. It can also strengthen email, social media, paid advertising and search campaigns."],
  ["Email Marketing", "Email supports lead nurturing, customer retention, promotions, follow-up and repeat action. It is especially useful when prospects are not ready to convert during their first interaction."],
  ["Lead Generation Campaigns", "Lead-generation campaigns are suitable for businesses that need enquiries, consultations, quotations, bookings or sales conversations."],
  ["Search Engine Optimisation", <>SEO supports long-term visibility in organic search results. Because SEO requires its own technical, content and authority strategy, it is available through our <a href="/services/seo-services">SEO services</a>.</>],
];

const support = [
  ["Digital Marketing Strategy Project", "Suitable for businesses that need a clear plan before committing to ongoing campaign activity. This may include a current marketing review, audience research, channel recommendations, campaign priorities, KPI selection, measurement planning and a strategic roadmap."],
  ["Campaign Setup and Launch", "Suitable for businesses with a defined campaign, launch date, offer or short-term objective. Support may include campaign strategy, audience planning, platform configuration, tracking and launch preparation."],
  ["Ongoing Campaign Management", "Suitable for businesses requiring continuous monitoring, testing, budget management and reporting. The final scope depends on the number of campaigns, channels and optimisation requirements."],
  ["Multi-Channel Marketing Support", "Suitable for businesses that require coordinated digital marketing services across paid search, paid social, content, email and lead generation. This approach helps maintain consistency across campaign messaging, landing experiences and performance reporting."],
];

const businessModels = [
  ["Service Businesses", "Generate enquiries, consultations, quotations and sales opportunities. Campaigns may focus on high-intent search traffic, lead forms, landing pages and follow-up journeys."],
  ["Ecommerce Businesses", "Support product discovery, promotions, remarketing and online purchases. Performance may be assessed through revenue, conversion rate, cost per purchase and return on advertising spend."],
  ["B2B Companies", "Reach decision-makers, build demand, generate leads and support longer sales cycles. Campaigns may need to combine paid media, educational content, landing pages and lead nurturing."],
  ["SaaS and Technology Companies", "Support demonstrations, free trials, account registrations, product education and customer acquisition."],
  ["Growing Brands", "Improve visibility, campaign consistency, audience reach and customer journeys across several marketing channels."],
  ["New Product or Service Launches", "Plan the message, audience targeting, creative assets, landing pages and launch activity around a defined objective."],
];

const why = [
  ["Strategy Before Activity", "We define the goal, audience, customer journey and measurement requirements before recommending marketing channels."],
  ["Connected Services", <>Campaign activity can be aligned with branding, website design, user experience, development and SEO where broader support is required. Explore our <a href="/services/branding">branding services</a> to create stronger consistency between campaign messaging and brand presentation.</>],
  ["Clear Measurement", "Campaign activity is connected with defined business actions wherever accurate tracking is technically possible."],
  ["Ongoing Optimisation", "Campaigns are reviewed using available performance data, audience response and conversion behaviour."],
  ["Practical Reporting", "Reports focus on results, completed changes and recommended next actions rather than vanity metrics alone."],
];

function Checklist({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, intro, children, tinted = false }) { return <section className={`wd-section dm-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro && <p>{intro}</p>}</div>{children}</section>; }
function Card({ item }) { const [title, body] = item; return <article className="wd-card"><BarChart3 className="wd-card-icon" aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>; }
function Cards({ items, className = "wd-card-grid" }) { return <div className={className}>{items.map((item) => <Card item={item} key={item[0]} />)}</div>; }
function ServiceCard({ service }) { return <article className="wd-card"><BarChart3 className="wd-card-icon" aria-hidden="true" /><h3>{service.title}</h3>{service.paragraphs.map((p) => <p key={p}>{p}</p>)}<Checklist items={service.items} />{service.closing.map((p) => <p key={p}>{p}</p>)}{service.title === "Content Marketing" && <p>For businesses seeking long-term organic search visibility, Vorevix also provides <a href="/services/seo-services">dedicated SEO services</a>.</p>}</article>; }

export default function DigitalMarketingPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page digital-marketing-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Digital Marketing</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><h1>Digital Marketing Services Built Around Clear Business Goals</h1><p>Reach the right audience with digital marketing services planned around your goals, customer journey and measurable outcomes. Vorevix connects strategy, paid media, social media, content, email and performance tracking through one coordinated approach.</p><p>We do not recommend channels simply because they are popular. We first understand what your business needs to achieve, who you need to reach and how meaningful actions will be measured.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Marketing Goals <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">View Our Work</a></div><ul className="dm-trust"><li>Strategy before channel selection</li><li>Clear campaign tracking</li><li>Flexible multi-channel support</li><li>Actionable performance reporting</li></ul></div><div className="wd-hero-visual"><img src="/service-social.png" alt="Digital marketing services strategy by Vorevix" width="1182" height="1330" fetchPriority="high" /></div></section>

    <Section title="Digital Marketing Works Better When Every Channel Has a Purpose"><div className="dm-prose"><p>Businesses often invest in advertising, social media, content and email without having a clear plan connecting each activity to a commercial objective.</p><p>This can result in disconnected campaigns, unclear reporting, wasted budget and difficulty identifying which channels contribute to enquiries, sales or customer growth.</p><p>Vorevix provides digital marketing services that connect strategy, campaign execution and measurement. Every channel is selected for a reason, every campaign is linked to a defined goal and every report is designed to support the next decision.</p><p>Whether the objective is to build awareness, generate qualified leads, increase ecommerce sales or improve campaign efficiency, we create a focused marketing approach around your business priorities.</p><p>The result is a clearer system in which campaigns, content, landing pages, audience targeting and reporting work together instead of operating as isolated activities.</p></div></Section>
    <Section title="Digital Marketing Services We Provide" intro="Our digital marketing services can support a single campaign or coordinate activity across multiple customer touchpoints. The right service mix depends on your audience, objectives, available budget, existing assets and measurement requirements."><p className="dm-note">We focus on channels that have a clear role in the customer journey rather than placing every business into the same marketing package.</p><div className="wd-card-grid">{services.map((service) => <ServiceCard service={service} key={service.title} />)}</div></Section>

    <Section title="Performance Marketing Focused on Measurable Actions" tinted><div className="dm-prose"><p>Performance marketing is not limited to launching advertisements. It requires a clear offer, accurate targeting, suitable landing pages, reliable conversion tracking and regular optimisation.</p><p>Our digital marketing services combine campaign planning, audience targeting, suitable landing pages, conversion tracking and ongoing optimisation so every campaign element supports a measurable action.</p><p>A performance-focused approach may combine:</p><Checklist items={["Paid search", "Paid social", "Remarketing", "Lead-generation campaigns", "Landing-page recommendations", "Audience testing", "Creative testing", "Budget adjustments", "Conversion analysis", "Campaign reporting"]} /><p>A performance marketing agency should be able to explain what is being measured, why it matters and how campaign data influences the next decision.</p><p>We prioritise meaningful actions rather than relying only on impressions, reach or clicks. Awareness metrics can still be useful, but they must be interpreted according to the objective of the campaign.</p><p>Campaign performance may be evaluated using qualified enquiries, purchases, sign-ups, bookings, cost per lead, cost per acquisition, conversion rate or return on advertising spend.</p></div></Section>
    <Section title="How We Build a Digital Marketing Strategy" intro="An effective strategy connects business goals, audience behaviour, channel selection, campaign assets and performance measurement."><p className="dm-note">These digital marketing services create a structured connection between business objectives, customer behaviour and campaign execution.</p><Cards items={process} className="wd-process-grid" /></Section>
    <Section title="Choosing the Right Digital Marketing Channels" intro="The right channel depends on how customers discover, compare and choose a product or service." tinted><div className="dm-prose"><p>Our digital marketing services may use one channel or connect several channels across the customer journey.</p><p>The purpose of our digital marketing services is not to use every available platform, but to select channels that have a clear role in reaching and converting the right audience.</p></div><Cards items={channels} /></Section>

    <Section title="Campaigns Need More Than Traffic"><div className="dm-prose"><p>A campaign may bring visitors to a website, but the landing experience often determines whether those visitors take action.</p><p>Campaign performance can be affected by:</p><Checklist items={["Landing-page relevance", "Message clarity", "Page speed", "Mobile usability", "Call-to-action placement", "Trust signals", "Form length", "Navigation distractions", "Conversion tracking", "Follow-up process"]} /><p>The advertisement, landing page and conversion action should feel like parts of the same customer journey.</p><p>Where required, our digital marketing services can be connected with <a href="/services/web-design">web design services</a>, <a href="/services/ui-ux-design-services">UI/UX design services</a> and <a href="/services/web-development-services">web development services</a>.</p><p>This creates stronger alignment between campaign messaging, website experience and the final action you want visitors to complete.</p></div></Section>
    <Section title="Tracking and Reporting That Support Better Decisions" tinted><div className="dm-prose"><p>Reliable reporting begins with reliable tracking.</p><p>Depending on the campaign and technical environment, measurement may include:</p><Checklist items={["Analytics configuration", "Campaign conversion tracking", "Form-submission tracking", "Enquiry tracking", "Ecommerce events", "Telephone-click tracking", "Key website actions", "UTM campaign structure", "Advertising platform tracking", "Channel comparisons", "Conversion-rate analysis", "Cost-per-result analysis"]} /><p>Official <a href="https://support.google.com/google-ads/answer/1722054" target="_blank" rel="noopener noreferrer">Google Ads conversion tracking documentation</a> explains how actions such as purchases, sign-ups or enquiries can be measured after an advertisement interaction.</p><p>Reports may include:</p><Checklist items={["Campaign spend", "Reach and impressions", "Clicks and engagement", "Leads or conversions", "Cost per result", "Conversion rate", "Audience performance", "Completed optimisations", "Campaign changes", "Recommended next actions"]} /><p>Our digital marketing services focus on reporting that supports decisions instead of presenting large amounts of disconnected information.</p><p>Reports should help answer what happened, why it may have happened and what action should be taken next.</p></div></Section>

    <Section title="What Your Digital Marketing Engagement May Include"><div className="dm-prose"><p>The final scope depends on your objectives, selected channels, current resources and technical requirements.</p><p>A digital marketing services engagement may include:</p><Checklist items={["Digital marketing audit", "Audience research", "Market and competitor review", "Campaign strategy", "Channel plan", "KPI framework", "Paid campaign setup", "Audience configuration", "Campaign copy", "Creative direction", "Landing-page recommendations", "Lead-form planning", "Conversion tracking", "Campaign optimisation", "Performance reporting", "Strategic recommendations"]} /><p>The agreed deliverables are defined before work begins.</p><p>Some businesses may only require strategy and campaign planning, while others may need ongoing management across multiple channels.</p></div></Section>
    <Section title="Flexible Digital Marketing Support" tinted><Cards items={support} /></Section>
    <Section title="Digital Marketing Support for Different Business Models" intro="Our approach can be adapted according to the business model, buying journey and type of conversion being targeted."><p className="dm-note">Our digital marketing services are adapted according to the business model, target market, customer journey and type of conversion being pursued.</p><Cards items={businessModels} /></Section>
    <Section title="Why Businesses Choose Vorevix for Digital Marketing" tinted><Cards items={why} /><div className="dm-prose"><p>Our digital marketing services are structured to help businesses understand what is being done, how performance is measured and what should happen next.</p><p>Learn more <a href="/about">about Vorevix</a> and how we approach digital projects.</p></div></Section>

    <Section title="Selected Digital Work"><div className="dm-prose"><p>Explore selected branding, design, development and digital projects completed by Vorevix.</p><p>Each project reflects a different business challenge, audience and delivery requirement.</p><p>Our portfolio shows how strategy, design, development and digital marketing services can support different business challenges and customer journeys.</p><p>Only verified project information and outcomes should be published. Traffic, lead, revenue and conversion figures should not be used unless they can be accurately supported.</p><a className="wd-text-link" href="/portfolio">View Our Portfolio <ArrowRight size={18} aria-hidden="true" /></a></div></Section>
    <Section title="How Digital Marketing Pricing Is Determined" tinted><div className="dm-prose"><p>Pricing depends on the scope and level of support required.</p><p>Important factors include:</p><Checklist items={["Number of marketing channels", "Campaign complexity", "Audience and market research", "Advertising platforms", "Advertising budget", "Creative requirements", "Landing-page requirements", "Content production", "Email requirements", "Conversion tracking", "Reporting frequency", "Campaign duration", "Optimisation frequency"]} /><p>Advertising spend is normally separate from Vorevix strategy, setup and management fees unless the project proposal states otherwise.</p><p>The cost of digital marketing services should be based on the actual work required rather than a generic package containing irrelevant channels.</p><p>Every digital marketing services proposal defines the selected channels, deliverables, management requirements and reporting schedule before work begins.</p><a className="wd-text-link" href="/contact">Request a Project Estimate <ArrowRight size={18} aria-hidden="true" /></a></div></Section>

    <Section title="Digital Marketing Services FAQs"><div className="dm-faq-list">{digitalMarketingFaqs.map((faq, index) => { const open = openFaq === index; const id = `dm-faq-${index}`; return <article className="dm-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{faq.question}<ChevronDown aria-hidden="true" /></button></h3><div id={id} hidden={!open}>{faq.answer.map((p, paragraphIndex) => <p key={p}>{faq.question === "Can you help with landing pages and conversion tracking?" && paragraphIndex === 1 ? <>Where needed, this can be connected with our <a href="/services/web-design">web design</a>, <a href="/services/ui-ux-design-services">UI/UX design</a> and <a href="/services/web-development-services">web development services</a>.</> : faq.question === "Is SEO included in digital marketing services?" && paragraphIndex === 1 ? <>Vorevix provides SEO through a separate <a href="/services/seo-services">SEO services</a> scope to avoid mixing long-term organic growth with short-term campaign management.</> : p}</p>)}</div></article>; })}</div></Section>
    <section className="wd-final-cta"><h2>Plan Your Next Digital Marketing Campaign with Clear Goals</h2><p>Tell us what you want to achieve, who you need to reach and where your current marketing is falling short.</p><p>Vorevix will help define a practical strategy, suitable channels, campaign requirements and measurable next steps.</p><p>Start with digital marketing services planned around your audience, commercial priorities and measurable campaign goals.</p><p>Our digital marketing services can support a focused campaign or a coordinated, ongoing marketing programme based on your business priorities.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Marketing Goals <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">Explore Our Work</a></div></section>
  </main>;
}
