import { useState } from "react";
import { ArrowRight, ChevronDown, Search } from "lucide-react";
import { seoAustraliaFaqs } from "../seoAustraliaFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";

const problems = [["Poor Keyword Targeting", "A page may target a keyword with high search volume but weak relevance to the service, audience or buying stage. Useful research considers intent, commercial relevance, competition, authority, page type, customer questions, geographic context and conversion potential."], ["Technical Crawl and Indexing Issues", "Blocked pages, incorrect canonicals, broken redirects, duplicate URLs, outdated sitemaps, orphan pages, rendering issues, redirect chains, broken links, accidental noindex tags and mobile problems can limit discovery and indexing."], ["Weak Page Structure", "Generic headings, poor section order, weak service descriptions, missing internal links, unclear calls to action, long text blocks and competing pages can make useful information difficult to understand."], ["Content Gaps", "Competitors may answer questions, explain services or cover buying stages that the website ignores. The right response may be a stronger service page, comparison section or dedicated supporting page."], ["Low Website Authority", "Authority can be supported through relevant backlinks, industry mentions, useful original resources, consistent information, verified case studies, expert contributions, digital PR and strong internal topic coverage."], ["Local Search Weakness", "Unclear location relevance, inconsistent information, incomplete business profiles, duplicated location pages and weak local linking can restrict genuine regional visibility."], ["Traffic Without Conversion", "Traffic may not produce value when search intent, the offer, trust, mobile usability, information or calls to action are poorly aligned."], ["Unclear Reporting", "Reporting should explain completed work, changes, page performance, traffic sources, visitor actions, remaining issues and the next priorities—not only keyword movement."]];

const services = [
  { title: "SEO Strategy and Keyword Research", items: ["Commercial keywords", "Service-related searches", "Customer questions", "Competitor terms", "Local keywords", "Product and category searches", "Search-intent analysis", "Keyword clustering", "Page mapping", "Cannibalisation checks", "Content opportunities"], body: "A clear strategy identifies where the website stands and which opportunities deserve attention first. Search volume alone does not determine business value." },
  { title: "Technical SEO", items: ["Crawl analysis", "Indexation review", "Robots.txt checks", "XML sitemap review", "Canonical implementation", "Redirect mapping", "Broken-link checks", "Duplicate-content analysis", "Core Web Vitals considerations", "Mobile usability", "Structured data", "JavaScript rendering", "URL consistency", "Server-response issues"], body: "Technical SEO reviews how search engines access and interpret the website, with recommendations prioritised by likely impact." },
  { title: "On-Page SEO", items: ["SEO titles", "Meta descriptions", "H1 and subheading structure", "Page introductions", "Service descriptions", "Internal links", "Image alternative text", "URL structure", "Content hierarchy", "Calls to action", "Supporting FAQs", "Search-intent alignment", "Duplicate-page reduction"], body: "On-page optimisation should preserve readability and make each page’s purpose and relevance clearer." },
  { title: "Content Strategy and Optimisation", items: ["Improving service pages", "Creating landing pages", "Updating outdated information", "Building topic clusters", "Creating briefs", "Resolving keyword overlap", "Adding FAQs", "Comparison content", "Content hierarchy", "Buying-stage information", "Blog and resource planning"], body: "New content should have a defined audience and purpose rather than increasing page count without strategy." },
  { title: "Local SEO", items: ["Local keyword research", "Google Business Profile guidance", "Business-information consistency", "Location-page planning", "Service-area content", "Local landing pages", "Citation review", "Review-strategy guidance", "Local internal linking", "Map-pack visibility analysis", "Duplicate-location control"], body: "Local SEO should represent areas genuinely served without false offices or misleading location claims." },
  { title: "Ecommerce SEO", items: ["Category optimisation", "Product-page optimisation", "Faceted navigation", "Filter and parameter handling", "Duplicate products", "Product structured data", "Internal linking", "Out-of-stock handling", "Category content", "Migration planning", "Image optimisation", "Mobile shopping usability"], body: "The goal is to improve discovery of useful categories and products while controlling unnecessary URLs." },
  { title: "Link Building and Digital Authority", items: ["Industry resources", "Useful guides", "Partner mentions", "Supplier relationships", "Digital PR", "Relevant directories", "Expert commentary", "Resource outreach", "Local citations", "Broken-link opportunities"], body: "Quality and relevance matter more than raw link quantity; authority should be built through credible signals." },
  { title: "SEO Audits", items: ["Technical review", "Content assessment", "Keyword analysis", "Internal linking", "Competitor comparison", "Authority review", "Prioritised roadmap"], body: "An audit should explain what is limiting performance, why it matters and what should be addressed first." },
  { title: "Website Migration SEO", items: ["URL inventory", "Redirect mapping", "Canonical checks", "Metadata migration", "Content preservation", "Internal-link updates", "Sitemap review", "Launch checks", "Post-launch monitoring"], body: "Migration planning helps reduce avoidable disruption when platforms, domains, URLs or website structures change." },
  { title: "SEO Reporting and Ongoing Optimisation", items: ["Visibility", "Landing pages", "Organic traffic", "Leads or sales where tracked", "Technical health", "Content performance", "Completed work", "Next priorities"], body: "Reporting connects performance data with completed activity and practical next decisions." },
  { title: "AI Search and Search Visibility", items: ["Clear topic structure", "Useful answers", "Entity information", "Source credibility", "Technical accessibility", "Content relationships"], body: "AI search adds new discovery formats, but it does not replace the need for technically accessible, trustworthy and useful content." },
  { title: "Small Business SEO", items: ["Priority services", "Local relevance", "Focused content", "Technical essentials", "Practical reporting"], body: "A focused scope can help smaller businesses concentrate resources on the pages and searches most connected to real customer needs." },
];

const foundations = [["Technical Quality", "Search engines need to access, crawl, render and index the website through clear technical signals."], ["Relevant Content", "Pages should match customer language, search intent and the information needed to evaluate a service or product."], ["Authority and Trust", "Relevant mentions, links, accurate business information and useful expertise can support credibility over time."]];
const process = [["1. Discovery and Goal Setting", "Understand the business, audience, priorities, markets, website history and success measures."], ["2. Website and Competitor Audit", "Review technical health, content, authority, competitors, internal linking and current performance."], ["3. Keyword and Search-Intent Research", "Map commercially relevant searches and questions to appropriate pages and buying stages."], ["4. SEO Strategy and Roadmap", "Prioritise work according to impact, dependencies, resources, competition and practical implementation."], ["5. Technical and On-Page Implementation", "Address agreed technical issues and improve metadata, structure, content relevance and internal links."], ["6. Content Development and Optimisation", "Strengthen existing pages and plan useful supporting content around defined gaps and intent."], ["7. Authority and Local Signals", "Develop credible authority opportunities and accurate regional signals where relevant."], ["8. Reporting and Ongoing Improvement", "Review evidence, completed work and changing priorities to guide the next actions."]];
const models = [["Small Businesses", "Focus limited resources on priority services, technical essentials and relevant local or commercial searches."], ["Professional Services", "Support expertise-led service pages, useful resources, trust and qualified enquiry journeys."], ["Ecommerce Stores", "Improve category and product discovery while controlling duplication, filters and indexation."], ["B2B Companies", "Support complex services, longer buying journeys, topic authority and qualified lead generation."], ["SaaS Businesses", "Connect solution, feature, integration, comparison and educational pages across the customer journey."], ["Multi-Location Businesses", "Create scalable, useful regional structures without duplicated or misleading location content."], ["Startups", "Build clean foundations and prioritise realistic opportunities while the website and market positioning evolve."], ["Established Businesses", "Audit legacy content, technical debt, authority and overlapping pages before expanding organic activity."]];
const platforms = [["WordPress", "Review themes, plugins, crawling, templates, performance, metadata and content-management patterns."], ["Shopify", "Address collections, products, filters, duplicate URLs, structured data, navigation and store content."], ["WooCommerce", "Review WordPress and commerce-specific technical, category, product and performance requirements."], ["React and JavaScript Websites", "Assess rendering, crawlability, routing, metadata, internal links, performance and indexable content."]];
const why = [["Strategy Before Activity", "We begin with the website, market and goals instead of applying the same checklist to every campaign."], ["Technical, Content and Authority Coverage", "SEO recommendations consider all three foundations rather than focusing only on metadata or backlinks."], ["Business-Relevant Keyword Targeting", "We prioritise searches connected to real services, products and customer needs."], ["Clear Reporting", "Reports explain completed work, performance changes and recommended next actions."], ["Connected Web and SEO Capability", <>SEO can connect with <a href="/services/web-development-services">web development services</a>, <a href="/services/web-design">web design services</a>, <a href="/services/ui-ux-design-services">UI/UX design services</a> and <a href="/services/digital-marketing">digital marketing services</a>. Australia-specific support is available through <a href="/services/web-development-australia">Web Development Australia</a> and <a href="/services/web-design-australia">Web Design Australia</a>.</>], ["Content and Conversion Awareness", "SEO pages should help visitors understand the offer and choose a suitable next step."], ["Honest Expectations", "We do not guarantee rankings or present uncertain forecasts as definite outcomes."], ["Ongoing Improvement", "SEO priorities are reviewed as the website, market and search environment change."]];

function List({items}){return <ul className="wd-checklist">{items.map(x=><li key={x}>{x}</li>)}</ul>}
function Section({title,intro,children,tinted=false}){return <section className={`wd-section wda-section${tinted?" wd-tinted":""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro&&<p>{intro}</p>}</div>{children}</section>}
function Cards({items}){return <div className="wd-card-grid">{items.map(([title,body])=><article className="wd-card" key={title}><Search className="wd-card-icon" aria-hidden="true"/><h3>{title}</h3><p>{body}</p></article>)}</div>}

export default function SeoAustraliaPage(){const[openFaq,setOpenFaq]=useState(0);return <main className="web-development-page wda-page">
  <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">SEO Services Australia</span></li></ol></nav>
  <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">SEO Services Australia</span><h1>SEO Services for Businesses in Australia</h1><p>Vorevix provides SEO services Australia businesses can use to improve search visibility, strengthen website quality and attract more relevant organic traffic.</p><p>Our work covers technical SEO, keyword research, on-page optimisation, content strategy, local search, ecommerce SEO, website authority, reporting and ongoing improvements.</p><p>We do not approach SEO as a collection of disconnected tasks. Each recommendation is based on the condition of your website, the market you compete in, the searches your customers make and the commercial goals the campaign needs to support.</p><p>Vorevix works remotely with businesses across Australia through structured audits, clear priorities, shared documentation and regular performance reviews.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your SEO Goals <ArrowRight size={18}/></a><a href="/services/seo-services">Explore Our SEO Services</a></div><ul className="wda-trust"><li>Strategy based on business and search intent</li><li>Technical, content and authority coverage</li><li>Clear priorities and measurable reporting</li><li>No unsupported ranking guarantees</li></ul></div><div className="wd-hero-visual"><img src="/service-seo.png" alt="SEO services for businesses in Australia by Vorevix" width="1183" height="1330" fetchPriority="high"/></div></section>
  <Section title="SEO for Australian Businesses That Need Sustainable Visibility"><div className="wda-prose"><p>Search visibility is useful only when it connects the right audience with the right pages.</p><p>A website can rank for several keywords and still produce little business value if those searches are irrelevant, the landing pages are unclear or the user journey does not support an enquiry or purchase.</p><p>Common SEO challenges include:</p><List items={["Important pages not appearing in search","Traffic coming from irrelevant keywords","Rankings declining after a website change","Technical issues limiting crawling or indexing","Service pages lacking depth","Poor internal linking","Several pages competing for the same keyword","Weak local search visibility","Ecommerce categories not being indexed correctly","Content attracting visits without enquiries","SEO reports that show rankings without explaining outcomes","Previous SEO activity producing no clear progress"]}/><p>Our SEO services Australia approach begins by identifying what is limiting the website and which opportunities are most relevant to the business.</p><p>The aim is not to chase every available keyword. It is to create a focused search strategy that improves the website’s technical foundations, content relevance and authority over time.</p><p>For broader location-neutral support, explore our <a href="/services/seo-services">general SEO services</a>.</p></div></Section>
  <Section title="Common SEO Problems That Limit Organic Growth" tinted><Cards items={problems}/></Section>
  <Section title="What Professional SEO Should Support"><Cards items={[["Better Discoverability","Important pages should be easy for search engines to find and understand."],["Stronger Relevance","Content should match the topics, language and intent behind customer searches."],["Technical Stability","URLs, canonicals, redirects, sitemaps, metadata and structured content should provide clear signals."],["More Useful Content","Pages should answer real questions and help users evaluate the business."],["Local Visibility","Businesses serving locations should communicate geographic relevance accurately."],["Qualified Organic Traffic","Campaigns should focus on visitors more likely to need the offer."],["Measurable Progress","Performance should be reviewed through suitable indicators rather than rankings alone."]]}/><p className="wda-note">No ethical SEO provider can control Google or guarantee a specific first-page position.</p></Section>
  <Section title="SEO Services for Australian Businesses" intro="Vorevix provides a connected range of services covering technical quality, content relevance, local visibility and website authority." tinted><div className="wd-card-grid">{services.map(s=><article className="wd-card" key={s.title}><Search className="wd-card-icon" aria-hidden="true"/><h3>{s.title}</h3><p>{s.body}</p><List items={s.items}/></article>)}</div></Section>
  <Section title="The Three Foundations of Sustainable SEO"><Cards items={foundations}/></Section>
  <Section title="Our SEO Process" tinted><Cards items={process}/></Section>
  <Section title="SEO Services for Different Australian Business Models"><Cards items={models}/></Section>
  <Section title="SEO Support Across Different Platforms" tinted><Cards items={platforms}/></Section>
  <Section title="Local SEO for Businesses Serving Australian Markets"><div className="wda-prose"><p>Local search should accurately connect services with the markets a business genuinely serves.</p><p>Strategy may include local research, business-information consistency, useful location pages, profile guidance, citations and internal links without creating false offices.</p></div></Section>
  <Section title="SEO Reporting That Explains What Is Changing" tinted><div className="wda-prose"><p>Reporting should explain work completed, important changes, page performance, traffic quality, tracked actions, remaining issues and the next priorities.</p><p>Metrics are selected according to business goals rather than using one generic report for every campaign.</p></div></Section>
  <Section title="How Long Does SEO Take?"><div className="wda-prose"><p>SEO timelines depend on website condition, competition, content, authority, technical implementation and market change.</p><p>Some corrections can be implemented quickly, while sustainable growth generally requires consistent work and review over time.</p></div></Section>
  <Section title="How SEO Services Pricing Is Determined" tinted><div className="wda-prose"><p>SEO pricing depends on website size, competition, technical condition, target services and locations, content requirements, implementation support and reporting scope.</p><p>Vorevix prepares a tailored proposal after reviewing the website and agreed priorities.</p></div></Section>
  <Section title="Clear Scope, Priorities and Expectations"><div className="wda-prose"><p>A clear engagement defines deliverables, responsibilities, implementation dependencies, reporting and review stages before work begins.</p><p>Our approach is informed by established guidance including the <a href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide" target="_blank" rel="noopener noreferrer">Google SEO Starter Guide</a>.</p></div></Section>
  <Section title="SEO Support Across Australia" tinted><div className="wda-prose"><p>Vorevix works remotely with businesses across Australia through online meetings, shared documentation, prioritised roadmaps and regular reporting.</p><p>This supports clear delivery without claiming an Australian office or physical presence.</p></div></Section>
  <Section title="Why Choose Vorevix for SEO Services in Australia"><Cards items={why}/><p className="wda-note">Learn more <a href="/about">about Vorevix</a>.</p></Section>
  <Section title="Selected SEO and Website Work" tinted><div className="wda-prose"><p>Explore selected Vorevix projects across SEO, website strategy, design and development.</p><p>Published examples should use verified information about the challenge, scope, completed work, timeline, outcomes and limitations.</p><a className="wd-text-link" href="/portfolio">View Our Portfolio <ArrowRight size={18}/></a></div></Section>
  <Section title="SEO Services Australia FAQs"><div className="wda-faq-list">{seoAustraliaFaqs.map((faq,i)=>{const open=openFaq===i,id=`seo-au-faq-${i}`;return <article className="wda-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={()=>setOpenFaq(open?-1:i)}>{faq.question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}>{faq.answer.map(p=><p key={p}>{p}</p>)}</div></article>})}</div></Section>
  <section className="wd-final-cta"><h2>Plan Your SEO Strategy in Australia</h2><p>Tell us what you want to improve, where your website is underperforming and which services or markets matter most.</p><p>Vorevix will review the website, current search visibility, competitors, technical condition and content before recommending a practical strategy.</p><p>Whether you need an audit, local visibility, ecommerce optimisation, technical improvements or ongoing support, our SEO services Australia approach can be structured around your priorities and available resources.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your SEO Goals <ArrowRight size={18}/></a><a href="/services/seo-services">Explore Our SEO Services</a></div></section>
</main>}
