import { useState } from "react";
import { ArrowRight, ChevronDown } from "lucide-react";
import { seoNewZealandFaqs } from "../seoNewZealandFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./SeoServicesPage.css";

const scope = ["technical and content discovery", "keyword and competitor research", "search-intent analysis", "site architecture review", "crawlability and indexation checks", "metadata and heading optimisation", "content planning", "internal linking", "local SEO guidance", "eCommerce SEO", "reporting and ongoing review"];
const technical = ["crawlability", "indexation", "robots directives", "XML sitemaps", "canonical tags", "redirect chains", "broken links", "duplicate pages", "URL structure", "mobile rendering", "page-speed priorities", "Core Web Vitals", "structured-data opportunities", "migration requirements"];
const onPage = ["title tags", "meta descriptions", "H1 and supporting headings", "introductory copy", "content depth", "image context", "internal links", "anchor text", "calls to action", "content duplication", "page relationships"];
const content = ["missing service pages", "weak category content", "supporting guides", "comparison topics", "FAQ opportunities", "outdated pages", "overlapping pages", "internal-linking gaps", "content consolidation opportunities"];
const local = ["local-intent keyword research", "location-page review", "Google Business Profile recommendations", "name, address and phone consistency", "local landing-page guidance", "review of local citations", "local content opportunities"];
const collaboration = ["video meetings", "shared audit documents", "prioritised recommendations", "recorded walkthroughs", "content reviews", "development handoffs", "monthly reports", "collaboration during suitable New Zealand business hours"];
const costs = ["audit depth", "keyword research", "number of target pages", "technical complexity", "content rewriting", "new content requirements", "local or eCommerce scope", "migration support", "reporting depth", "backlink or digital PR activity", "developer involvement", "campaign duration", "stakeholder availability"];
const process = [["Discovery", "We review the business, website, audiences, objectives, previous SEO activity and implementation constraints."], ["Research and Prioritisation", "We assess search demand, competitors, intent, technical issues and page opportunities."], ["Strategy", "We create a practical roadmap covering technical, on-page, content and authority priorities."], ["Implementation Support", "We optimise agreed elements and coordinate technical recommendations with the relevant development team."], ["Measurement", "We review visibility, traffic, indexation and conversion signals where tracking is available."], ["Ongoing Improvement", "We refine priorities based on performance, implementation progress and changes in search behaviour."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section seo-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="seo-prose">{children}</div></section>; }

export default function SeoNewZealandPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page seo-services-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/seo-services">SEO Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">New Zealand</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">SEO New Zealand</span><h1>SEO Services for New Zealand Businesses</h1><p>For organisations comparing SEO company New Zealand providers, the right partner should offer more than a list of keywords or a promise of quick rankings. Effective search engine optimisation requires technical clarity, useful content, sound site structure, realistic measurement and ongoing improvement.</p><p>Vorevix supports New Zealand startups, SMEs, eCommerce stores, SaaS companies, professional-service firms and established organisations through remote SEO collaboration. Our work can include discovery, keyword research, competitor analysis, search-intent mapping, technical audits, on-page optimisation, content planning, internal linking, local SEO guidance, eCommerce SEO, reporting and monthly optimisation.</p><p>We do not guarantee first-page rankings, fixed traffic growth, leads, sales or return on investment. Search performance depends on competition, website quality, implementation, content, authority, user demand and search-engine changes.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your New Zealand SEO Requirements <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-seo.png" alt="SEO strategy and reporting by Vorevix" width="1183" height="1330" fetchPriority="high"/></div></section>

    <Section title="SEO Built Around Business Priorities"><p>SEO should begin with the business objective, not with a generic checklist.</p><p>A campaign may increase visibility for high-value services, improve category pages, support an eCommerce store, strengthen local discoverability or restore clarity after a redesign.</p><p>An SEO company New Zealand engagement may involve:</p><List items={scope}/><p>The right scope depends on the website, market, available resources and implementation capacity.</p></Section>
    <Section title="Building Organic Visibility in New Zealand" tinted><p>New Zealand businesses may compete nationally, locally or across several regions. Search demand can differ by service, city, industry and buyer intent.</p><p>Strong SEO work should identify what people search for, what page they expect and whether the website provides a useful answer. Visibility is not created by repetition alone. Search engines also assess relevance, technical accessibility, content quality, authority and user experience.</p><p>A professional SEO company New Zealand should explain that rankings are influenced by factors outside an agency's direct control. The goal is to improve the website's ability to compete, not promise a fixed position.</p></Section>
    <Section title="SEO Discovery and Website Review"><p>Discovery helps establish what is working, what limits performance and what the business wants to achieve.</p><p>We may review target services, priority audiences, organic traffic, previous SEO work, website structure, content quality, technical limitations, conversion paths, tracking and approval responsibilities.</p><p>The review helps determine whether the priority is technical correction, content improvement, restructuring, local visibility, eCommerce optimisation or a broader ongoing programme.</p><p>This creates a shared baseline for deciding which technical, content and structural tasks should come first. It also helps identify dependencies that require input from content, design, development or internal stakeholders before recommendations can be implemented and measured consistently over time.</p></Section>
    <Section title="Keyword Research and Search Intent" tinted><p>Keyword research should connect search demand with real business priorities.</p><p>The process may examine service and product terms, informational questions, commercial comparison queries, local searches, category keywords, competitor visibility, likely page type, ranking difficulty and conversion relevance.</p><p>Search intent matters because a service page, guide, category page and product page solve different needs. An SEO company New Zealand strategy should map keywords to the correct page type instead of forcing every phrase onto one landing page.</p></Section>
    <Section title="Technical SEO Priorities"><p>Technical SEO helps search engines access, understand and index website content.</p><p>Work may include reviewing:</p><List items={technical}/><p>Technical recommendations may require developer support. They do not guarantee rankings or Core Web Vitals passes.</p><p>Recommendations involving templates, redirects, schema or performance can be implemented through our <a href="/new-zealand/web-development">web development services for New Zealand businesses</a>.</p></Section>
    <Section title="On-Page SEO and Content Structure" tinted><p>On-page optimisation aligns each page with a clear topic and search intent.</p><p>This may include:</p><List items={onPage}/><p>The aim is not to insert the same keyword repeatedly. A strong page should explain the subject clearly, answer relevant questions and guide users towards a useful next step.</p></Section>
    <Section title="Content Planning and Optimisation"><p>Content can support visibility when it addresses genuine audience questions and business priorities.</p><p>Vorevix may help identify:</p><List items={content}/><p>An SEO company New Zealand campaign may improve existing content before recommending new production. More pages are not automatically better when they duplicate intent or add little value.</p></Section>
    <Section title="Local SEO for Eligible Businesses" tinted><p>Local SEO may support businesses serving customers from real locations or defined service areas.</p><p>Work may include:</p><List items={local}/><p>Local SEO cannot guarantee map-pack placement. Eligibility, proximity, relevance, competition and profile quality affect visibility.</p><p>Vorevix does not claim a New Zealand office, local team or listings-management capability.</p></Section>
    <Section title="eCommerce SEO"><p>eCommerce SEO may involve category pages, product pages, filters, internal linking, product feeds and technical controls.</p><p>Important areas can include category hierarchy, faceted navigation, duplicate URLs, product metadata, collection content, discontinued products, pagination, product schema, crawl budget and mobile performance.</p><p>A broad SEO company New Zealand page should cover eCommerce practically. Large catalogues, Shopify stores and complex platforms may require a separate technical scope.</p></Section>
    <Section title="Reporting and Ongoing Optimisation" tinted><p>SEO reporting should connect completed work with meaningful performance indicators.</p><p>Reports may include organic visibility, keyword movement, landing-page traffic, clicks, impressions, indexation changes, technical issues, content performance, conversion activity where tracking allows, completed actions and next priorities.</p><p>Reporting improves visibility but does not provide perfect attribution. For SEO company New Zealand projects, reviews can be coordinated during suitable New Zealand business hours.</p><p>Ongoing optimisation may include updating priority pages, reviewing queries, monitoring technical issues, improving internal links and refining content using available evidence.</p></Section>
    <Section title="Remote Collaboration Across New Zealand"><p>Vorevix works remotely with organisations across New Zealand.</p><p>An SEO company New Zealand engagement may include:</p><List items={collaboration}/><p>National availability does not imply a New Zealand office, New Zealand-based team, local clients or local awards unless independently verified.</p></Section>
    <Section title="SEO Cost Factors in New Zealand" tinted><p>SEO cost depends on website size, technical condition, competition, content needs and implementation requirements.</p><p>Common cost factors include:</p><List items={costs}/><p>An SEO company New Zealand proposal should clarify what is included, what requires client or developer action and whether third-party tools or content production are separate.</p><p>Vorevix does not publish invented NZD prices, fixed ranking timelines or guaranteed backlink quantities without reviewing the project.</p></Section>
    <section className="wd-section seo-section"><div className="wd-section-heading"><h2>Our New Zealand SEO Process</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="wd-section seo-section wd-tinted"><div className="wd-section-heading"><h2>Why Work With Vorevix?</h2><p>Our SEO company New Zealand approach combines technical review, keyword research, on-page optimisation, content planning, internal linking, reporting and ongoing support without guaranteed ranking or revenue claims.</p></div><div className="seo-prose"><p>Businesses may work with Vorevix for discovery, keyword research, competitor analysis, technical audits, on-page optimisation, content planning, local SEO guidance, eCommerce SEO, migration support, reporting and monthly optimisation.</p><p>Websites requiring new layouts can connect with our <a href="/new-zealand/web-design">web design services for New Zealand businesses</a>.</p><p>Navigation issues requiring user research can use our <a href="/new-zealand/ui-ux-design">UI/UX design services for New Zealand businesses</a>.</p><p>Brand messaging can align with search demand through our <a href="/new-zealand/branding-services">branding services for New Zealand businesses</a>.</p><p>Paid campaigns belong within our <a href="/new-zealand/digital-marketing">digital marketing services for New Zealand businesses</a>.</p><p>For the complete global methodology, <a href="/services/seo-services">explore our complete SEO services</a>.</p></div></section>
    <section className="wd-section seo-section wda-section"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="wda-faq-list">{seoNewZealandFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `seo-nz-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan Your New Zealand SEO Project</h2><p>Sustainable SEO requires useful content, sound technical foundations, clear priorities and consistent implementation.</p><p>Vorevix helps New Zealand businesses review search demand, improve website structure, optimise priority pages and measure ongoing organic performance.</p><p>Share your website, target services, current challenges and business priorities. We will review the requirements and recommend the next practical step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your New Zealand SEO Requirements <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
