import { ArrowRight, Search } from "lucide-react";
import { seoServiceFaqs } from "../seoServiceFaqs";
import "./WebDevelopmentPage.css";
import "./SeoServicesPage.css";

const coreServices = [
  {
    title: "Technical SEO",
    paragraphs: [
      "Technical SEO helps search engines access, crawl, interpret, and index your website more effectively.",
      "We review the technical foundations that can influence organic visibility and identify issues that may prevent important pages from being discovered or understood correctly. This can include problems caused by website architecture, redirects, duplicate content, canonical tags, indexation rules, or inconsistent internal linking.",
    ],
    items: ["Crawlability and indexation reviews", "Website architecture analysis", "Sitemap and robots.txt assessment", "Canonical and duplicate-content checks", "Redirect and broken-link reviews", "Structured data recommendations", "Internal linking analysis", "Page experience and Core Web Vitals coordination", "Technical issue prioritisation", "Migration and redevelopment support"],
    closing: <>Technical recommendations are organised by priority and business impact. This gives your development team a clearer path forward and helps prevent low-value technical tasks from distracting from more important opportunities. Our <a href="/services/web-development-services">web development services</a> can support implementation where required.</>,
  },
  {
    title: "On-Page SEO",
    paragraphs: ["On-page SEO improves how individual pages communicate their topic, purpose, and relevance to both users and search engines.", "We review how your pages align with search intent and determine whether their structure, metadata, headings, internal links, and content clearly address the needs of the target audience."],
    items: ["Search intent analysis", "Title tag optimisation", "Meta description recommendations", "Heading structure improvements", "URL review", "Content relevance assessment", "Internal linking improvements", "Image optimisation guidance", "Keyword mapping", "Page-level content recommendations"],
    closing: "Good on-page optimisation should never feel forced. Keywords must support clarity rather than interrupt it. Our approach focuses on naturally matching the language people use when searching with the information they need when they reach the page.",
  },
  {
    title: "SEO Content Strategy",
    paragraphs: ["Search visibility depends on having useful content for the topics, services, and questions that matter to your audience.", "We develop SEO content strategies that connect keyword opportunities with business relevance. This may involve creating new service pages, strengthening existing pages, identifying content gaps, or organising content around clearer topic clusters."],
    items: ["Keyword research", "Competitor content analysis", "Search intent classification", "Keyword-to-page mapping", "Service-page planning", "Content gap analysis", "Content briefs", "Existing content improvement", "Topic and supporting-page planning", "Internal linking recommendations"],
    closing: <><p>The goal is not to publish content simply to increase page count. Each recommended page should have a clear audience, purpose, and role within your wider organic search strategy.</p><p>We also review whether existing pages compete with one another, target unclear topics, or lack the depth required to support a commercial decision.</p></>,
  },
  {
    title: "Local SEO",
    paragraphs: ["Local SEO helps businesses improve visibility when potential customers search for products or services within a specific area.", "For businesses that serve defined cities, regions, or physical locations, local search performance can depend on the quality of location signals across the website and wider search ecosystem."],
    items: ["Local keyword research", "Location-page strategy", "Google Business Profile guidance", "Business information consistency reviews", "Local content recommendations", "Service-area optimisation", "Internal linking between service and location pages", "Local competitor analysis", "Local search visibility reporting"],
    closing: <><p>We avoid creating repetitive location pages with minimal value. Each local page should provide useful, relevant information for people in that area and have a clear reason to exist.</p><p>For businesses operating across multiple markets, we can help create a scalable location structure without overloading the main website with unnecessary geographic repetition.</p></>,
  },
  {
    title: "eCommerce SEO",
    paragraphs: ["eCommerce SEO helps online stores improve product and category discovery through organic search.", "Store websites often have complex structures, large product catalogues, filters, duplicated URLs, seasonal inventory, and changing availability. Without a clear SEO strategy, these elements can create crawling issues, dilute page relevance, or make important categories difficult to find."],
    items: ["Category-page optimisation", "Product-page recommendations", "Faceted navigation reviews", "Duplicate URL analysis", "eCommerce keyword research", "Commercial search intent mapping", "Internal linking improvements", "Product and category metadata", "Out-of-stock content guidance", "Technical store audits", "Structured data recommendations", "Content opportunities for commercial journeys"],
    closing: <>We focus on the pages most likely to influence product discovery, category visibility, and commercially relevant traffic. Our <a href="/services/web-development-services">web development services</a> can support store implementation.</>,
  },
  {
    title: "Off-Page SEO and Digital Authority",
    paragraphs: ["Off-page SEO focuses on the external signals that help strengthen a website’s credibility, relevance, and authority.", "Authority should not be treated as a numbers-only exercise. A large volume of irrelevant links does not create the same value as genuine mentions, useful resources, relevant partnerships, and editorial coverage connected to your market."],
    items: ["Backlink profile analysis", "Competitor authority research", "Link-quality evaluation", "Relevant outreach opportunities", "Digital PR alignment", "Brand mention opportunities", "Harmful-link risk identification", "Authority gap analysis"],
    closing: <><p>We prioritise quality, relevance, and long-term value rather than link quantity.</p><p>Any authority-building recommendations are shaped around your industry, content assets, competitive environment, and realistic outreach opportunities.</p></>,
  },
  {
    title: "SEO Audits and Consulting",
    paragraphs: ["An SEO audit provides a structured view of what is working, what is limiting performance, and what should be improved first.", "Our audits combine technical, content, competitive, and strategic analysis. Rather than producing a large list of issues without context, we organise recommendations into a practical roadmap."],
    items: ["Technical website analysis", "Indexation and crawl review", "Keyword and ranking assessment", "On-page optimisation review", "Content gap analysis", "Competitor comparison", "Internal linking analysis", "Authority and backlink review", "Local or eCommerce assessment", "Prioritised recommendations"],
    closing: <><p>Our SEO consulting services are suitable for businesses that already have internal marketing, development, or content teams but need specialist guidance, planning, or independent review.</p><p>Consulting can support:</p><Checklist items={["Website redesigns", "Platform migrations", "International expansion", "Content planning", "Technical implementation", "Internal team training", "Agency or vendor coordination", "Strategy validation"]} /></>,
  },
];

const advanced = [
  { title: "International SEO", paragraphs: ["International SEO helps businesses target audiences across multiple countries, languages, or regions.", "The correct structure depends on how your business operates, how content is localised, and how different markets should be represented."], items: ["International website architecture", "Country and language targeting", "Hreflang recommendations", "Regional keyword research", "International content planning", "Duplicate-content prevention", "Internal linking between regional versions", "Market-level performance analysis"], closing: "The objective is to help search engines understand which content is intended for which audience while creating a clear experience for users across different markets." },
  { title: "Website Migration SEO", paragraphs: ["Website migrations can create significant organic search risk when URLs, content, metadata, or technical settings change without a clear preservation plan.", "We help businesses prepare for and manage SEO requirements during:"], items: ["Website redesigns", "Domain changes", "CMS migrations", "Platform changes", "URL restructuring", "International site consolidation", "eCommerce rebuilds"], after: <>Migration support may include:<Checklist items={["Existing URL inventory", "Redirect mapping", "Metadata transfer planning", "Content preservation", "Internal link updates", "Staging-site reviews", "Launch checks", "Post-launch crawl analysis", "Indexation monitoring", "Visibility tracking"]} /></>, closing: <>Early SEO involvement can reduce avoidable disruption and help design and development teams make informed decisions before launch. Explore our <a href="/services/web-design">web design services</a> and <a href="/services/ui-ux-design-services">UI/UX design services</a>.</> },
  { title: "AI Search Readiness", paragraphs: ["Search experiences continue to evolve as search engines and AI systems present more direct, summarised, and conversational answers.", "AI search readiness does not require replacing established SEO fundamentals. It requires making information clear, trustworthy, well structured, and easy to interpret."], items: ["Improving topic clarity", "Strengthening page structure", "Answering relevant questions directly", "Reducing vague or unsupported content", "Improving entity and service information", "Organising related content more clearly", "Strengthening source credibility", "Improving technical accessibility"], closing: "We do not promise placement in AI-generated answers. Instead, we focus on the content and technical qualities that can help modern search systems understand and evaluate your website more effectively." },
];

const process = [
  ["1. Discovery and Goal Alignment", "We begin by understanding your business, audience, website, services, market, and current challenges.", ["Business objectives", "Target customers", "Priority services or products", "Markets and locations", "Website history", "Previous SEO activity", "Current performance concerns", "Internal resources and implementation capacity"], "These details help ensure the strategy is based on commercial relevance rather than keyword volume alone."],
  ["2. SEO Audit and Research", "We assess the current website and identify opportunities across technical SEO, content, competitors, keywords, and authority.", ["Technical crawling", "Indexation analysis", "Keyword research", "Search intent review", "Competitor analysis", "Content gap analysis", "Internal linking review", "Backlink assessment", "Local or eCommerce analysis"], "The findings establish the current position and clarify the issues most likely to affect performance."],
  ["3. Strategy and Prioritisation", "Not every SEO task has equal value or urgency. We organise recommendations into a prioritised roadmap based on:", ["Potential business impact", "Technical dependencies", "Implementation effort", "Search demand", "Competitive opportunity", "Existing website limitations", "Available internal resources"], "This makes it easier to focus on the work that matters first."],
  ["4. Optimisation and Implementation", "Once priorities are agreed, optimisation begins across the relevant areas.", ["Technical corrections", "Metadata improvements", "On-page optimisation", "Content updates", "New content briefs", "Internal linking", "Local search improvements", "eCommerce optimisation", "Authority development", "Development coordination"], "Implementation responsibilities are defined clearly so your internal team, Vorevix, and any other partners understand the next steps."],
  ["5. Measurement and Continuous Improvement", "SEO requires ongoing review because websites, competitors, search behaviour, and business priorities change. We measure progress, review completed work, and identify the next opportunities.", ["Visibility reviews", "Landing-page performance", "Keyword movement", "Organic traffic quality", "Conversion trends", "Technical monitoring", "Content performance", "Competitor changes", "Roadmap updates"], "The strategy evolves based on evidence rather than assumptions."],
];

const businessModels = [
  ["SEO for Service Businesses", "Service businesses often need to attract qualified leads from people searching for specific expertise, solutions, or local providers.", ["Service-page optimisation", "Commercial keyword targeting", "Local visibility", "Authority-building content", "Lead-generation landing pages", "Location-page strategy", "Trust and proof signals"], "The objective is not simply to increase traffic, but to improve visibility for searches connected to real customer needs."],
  ["SEO for eCommerce Businesses", "eCommerce websites require a strong structure that helps users and search engines discover the right categories and products.", ["Category optimisation", "Product-page improvements", "Faceted navigation control", "Commercial keyword mapping", "Internal linking", "Technical store health", "Product and category content", "Seasonal search planning"], "SEO works alongside user experience and development to create clearer product-discovery journeys."],
  ["SEO for SaaS and Digital Products", "SaaS businesses often need to reach users at different levels of awareness, from broad problem research to detailed product comparison.", ["Solution and use-case pages", "Feature-page optimisation", "Comparison content", "Integration pages", "Educational content", "Industry landing pages", "Product-led search journeys", "Technical documentation visibility"], "This creates opportunities to support discovery, evaluation, and purchase intent across the customer journey."],
];

const why = [
  ["Strategy Before Tactics", "We begin with the business context before recommending SEO activity. This keeps work focused on relevant opportunities rather than isolated tasks."],
  ["Integrated Technical and Content Expertise", "SEO performance often depends on collaboration between strategy, content, design, and development. We consider these areas together rather than treating them as separate disciplines."],
  ["Clear Priorities", "Recommendations are organised according to impact, urgency, and implementation requirements. This helps teams make better decisions and avoid unnecessary work."],
  ["Business-Focused Measurement", "We look beyond rankings and consider how organic search supports meaningful website activity, including relevant traffic, enquiries, conversions, and product discovery."],
  ["Transparent Communication", "You receive clear explanations, realistic recommendations, and practical next steps throughout the engagement."],
  ["Wider Digital Capability", "Our SEO work can connect with website design, development, and user experience where the project requires broader support."],
];

function Checklist({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function ServiceCard({ service }) { return <article className="wd-card"><Search className="wd-card-icon" aria-hidden="true" /><h3>{service.title}</h3>{service.paragraphs.map((p) => <p key={p}>{p}</p>)}<Checklist items={service.items} />{service.after && <div>{service.after}</div>}<div>{service.closing}</div></article>; }
function Section({ title, intro, children, tinted = false }) { return <section className={`wd-section seo-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro && <p>{intro}</p>}</div>{children}</section>; }

export default function SeoServicesPage() {
  return <main className="web-development-page seo-services-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">SEO Services</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><h1>SEO Services for Sustainable Business Growth</h1><p>Build stronger search visibility with a strategy that connects technical performance, relevant content, digital authority, and continuous optimisation.</p><p>Vorevix provides professional SEO services for businesses that want to improve how they are discovered, understood, and evaluated through organic search. We identify the issues limiting performance, prioritise the opportunities that matter, and create a practical roadmap aligned with your wider business goals.</p><p>Our approach goes beyond rankings alone. We focus on building a stronger organic search foundation that can support qualified traffic, leads, product discovery, and long-term growth.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your SEO Goals <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-seo.png" alt="SEO services by Vorevix" width="1183" height="1330" fetchPriority="high" /></div></section>

    <Section title="Build Stronger Search Visibility with a Clear SEO Strategy"><div className="seo-prose"><p>Effective search engine optimisation is not a collection of disconnected tasks. Strong organic performance comes from the way technical structure, content relevance, search intent, user experience, and website authority work together.</p><p>A website may have valuable services and strong design, but still struggle to perform in search if search engines cannot crawl it efficiently, understand its pages, or connect its content with the right audience. In other cases, a website may rank for several terms without attracting the visitors most likely to become customers.</p><p>Our SEO services are built around clarity and prioritisation. We assess your current website, understand your commercial objectives, study your audience and competitors, and develop an organic search strategy based on realistic opportunities.</p><p>Our approach is informed by established search quality and technical guidance, including the principles outlined in <a href="https://developers.google.com/search/docs/essentials" target="_blank" rel="noopener noreferrer">Google Search Essentials</a>.</p><p>The result is a structured approach that helps your business improve visibility without relying on shortcuts, unsupported claims, or isolated optimisation tactics.</p></div></Section>

    <Section title="Our SEO Services" intro="Every business has a different website, market, audience, and level of competition. Our work is therefore shaped around your actual needs rather than a fixed list of generic activities."><p className="seo-section-intro">Depending on your goals, your SEO strategy may include technical improvements, on-page optimisation, content planning, local visibility, eCommerce optimisation, digital authority, auditing, consulting, or a combination of these services.</p><div className="wd-card-grid">{coreServices.map((service) => <ServiceCard key={service.title} service={service} />)}</div></Section>

    <Section title="Advanced SEO Solutions" intro="Some websites require more than standard page optimisation. Larger platforms, international websites, growing SaaS businesses, and websites undergoing major technical changes often need more specialised planning." tinted><div className="wd-card-grid">{advanced.map((service) => <ServiceCard key={service.title} service={service} />)}</div></Section>

    <Section title="Our SEO Process" intro="A clear process keeps SEO focused, measurable, and aligned with business priorities."><div className="wd-process-grid">{process.map(([title, body, items, closing]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p><Checklist items={items} /><p>{closing}</p></article>)}</div></Section>

    <Section title="SEO Reporting Focused on Meaningful Progress"><div className="seo-prose"><p>Clear reporting should explain more than whether individual keywords moved up or down.</p><p>We connect organic performance with the wider goals of your website and business. Depending on the project, reporting may include:</p><Checklist items={["Organic search visibility", "Priority keyword trends", "Qualified organic traffic", "Landing-page performance", "Leads or conversions", "Revenue indicators where tracking allows", "Technical issues", "Completed optimisation work", "Content performance", "Authority development", "Upcoming priorities", "Strategic recommendations"]} /><p>We also explain what changed, why it matters, and what should happen next.</p><p>Reporting frequency and detail depend on the scope of the engagement, but communication remains clear throughout the project. You should understand what work is being completed, what progress is being observed, and where further improvement is possible.</p></div></Section>

    <Section title="SEO for Different Business Models" intro="SEO strategies should reflect how a business attracts, educates, and converts customers." tinted><div className="wd-card-grid">{businessModels.map(([title, body, items, closing]) => <article className="wd-card" key={title}><h3>{title}</h3><p>{body}</p><Checklist items={items} /><p>{closing}</p></article>)}</div></Section>

    <Section title="Why Businesses Choose Vorevix for SEO"><div className="seo-why-grid">{why.map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><div className="seo-prose"><p>We build digital solutions that combine strategy, design, technology, and performance to help businesses grow with confidence.</p><p>Learn more <a href="/about">about Vorevix</a>.</p></div></Section>

    <Section title="SEO Work and Results"><div className="seo-prose"><p>The strongest SEO evidence comes from relevant, verifiable work.</p><p>Our portfolio highlights how we approach digital challenges across strategy, design, development, and performance. Where SEO results are available and verified, case studies can show:</p><Checklist items={["The original business challenge", "The website or search limitations identified", "The strategy developed", "The work implemented", "The measurable outcomes achieved"]} /><p>We do not use unsupported performance claims or present estimates as guaranteed results.</p><a className="wd-text-link" href="/portfolio">Explore Our Portfolio <ArrowRight size={18} aria-hidden="true" /></a></div></Section>

    <Section title="SEO Services Pricing" tinted><div className="seo-prose"><p>SEO pricing depends on the scale, complexity, and requirements of the project.</p><p>A small service website with a clear structure will usually require a different level of work from a large eCommerce platform, an international website, or a business operating in a highly competitive market.</p><p>Pricing may be influenced by:</p><Checklist items={["Website size", "Technical complexity", "Number of services or products", "Market competition", "Target countries or locations", "Current website condition", "Content requirements", "Development support", "Migration requirements", "Reporting and consulting scope", "Internal implementation capacity"]} /><p>Engagements may include an audit, a defined strategy project, ongoing SEO support, consulting, or a combination of these services.</p><p>We provide a clear scope before work begins so you understand what is included, what the priorities are, and how responsibilities will be managed.</p><a className="wd-text-link" href="/contact">Request a Project Estimate <ArrowRight size={18} aria-hidden="true" /></a></div></Section>

    <Section title="Frequently Asked Questions"><div className="seo-faq-grid">{seoServiceFaqs.map((faq) => <article key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></article>)}</div></Section>

    <section className="wd-final-cta"><h2>Build a Stronger Organic Search Foundation</h2><p>A clearer SEO strategy can help your business improve visibility, strengthen important pages, and create a more reliable path from search to meaningful website action.</p><p>Whether you need a complete SEO audit, ongoing optimisation, local search support, eCommerce SEO, content strategy, or consulting, Vorevix can help you identify the right priorities and move forward with confidence.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your SEO Goals <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">Explore Our Portfolio</a></div></section>
  </main>;
}
