import { ArrowRight, Search } from "lucide-react";
import { seoServiceFaqs } from "../seoServiceFaqs";
import "./WebDevelopmentPage.css";
import "./SeoServicesPage.css";

const services = [
  ["SEO Audit and Strategic Roadmap", ["An SEO audit examines the website and identifies issues that may restrict visibility or create poor user experiences. We review crawlability, indexation, architecture, metadata, content quality and internal linking.", "Findings are organised by priority. Each recommendation considers impact, effort and business importance. The roadmap helps internal teams, developers and content specialists understand what should happen first and why."]],
  ["Keyword and Competitor Research", ["Keyword research identifies how potential customers describe their needs and what they expect to find. We assess search demand, difficulty, commercial relevance and intent rather than selecting terms based only on volume.", "Competitor research shows which pages, topics and formats currently perform. It also reveals content gaps and unrealistic assumptions. These insights support page targeting and future content decisions without copying competitors."]],
  ["Technical SEO", ["Technical SEO helps search engines crawl, render, understand and index a website efficiently. Reviews may cover canonical tags, redirects, structured data, page speed, mobile behaviour, duplicate content and architecture.", "Recommendations are adjusted to the platform and development environment. Vorevix can implement approved changes or provide clear requirements to an existing development team and verify completed fixes."]],
  ["On-Page SEO", ["On-page optimisation improves how individual pages communicate their subject, purpose and value. Work may include title tags, meta descriptions, headings, copy structure, image text, internal links and URL recommendations.", "We avoid inserting keywords mechanically. Each page should match a specific search need while remaining natural and useful. Overlapping pages may be consolidated or redirected when several URLs compete for the same topic."]],
  ["Content Optimisation and Planning", ["Content should answer real questions, support business goals and strengthen topic coverage. We assess existing pages for outdated information, weak intent alignment, missing detail and duplication.", "Recommendations may include refreshing service pages, creating supporting resources or combining overlapping content. Where required, Vorevix can produce briefs covering audience, topic, structure, internal links and conversion goals."]],
  ["Off-Page SEO and Authority Building", ["Off-page SEO focuses on signals beyond the website that may support trust and authority. Depending on scope, this can include backlink analysis, link reclamation, digital PR opportunities, relevant citations and outreach planning.", "We do not use automated link schemes, private networks or low-quality directories. Authority building should be selective, relevant and aligned with long-term credibility."]],
];

const process = [
  ["1. Discovery and Goals", "We begin by understanding the business, audience, website, competitors and desired outcomes. Existing analytics, search data and previous work are reviewed where available."],
  ["2. Audit and Research", "The website is assessed for technical, content and structural issues. Keyword and competitor research identifies realistic opportunities and search-intent patterns."],
  ["3. Strategy and Prioritisation", "Findings are converted into a roadmap. Tasks are prioritised by expected value, urgency, dependencies and available resources."],
  ["4. Implementation", "Approved improvements are completed by Vorevix, the client’s team or both. Responsibilities are documented so recommendations do not remain unresolved."],
  ["5. Content Development and Optimisation", "Existing pages are improved and new content is planned where justified by demand and business relevance. Internal linking is updated to support discovery and topical relationships."],
  ["6. Measurement and Continuous Improvement", "Performance is monitored through relevant analytics and search tools. Reports explain completed work, current results, limitations and upcoming priorities. Strategy is adjusted as search behaviour, competitors and the website change."],
];

function List({ items }) { return <ul className="wd-checklist">{items.map(item=><li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted=false }) { return <section className={`wd-section seo-section${tinted?" wd-tinted":""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="seo-prose">{children}</div></section>; }

export default function SeoServicesPage() {
  return <main className="web-development-page seo-services-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">SEO Services</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><h1>Professional SEO Services That Support Sustainable Organic Growth</h1><p>Vorevix provides professional seo services for businesses that want stronger search visibility, better technical foundations and content aligned with genuine search demand. We combine research, implementation and transparent reporting to help websites become easier for search engines to understand and more useful for the people they serve.</p><p>Our approach does not rely on shortcuts, keyword stuffing or guaranteed-ranking claims. Every campaign is shaped around the website, market, competition, resources and business goals. Whether you are improving an established website or preparing a new one for growth, we build a practical roadmap based on evidence and clear priorities.</p><div className="wd-actions"><a className="primary" href="/contact">Start Your SEO Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-seo.png" alt="Professional SEO services for sustainable organic growth" width="1183" height="1330" fetchPriority="high"/></div></section>

    <Section title="Why Businesses Struggle to Grow Through Search"><p>Search visibility can decline because of technical barriers, unclear page targeting, weak internal links, outdated content or limited authority. Some pages rank for the wrong terms, while important commercial pages remain invisible.</p><p>SEO also becomes difficult when strategy and implementation are separated. An audit may identify many issues, but progress remains limited when no one prioritises or fixes them. Our professional seo services connect research with realistic action so teams can focus on improvements that may create the greatest value.</p><p>We assess technical health, search intent, content structure, user experience and authority together. The result is a clear plan rather than a collection of disconnected recommendations.</p></Section>

    <section className="wd-section seo-section"><div className="wd-section-heading"><h2>What Our Professional SEO Services Include</h2><p>Our work can support business websites, service companies, SaaS platforms, online stores and content-led organisations. Scope varies, but a campaign may include auditing, research, optimisation, content planning, implementation support and reporting.</p></div><div className="wd-card-grid">{services.map(([title,paragraphs])=><article className="wd-card" key={title}><Search className="wd-card-icon" aria-hidden="true"/><h3>{title}</h3>{paragraphs.map(p=><p key={p}>{p}</p>)}{title==="Technical SEO"&&<p>Implementation can connect with our <a href="/services/web-development-services">web development services</a>.</p>}{title==="On-Page SEO"&&<p>Page improvements can be coordinated with our <a href="/services/web-design">web design services</a> and <a href="/services/ui-ux-design-services">UI UX design services</a>.</p>}{title==="Content Optimisation and Planning"&&<p>Wider campaigns may also connect with our <a href="/services/branding">branding services</a> and <a href="/services/digital-marketing">digital marketing services</a>.</p>}</article>)}</div></section>

    <Section title="Search Visibility Beyond Traditional Results" tinted><p>People may discover businesses through featured answers, AI-generated summaries and conversational tools as well as traditional search engines.</p><p>Modern visibility still depends on strong foundations: accessible pages, clear entities, accurate information, useful content, structured data and credible references. We improve these foundations as part of our professional seo services, but we do not present AI SEO as a replacement for technical, content and authority work.</p><p>No business can guarantee inclusion in an AI-generated answer. The practical objective is to make information clear, consistent and worthy of reference.</p></Section>

    <Section title="General and Specialist SEO Requirements"><p>The main service covers strategy, technical reviews, on-page optimisation, content planning and measurement. Some businesses require a specialist scope.</p><p>Local SEO may involve Google Business Profile optimisation, citations, reviews and location pages. eCommerce SEO requires attention to category pages, product information, faceted navigation and duplicate content. Enterprise SEO may involve large websites, governance and multiple teams. International SEO can require regional and hreflang planning.</p><p>These capabilities can be introduced within a general campaign, but complex requirements may need separate strategy and deliverables.</p></Section>

    <section className="wd-section seo-section wd-tinted"><div className="wd-section-heading"><h2>Our Professional SEO Services Process</h2></div><div className="wd-process-grid">{process.map(([title,body])=><article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <Section title="What You Receive"><p>Deliverables depend on scope and may include:</p><List items={["Technical and on-page SEO audit","Prioritised implementation roadmap","Keyword research and page mapping","Competitor and search-intent analysis","Metadata and heading recommendations","Internal-linking plan","Content optimisation recommendations","SEO content briefs","Redirect and canonical guidance","Structured-data recommendations","Backlink profile review","Performance reporting","Monthly action plan","Developer-ready implementation notes"]}/><p>Deliverables are defined before work begins so both sides understand what is included.</p></Section>

    <Section title="Reporting That Explains What Matters" tinted><p>SEO reporting should provide more than ranking screenshots. Metrics may include qualified organic traffic, conversions, keyword visibility, indexed pages, technical health, content performance and relevant referring domains.</p><p>Reports document completed actions and future priorities, helping connect performance changes with actual work. Traffic growth alone is not always meaningful; a campaign should attract relevant users and support measurable business actions.</p></Section>

    <Section title="Why Choose Vorevix as Your SEO Agency?"><p>Vorevix connects SEO with content, web design, development and user experience. This allows recommendations to be considered within the wider website rather than treated as isolated keyword changes.</p><p>Businesses choose our professional seo services for:</p><List items={["Research aligned with commercial goals","Clear priorities and realistic roadmaps","Technical and content collaboration","Developer-ready recommendations","Ethical authority-building practices","Transparent reporting","Flexible work with internal teams","Support from discovery through implementation"]}/><p>We do not guarantee rankings, traffic or revenue. Search performance is affected by competition, authority, content, implementation, market demand and search-engine changes.</p></Section>

    <Section title="SEO Pricing and Engagement Factors" tinted><p>SEO cost depends on website size, technical condition, competition, target markets, content requirements and implementation responsibility. A small service website usually requires less work than a large eCommerce or multi-country platform.</p><p>Engagements may begin with an audit or continue through monthly optimisation. Ongoing work should involve analysis, implementation and review—not recurring reports without action. Pricing is confirmed after the website and requirements are assessed.</p></Section>

    <Section title="SEO Timelines and Realistic Expectations"><p>SEO is a long-term channel, but timing varies. Technical corrections may be processed quickly, while competitive commercial terms can require sustained content, authority and website improvements.</p><p>New websites often need time to establish relevance and trust. Professional seo services should support steady improvement through prioritised work, but no honest provider can promise a fixed ranking date.</p></Section>

    <section className="wd-section seo-section"><div className="seo-prose"><p>Vorevix works with businesses worldwide, including organisations seeking <a href="/australia/seo-services">SEO services across Australia</a>, New Zealand and the United Arab Emirates.</p></div></section>

    <section className="wd-section seo-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="seo-faq-grid">{seoServiceFaqs.map(faq=><article key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></article>)}</div></section>

    <section className="wd-final-cta"><h2>Build a Stronger Foundation for Organic Growth</h2><p>Vorevix provides professional seo services for businesses that need clearer strategy, stronger technical foundations and content built around genuine search demand.</p><p>We can review your website, identify practical priorities and recommend a scope that matches your goals, resources and current stage of growth.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your SEO Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></section>
  </main>;
}
