import { useState } from "react";
import { ArrowRight, ChevronDown, Search } from "lucide-react";
import { seoUaeFaqs } from "../seoUaeFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./SeoServicesPage.css";

const scope = ["SEO discovery and strategy", "keyword and competitor research", "technical SEO audits", "crawlability and indexation review", "metadata and heading optimisation", "content planning and optimisation", "internal-link improvements", "local and eCommerce SEO", "backlink audits", "reporting and monthly support"];
const discovery = ["business objectives", "priority services or products", "target audiences", "important locations", "current rankings and traffic", "website structure", "content quality", "previous SEO work", "technical limitations", "internal approval processes"];
const keywordGroups = ["service or product", "commercial priority", "location", "informational need", "buying stage", "page type", "specialist intent"];
const technical = ["crawlability", "indexation", "canonical tags", "robots directives", "XML sitemaps", "redirects", "duplicate content", "metadata templates", "schema requirements", "mobile rendering", "page speed", "Core Web Vitals priorities", "JavaScript dependencies", "migration risks"];
const onPage = ["title tags", "meta descriptions", "heading structure", "page introductions", "content relevance", "image context", "internal links", "URL review", "keyword placement", "schema recommendations"];
const contentPlanning = ["page briefs", "target queries", "search intent", "recommended headings", "questions to answer", "internal-link opportunities", "content gaps", "update priorities"];
const ecommerce = ["category targeting", "product information", "duplicate content", "crawl filters", "canonical rules", "unavailable products", "pagination", "structured data", "collection content", "shopping-intent keywords"];
const backlinks = ["relevant referring domains", "suspicious patterns", "broken links", "lost links", "competitor opportunities", "digital PR possibilities", "citation gaps"];
const reporting = ["visibility trends", "ranking movement", "organic traffic", "landing-page performance", "crawl and indexation issues", "completed actions", "implementation status", "next priorities"];
const costs = ["number of priority pages", "technical complexity", "content gaps", "market competition", "eCommerce catalogue size", "local SEO requirements", "backlink review", "reporting depth", "implementation support", "monthly content needs", "stakeholder approvals", "project duration"];
const process = [["Discovery", "We review business goals, website condition, target services, audiences and previous SEO activity."], ["Research", "We assess search demand, intent, competitors, content gaps and page ownership."], ["Audit and Prioritisation", "We identify technical, on-page, content and authority issues, then organise recommendations by importance and effort."], ["Optimisation", "We complete agreed SEO work and coordinate tasks that require content, design or development support."], ["Reporting", "We review completed activity, visibility, traffic signals, implementation progress and next priorities."], ["Ongoing Improvement", "SEO priorities may change as competitors, content, the website and search systems evolve."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section seo-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="seo-prose">{children}</div></section>; }

export default function SeoUaePage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page seo-services-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/seo-services">SEO Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">United Arab Emirates</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">SEO United Arab Emirates</span><h1>SEO Services for UAE Businesses</h1><p>For organisations comparing SEO services UAE providers, the right partner should offer more than keyword placement or monthly reports. Sustainable organic visibility depends on technical foundations, useful content, search intent, internal structure, authority signals and consistent implementation.</p><p>Vorevix supports UAE startups, SMEs, eCommerce brands, SaaS companies, professional-service firms and established organisations through remote SEO collaboration. Our work can include discovery, keyword research, technical SEO, on-page optimisation, content planning, local SEO, eCommerce SEO, backlink review, reporting and implementation coordination.</p><p>We do not promise first-page rankings, guaranteed traffic, fixed lead numbers or automatic revenue. We focus on evidence-led recommendations, measurable activity and clear communication.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UAE SEO Priorities <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-seo.png" alt="SEO strategy and reporting by Vorevix" width="1183" height="1330" fetchPriority="high"/></div></section>

    <Section title="SEO Built Around Business Priorities"><p>SEO should begin with business goals, search demand and the condition of the current website.</p><p>An SEO services UAE engagement may support a new website, an established corporate site, an eCommerce store, a SaaS platform or a business recovering from technical and content issues. The right scope depends on competition, website quality, available content, authority, implementation resources and realistic timelines.</p><p>Our work may include:</p><List items={scope}/><p>The aim is to identify priorities that can be implemented and reviewed over time.</p></Section>
    <Section title="Building Organic Visibility in Competitive UAE Markets" tinted><p>Search demand in the UAE can be competitive, especially in sectors such as real estate, professional services, retail, technology, healthcare and hospitality.</p><p>Search engines need to access and interpret the website, pages need to match relevant intent, content needs to answer useful questions and the business needs credible signals compared with competing results.</p><p>A professional SEO company in UAE markets should explain these dependencies instead of presenting SEO as a shortcut. Stronger visibility may create more opportunities for relevant traffic, but rankings and commercial outcomes remain influenced by competition, algorithms, the offer and the website experience.</p></Section>
    <Section title="SEO Discovery and Strategy"><p>Discovery creates a practical starting point before recommendations are made.</p><p>We may review:</p><List items={discovery}/><p>For SEO services UAE projects, this stage helps align business goals with realistic search opportunities before detailed execution begins.</p></Section>
    <Section title="Keyword Research and Search-Intent Analysis" tinted><p>Keyword research is not only about finding phrases with volume. It should also assess what users appear to want and whether the website can satisfy that intent.</p><p>Research may group keywords by:</p><List items={keywordGroups}/><p>Search-intent analysis helps decide whether a query needs a service page, product page, category page, guide, FAQ or supporting article.</p><p>Vorevix can use keyword evidence to recommend page ownership and reduce unnecessary overlap between pages.</p></Section>
    <Section title="Technical SEO Foundations"><p>Technical SEO helps search engines access, interpret and index website content more effectively.</p><p>For SEO services UAE campaigns, a technical review may cover:</p><List items={technical}/><p>Technical SEO recommendations involving templates, redirects, schema, performance or migrations can be implemented through our <a href="/united-arab-emirates/web-development">web development services for UAE businesses</a>.</p></Section>
    <Section title="On-Page SEO and Metadata Optimisation" tinted><p>On-page SEO helps individual pages communicate their purpose more clearly.</p><p>Work may include:</p><List items={onPage}/><p>Optimisation should not force exact phrases into every heading or paragraph. The goal is to improve relevance and clarity while preserving natural language.</p></Section>
    <Section title="Content Optimisation and Planning"><p>Content should support both search intent and the needs of real users.</p><p>Vorevix may review existing service pages, category pages, blog content, FAQs and supporting resources. Recommendations can address missing topics, weak page depth, repeated wording, outdated information or unclear page ownership.</p><p>Content planning may include:</p><List items={contentPlanning}/></Section>
    <Section title="Internal Linking and Website Structure" tinted><p>Internal links help users and search engines understand relationships between pages.</p><p>A review may examine navigation, service clusters, related content, breadcrumb structure and orphan pages. Recommendations can strengthen important routes without creating unnatural anchor repetition.</p><p>Projects requiring new page layouts, responsive presentation or a complete website redesign can connect with our <a href="/united-arab-emirates/web-design">web design services for UAE businesses</a>.</p><p>Navigation, content clarity and interaction issues requiring user research or prototype testing can be explored through our <a href="/united-arab-emirates/ui-ux-design">UI/UX design services for UAE businesses</a>.</p></Section>
    <Section title="Local SEO for UAE Businesses"><p>Local SEO can support eligible businesses with genuine physical locations or defined service areas.</p><p>Work may include Google Business Profile review, location-page assessment, local citations, name-address-phone consistency and local content recommendations.</p><p>Vorevix does not claim a UAE office or manage local listings as if it were physically present in the country. Local SEO scope should be based on the client's verified locations and available access.</p></Section>
    <Section title="eCommerce SEO" tinted><p>eCommerce SEO may involve category structure, product-page optimisation, faceted navigation, internal links, technical controls and content planning.</p><p>Important areas may include:</p><List items={ecommerce}/><p>A broad SEO services UAE page should cover eCommerce at a high level. Complex stores may require a separate specialist scope depending on platform, catalogue size, integrations and technical limitations.</p></Section>
    <Section title="Authority Building and Backlink Review"><p>Authority signals can influence how competitive pages perform, but link acquisition should be approached carefully.</p><p>A backlink review may identify:</p><List items={backlinks}/><p>Authority-building work should prioritise relevant and editorially appropriate opportunities. No agency should guarantee a fixed number of high-quality backlinks, permanent rankings or risk-free outcomes.</p></Section>
    <Section title="SEO Reporting and Performance Review" tinted><p>SEO services UAE reporting should help teams understand what was completed, what changed and what requires attention.</p><p>Reports may include:</p><List items={reporting}/><p>For SEO services UAE engagements, Vorevix can coordinate reviews during suitable UAE business hours using shared reports, meetings and written recommendations.</p><p>Remote collaboration can include scheduled review meetings, shared dashboards, written action lists and documented implementation responsibilities. This gives marketing, content and development stakeholders a consistent record of completed work, unresolved dependencies and the priorities recommended for the next reporting period, without presenting reporting as a guarantee of future results.</p></Section>
    <Section title="Multilingual and Arabic SEO Planning"><p>UAE websites may target English, Arabic or additional languages.</p><p>Multilingual SEO can involve keyword research, content localisation, language targeting, hreflang, metadata and technical structure. Arabic SEO requires verified language and cultural capability.</p><p>Where translation and localisation are managed by another provider, we can coordinate technical requirements around approved content.</p></Section>
    <Section title="SEO Cost Factors in the UAE" tinted><p>SEO cost depends on scope, competition, website condition and implementation requirements.</p><p>Common factors include:</p><List items={costs}/><p>An SEO services UAE proposal should separate strategy, implementation, content, development and digital PR where appropriate.</p><p>Vorevix does not publish invented AED prices, VAT statements, guaranteed timelines or fixed ranking outcomes without reviewing the actual requirements.</p></Section>
    <section className="wd-section seo-section"><div className="wd-section-heading"><h2>Our SEO Process</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="wd-section seo-section wd-tinted"><div className="wd-section-heading"><h2>Why Work With Vorevix?</h2><p>Our SEO services UAE approach combines strategy, technical review, content planning, on-page optimisation, reporting and practical coordination without promising guaranteed rankings or commercial outcomes.</p></div><div className="seo-prose"><p>Businesses may work with Vorevix for keyword research, search-intent analysis, technical SEO, metadata, content optimisation, internal linking, local SEO, eCommerce SEO, backlink audits and monthly support.</p><p>Brand communication can connect with our <a href="/services/branding">branding services</a>, while wider campaigns can use our <a href="/services/digital-marketing">digital marketing services</a>.</p><p>For broader methodology, <a href="/services/seo-services">explore our complete SEO services</a>.</p></div></section>
    <section className="wd-section seo-section wda-section"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="wda-faq-list">{seoUaeFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `seo-uae-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan Your UAE SEO Project</h2><p>Effective SEO services UAE work requires clear priorities, useful content, technical cooperation and realistic expectations.</p><p>Vorevix helps UAE businesses identify organic-search opportunities, improve important pages and coordinate implementation across content, design and development.</p><p>Share your website, priority services, target audiences, previous SEO work and current challenges. We will review the requirements and recommend the next practical step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UAE SEO Priorities <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
