import { useState } from "react";
import { ArrowRight, ChevronDown, PanelsTopLeft } from "lucide-react";
import { uiUxNewZealandFaqs } from "../uiUxNewZealandFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./UiUxDesignPage.css";

const costs = ["number of products, screens or user roles", "research requirements", "access to users and existing data", "UX audit depth", "complexity of journeys and workflows", "wireframe and prototype fidelity", "responsive requirements", "mobile, web-app or SaaS scope", "usability-testing requirements", "design-system needs", "stakeholder and approval complexity", "developer handoff and collaboration", "ongoing iteration or design support"];
const reasons = ["requirements-led discovery", "evidence-informed UX decisions", "clear information architecture", "user journeys and task flows", "wireframes and prototypes", "usability-focused interface design", "responsive UI systems", "website, web-app, mobile and SaaS design", "accessibility-aware decisions", "reusable component libraries", "design handoff and developer collaboration", "remote collaboration across New Zealand business hours", "qualified recommendations without guaranteed outcomes"];
const process = [["Discovery", "We review business goals, users, current products, constraints, stakeholders and the decisions the project needs to support."], ["Research and Analysis", "Relevant research, feedback, analytics and competitor patterns are reviewed to identify needs, behaviours and potential friction."], ["Structure and Flows", "We develop information architecture, user journeys, task flows and content priorities."], ["Wireframes and Prototypes", "Key screens and interactions are mapped, reviewed and refined before final styling."], ["Interface Design", "Approved structures are developed into responsive, brand-aligned interface systems."], ["Testing and Iteration", "Where included, prototypes or working interfaces are tested and adjusted according to findings."], ["Handoff and Collaboration", "Design files, components, notes and interaction details are prepared for development."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section uiux-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="uiux-prose">{children}</div></section>; }

export default function UiUxNewZealandPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page uiux-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/ui-ux-design-services">UI/UX Design</a></li><li aria-hidden="true">/</li><li><span aria-current="page">New Zealand</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">UI/UX Design New Zealand</span><h1>UI/UX Design for New Zealand Businesses</h1><p>For organisations comparing UX design NZ providers, the right partner should do more than make screens look polished. Strong user experience work connects business goals, user needs, content, functionality and technical realities. Without that connection, even an attractive interface can create confusion, increase friction or make development harder than it needs to be.</p><p>Vorevix provides UI/UX design for New Zealand businesses through a structured remote process. We help teams understand users, organise information, map journeys, develop wireframes, create prototypes, design interfaces and prepare clear handoff materials for development.</p><p>Our UX design NZ approach does not promise guaranteed conversions, engagement or business growth. Instead, we focus on evidence-informed decisions, practical collaboration and interface systems that can support clearer experiences across websites, web applications, mobile products, dashboards and digital services.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UI/UX Design Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-software-app.png" alt="UI and UX interface design by Vorevix" width="1306" height="1205" fetchPriority="high"/></div></section>

    <Section title="UX Design NZ Built Around Real User Needs"><p>A UX design NZ project begins by understanding what users are trying to achieve, what information they need and where they may encounter friction. It also requires an understanding of business goals, operational constraints and the technology that will support the final experience.</p><p>Vorevix brings these factors together before detailed interface design begins. Depending on scope, our process may include stakeholder discussions, existing-product reviews, competitor analysis, user research, analytics review, journey mapping, information architecture and usability evaluation.</p></Section>
    <Section title="UX Discovery and Stakeholder Alignment" tinted><p>UX discovery creates a shared understanding of the project before screens are designed. During this stage, we review the product or service, intended users, business objectives, current pain points, technical constraints and success criteria.</p><p>For UX design NZ projects, remote workshops and review sessions can be scheduled around New Zealand business hours. Decisions, open questions and next actions are documented so teams can review progress without relying only on meetings.</p></Section>
    <Section title="User Research and Evidence-Informed Decisions"><p>User research can help teams understand behaviours, expectations, needs and sources of frustration. The right method depends on the product, available users, budget and stage of development.</p><p>Vorevix uses research to reduce reliance on assumptions. Insights may inform content priorities, navigation, feature order, interaction patterns and the language used across the interface.</p><p>Research outcomes depend on relevant questions, available information and sound interpretation.</p></Section>
    <Section title="UX Audits and Heuristic Evaluation" tinted><p>An existing website or digital product may not need to be rebuilt immediately. A focused UX audit can help identify unclear navigation, inconsistent interactions, missing feedback, confusing forms or friction in important tasks.</p><p>An audit may review hierarchy, labels, calls to action, page flow, consistency, mobile behaviour and common usability principles. Analytics, customer feedback and support information can strengthen the review when available.</p><p>The resulting recommendations can help teams prioritise content, interface or development changes instead of treating every issue as a complete redesign requirement.</p></Section>
    <Section title="Journeys, Flows and Information Architecture"><p>User journeys show how people move through a service or product over time. User flows focus on the steps required to complete a particular task, such as submitting an enquiry, creating an account, purchasing a product or managing information.</p><p>Information architecture organises pages, content and functions so users can understand where they are and where to go next. Clear structure can help users find information more easily, but it does not guarantee that every user will follow the same path.</p><p>Our UX design NZ work may include journey maps, task flows, sitemap planning, navigation models and content hierarchies. These outputs help align stakeholders before detailed interface design and can also support content, SEO and development planning.</p></Section>
    <Section title="Wireframes and Prototypes Before Development" tinted><p>Wireframes show the structure and priority of content without relying on final visual styling. They help teams review layout, page hierarchy, actions, components and responsive behaviour at an early stage.</p><p>Wireframes create a practical checkpoint where stakeholders can identify missing information, unclear priorities or unnecessary complexity before final interface styling begins.</p><p>Prototypes demonstrate how selected screens or interactions may behave. They allow stakeholders to review concepts before full development and can support usability testing.</p><p>A prototype is not a finished application and does not prove that a product will succeed. Its purpose is to make proposed interactions easier to evaluate before development resources are committed.</p></Section>
    <Section title="User Interface Design"><p>UI design turns approved structure and interaction decisions into a clear visual system. It includes layout, spacing, typography, colour, buttons, forms, navigation, states and reusable components.</p><p>Our interface work aims to balance brand expression with usability. Visual styling should support hierarchy and interaction rather than make key tasks harder to understand.</p><p>Consistent components also help developers understand repeated patterns.</p></Section>
    <Section title="Responsive and Accessibility-Aware Design" tinted><p>Users may access a product through desktops, laptops, tablets and phones. Responsive interface design considers how layouts, content and actions adapt across screen sizes.</p><p>Navigation, tables, forms, content density, touch targets and component behaviour may need different treatment on smaller screens. Responsive design should therefore be considered during the UX and UI process rather than left entirely until development.</p><p>Accessibility-aware design considers colour contrast, readable type sizes, clear focus states, logical hierarchy, understandable labels and consistent interaction patterns. These practices can support a wider range of users and often improve general clarity.</p><p>Vorevix does not claim full WCAG compliance unless specific standards, testing and remediation work are included and verified.</p></Section>
    <Section title="Usability Testing and Iteration"><p>Usability testing observes how representative users attempt important tasks. It can help identify hesitation, misunderstanding, missed actions or unexpected behaviour.</p><p>Vorevix can use findings to refine flows, labels, page structure and interactions. Further testing may be valuable after changes, especially for high-impact or complex workflows.</p><p>Testing can reveal potential problems, but it cannot guarantee that a product will be easy for every user. Results depend on participant selection, task design, product context and the quality of interpretation.</p></Section>
    <Section title="Design Systems and Developer Handoff" tinted><p>A design system can help teams maintain consistency as a product grows. Reusable components, shared interaction rules and documented visual decisions can reduce unnecessary variation across screens.</p><p>Good handoff is not simply sending design files. Developers need clarity around responsive behaviour, component states, interactions, content rules and edge cases.</p><p>Vorevix can prepare structured files, notes and specifications for implementation. Collaboration during development can help resolve questions and identify differences between the approved design and the working product.</p><p>Once interface designs are approved, our <a href="/new-zealand/web-development">New Zealand website-development service</a> can support implementation, integrations, testing and launch.</p><p>For complete marketing-site planning and visual website design, explore our <a href="/new-zealand/web-design">web design services for New Zealand businesses</a>.</p></Section>
    <section className="wd-section uiux-section wd-tinted"><div className="wd-section-heading"><h2>Our UI/UX Design Process for New Zealand Teams</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p className="wda-note">Explore our <a href="/services/ui-ux-design-services">complete UI/UX design services</a> for a broader view of our global capabilities and methodology.</p></section>
    <Section title="Remote Collaboration Across New Zealand"><p>Vorevix supports UX design NZ projects through remote meetings, shared design files, written updates and milestone-based approvals.</p><p>We collaborate with founders, product managers, marketers, developers and stakeholders across New Zealand business hours. Clear review stages keep feedback organised and reduce conflicting instructions.</p><p>National availability does not imply a New Zealand office, local telephone number or New Zealand-based UX team. Services are delivered through structured remote collaboration.</p></Section>
    <Section title="What Influences UI/UX Design Cost in New Zealand?" tinted><p>The cost of UX design NZ work depends on the depth and complexity of the engagement rather than one standard package.</p><p>Important factors may include:</p><List items={costs}/><p>This UX design NZ service is scoped around the actual research, design and collaboration required. Vorevix prepares a tailored proposal after reviewing the requirements.</p><p>We do not publish unsupported NZD pricing, GST statements or fixed timelines for every project.</p></Section>
    <section className="wd-section"><div className="wd-section-heading"><h2>Why Choose Vorevix for UX Design NZ?</h2><p>Our UX design NZ service combines research, structure, interface design and practical collaboration without forcing every project into the same process.</p></div><div className="wd-card-grid">{reasons.map((reason) => <article className="wd-card" key={reason}><PanelsTopLeft className="wd-card-icon" size={25} aria-hidden="true"/><h3>{reason}</h3></article>)}</div></section>
    <section className="wd-section uiux-section wda-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions About UI/UX Design in New Zealand</h2></div><div className="wda-faq-list">{uiUxNewZealandFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `ui-ux-nz-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan a Clearer Digital Experience</h2><p>A strong UX design NZ project should connect user needs, business goals, content, interface decisions and technical delivery.</p><p>Vorevix helps New Zealand businesses research, structure, prototype and design digital experiences that are clearer to review, easier to implement and better aligned with the needs of users and stakeholders.</p><p>Share your current website or product, intended users, key challenges and expected timeline. We will review the information and discuss an appropriate next step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UI/UX Design Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
