import { useState } from "react";
import { ArrowRight, ChevronDown } from "lucide-react";
import { uiUxUaeFaqs } from "../uiUxUaeFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./UiUxDesignPage.css";

const scope = ["UX discovery and stakeholder workshops", "user and competitor research", "UX audits and heuristic evaluation", "user journeys and task flows", "information architecture", "wireframes and interactive prototypes", "usability testing", "interaction and user-interface design", "design systems", "developer handoff and design QA"];
const discovery = ["priority users", "important tasks", "required features", "product risks", "research questions", "approval stages", "content responsibilities", "technical limitations", "assumptions that require testing"];
const journeyDetails = ["where a user begins", "what information they need", "which decisions must be made", "where confusion may occur", "what happens after success or failure", "which systems or teams are involved"];
const productInterfaces = ["onboarding", "account registration", "subscriptions", "navigation systems", "settings", "dashboards", "forms and tables", "filters", "notifications", "empty states", "error states", "role-based interfaces"];
const systemParts = ["typography", "colour usage", "spacing", "buttons", "forms", "cards", "tables", "modals", "interaction states", "design tokens", "component documentation"];
const handoff = ["responsive layouts", "component states", "spacing and typography guidance", "interaction notes", "design tokens", "asset exports", "content requirements", "edge cases", "prototype links"];
const costs = ["discovery and workshops", "participant recruitment", "UX audit depth", "number of journeys and flows", "wireframe fidelity", "prototype complexity", "usability-testing rounds", "responsive requirements", "design-system requirements", "stakeholder approvals", "developer handoff", "design QA", "expected timeline"];
const process = [["Discovery", "We review the product, audience, available evidence, business goals, constraints and stakeholder priorities."], ["Research and Analysis", "We gather relevant evidence, review competing products and identify user needs, risks and assumptions."], ["Structure and Flows", "We define journeys, task flows, information architecture and content priorities."], ["Wireframes and Prototypes", "We create and refine layouts and interactive journeys for stakeholder review or user testing."], ["Interface Design", "We translate approved structure into responsive visual components and interaction states."], ["Testing and Refinement", "Where included, we test selected tasks and improve the design using relevant findings."], ["Handoff and Design QA", "We prepare specifications and support implementation review according to the agreed project scope."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section uiux-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="uiux-prose">{children}</div></section>; }

export default function UiUxUaePage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page uiux-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/ui-ux-design-services">UI/UX Design</a></li><li aria-hidden="true">/</li><li><span aria-current="page">United Arab Emirates</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">UI/UX Design United Arab Emirates</span><h1>UI/UX Design for UAE Businesses</h1><p>For organisations comparing UX design UAE providers, the right partner should do more than create polished screens. A useful digital product needs clear structure, evidence about user needs, practical interaction flows and interfaces that can be reviewed, tested and implemented.</p><p>Vorevix supports UAE startups, SaaS teams, eCommerce businesses, professional-service firms and established organisations through remote UI/UX collaboration. Our work can include discovery, user research, UX audits, journeys, information architecture, wireframes, prototypes, usability testing, interface design, design systems and developer handoff.</p><p>We do not promise guaranteed conversions, effortless usability or automatic growth. Instead, we focus on structured decisions, clear documentation and design work that supports product and business objectives.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UI/UX Design Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-software-app.png" alt="UI and UX interface design by Vorevix" width="1306" height="1205" fetchPriority="high"/></div></section>

    <Section title="UI/UX Design Built Around Product Priorities"><p>A UX design UAE engagement may support a mobile application, SaaS platform, customer portal, dashboard, eCommerce experience or an existing product that needs improvement. It should begin with the problem, audience and team decisions. Scope depends on product maturity, evidence, stakeholder goals and technical constraints.</p><p>Our work may include:</p><List items={scope}/><p>The aim is to reduce avoidable uncertainty and give teams a clearer basis for design and implementation decisions.</p></Section>
    <Section title="Understanding Users Before Designing Interfaces" tinted><p>Research can identify user goals, friction and assumptions requiring validation through interviews, surveys, analytics, product reviews, support feedback or competitor analysis.</p><p>It does not provide perfect certainty or represent every future customer, but can inform what to design, test or prioritise.</p><p>For UX design UAE projects, research and workshops can be coordinated remotely during suitable UAE business hours. Participant recruitment, language requirements and local research capabilities must be confirmed separately.</p></Section>
    <Section title="UX Discovery and Stakeholder Workshops"><p>Discovery aligns stakeholders before detailed design. Workshops may cover product objectives, audiences, business rules, evidence, technical dependencies and success criteria.</p><p>This stage can clarify:</p><List items={discovery}/><p>Documentation helps design, development and business teams work from the same understanding.</p></Section>
    <Section title="UX Audits and Heuristic Evaluation" tinted><p>An existing product may need a structured review rather than a complete redesign.</p><p>A UX audit can examine navigation, hierarchy, consistency, feedback, errors, forms and content clarity. Heuristic evaluation compares the interface with recognised usability principles.</p><p>An audit cannot find every issue; findings depend on the product, evidence and selected journeys.</p><p>Vorevix can organise recommendations by severity, affected users, business importance and implementation effort.</p></Section>
    <Section title="User Journeys, Task Flows and Information Architecture"><p>User journeys describe broader experiences; task flows show steps for a particular action.</p><p>These artefacts can help teams understand:</p><List items={journeyDetails}/><p>Information architecture organises content, features and navigation so users understand what they can do next.</p><p>For UX design UAE projects, journeys may reveal account, approval, payment, language or support requirements affecting the interface.</p></Section>
    <Section title="Wireframes and Interactive Prototypes" tinted><p>Wireframes help teams review structure and priority before detailed visual design. Low-fidelity versions focus on layout, content, navigation and actions; higher-fidelity versions add interaction decisions.</p><p>Interactive prototypes let stakeholders and participants experience proposed journeys, forms, component states and task paths before development.</p><p>A prototype is not a production system and may omit live data, complete accessibility behaviour or technical edge cases. It supports review and testing.</p></Section>
    <Section title="Usability Testing"><p>Usability testing observes participants completing selected tasks using a product or prototype.</p><p>It can reveal unclear wording, hidden actions, navigation problems and differences between assumptions and user behaviour.</p><p>Findings apply only to the tested tasks, sample and design version; they do not prove universal usability.</p><p>A UX design UAE engagement may include moderated sessions, unmoderated testing or stakeholder observation when participants, language support and technology are available.</p></Section>
    <Section title="Interaction and User-Interface Design" tinted><p>Interaction design defines responses to navigation, choices, inputs, forms and errors.</p><p>For UX design UAE projects, user-interface design translates approved requirements into a visual system covering hierarchy, typography, spacing, colour, components, feedback and responsive behaviour.</p><p>UI should support clarity and work with content, product logic, branding and development constraints.</p><p>Vorevix can apply existing brand assets, while full strategy and identity remain part of <a href="/services/branding">Branding</a>.</p></Section>
    <Section title="Mobile Apps, Web Apps and SaaS Interfaces"><p>Mobile applications, web applications and SaaS platforms often include complex journeys, account states, permissions, dashboards and repeated workflows.</p><p>Depending on scope, Vorevix may design:</p><List items={productInterfaces}/><p>The UI/UX page owns research, flows, prototypes and interface specifications.</p><p>Technical architecture, application logic, APIs, databases, deployment and maintenance belong to Web Development.</p><p>Approved interfaces can move into technical implementation through our <a href="/united-arab-emirates/web-development">web development services for UAE businesses</a>.</p></Section>
    <Section title="Dashboards and eCommerce UX" tinted><p>Dashboards should help users locate relevant information, understand status and complete recurring tasks without unnecessary complexity.</p><p>Design work may consider data hierarchy, filters, tables, charts, alerts, permissions and responsive behaviour. The design should reflect the actual data and decisions users need to make.</p><p>eCommerce UX may cover product discovery, categories, search, filters, product details, cart behaviour and checkout journeys.</p><p>Interface design can reduce avoidable friction, but it cannot guarantee purchases, retention or revenue.</p><p>Complex dashboard and eCommerce projects may require separate specialist scope, research and technical planning.</p></Section>
    <Section title="Design Systems and Component Libraries"><p>A design system can help teams create more consistent interfaces and reduce repeated design decisions.</p><p>Depending on scope, it may include:</p><List items={systemParts}/><p>Not every product needs a large enterprise design system.</p><p>Smaller teams may benefit from a focused component library that supports current screens and expected product growth.</p><p>For distributed UX design UAE teams, shared components and documented interface rules can improve communication between designers, developers and stakeholders.</p></Section>
    <Section title="Accessibility-Aware Interface Design" tinted><p>Accessibility-aware design considers how different users may perceive, navigate and interact with an interface.</p><p>Design decisions may review contrast, hierarchy, labels, form feedback, target sizes, focus order and keyboard interaction requirements.</p><p>Accessibility should not be presented as an absolute claim without defined standards, technical implementation and testing.</p><p>Vorevix should only claim WCAG compliance where the required design, development and audit work has been verified.</p></Section>
    <Section title="Multilingual and RTL Interface Planning"><p>UAE products may need to support English, Arabic or additional languages.</p><p>Multilingual planning can affect navigation length, content structure, typography, alignment, components and testing.</p><p>Right-to-left interfaces may require changes to direction, icons, tables and interaction patterns.</p><p>Arabic research, translation, copywriting and specialist RTL design should only be included where the required capability has been confirmed.</p><p>Where language production is managed by another provider, Vorevix can plan interface structures around approved translated content and documented localisation requirements.</p></Section>
    <Section title="Developer Handoff and Design QA" tinted><p>Approved designs need clear specifications before implementation.</p><p>The handoff may include:</p><List items={handoff}/><p>Structured handoff can support more consistent development, but it does not replace communication between designers and developers.</p><p>Design QA may compare implemented screens with approved designs and document visual or interaction differences.</p><p>Development teams remain responsible for technical implementation, testing, security and deployment.</p></Section>
    <Section title="Remote Collaboration Across the UAE"><p>Vorevix works remotely with organisations throughout the United Arab Emirates.</p><p>As a UX design UAE partner, we can coordinate with founders, product managers, marketing teams, developers, customer-support teams and decision-makers during suitable UAE business hours.</p><p>Collaboration may use video workshops, shared design files, prototypes, recorded walkthroughs and documented feedback.</p><p>National availability does not imply a UAE office, local phone number, UAE employees, Arabic-speaking researchers or UAE case studies unless independently verified.</p></Section>
    <Section title="UI/UX Design Cost Factors in the UAE" tinted><p>UI/UX cost depends on research depth, product complexity, number of journeys, screen count, testing requirements and design-system scope.</p><p>Common cost factors include:</p><List items={costs}/><p>A UX design UAE proposal should separate research, design, testing, development and language services where appropriate.</p><p>Vorevix does not publish invented AED prices, UAE VAT statements or fixed project timelines without reviewing the actual requirements.</p></Section>
    <section className="wd-section uiux-section"><div className="wd-section-heading"><h2>Our UI/UX Design Process</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="wd-section uiux-section wd-tinted"><div className="wd-section-heading"><h2>Why Work With Vorevix?</h2><p>Our UX design UAE approach combines research, structure, interface design and practical handoff without promising guaranteed commercial outcomes.</p></div><div className="uiux-prose"><p>Businesses may work with Vorevix for discovery, UX audits, journeys, flows, information architecture, wireframes, prototypes, usability testing, mobile and web-app interfaces, SaaS products, dashboards, eCommerce UX, design systems and development coordination.</p><p>Marketing and corporate websites requiring page planning and responsive visual layouts can be supported through our <a href="/united-arab-emirates/web-design">web design services for UAE businesses</a>.</p><p>For broader methodology, <a href="/services/ui-ux-design-services">explore our complete UI/UX design services</a>.</p></div></section>
    <section className="wd-section uiux-section wda-section"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="wda-faq-list">{uiUxUaeFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `ui-ux-uae-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan Your UAE UI/UX Project</h2><p>A useful digital product needs evidence, clear structure, understandable interactions and interfaces that development teams can implement.</p><p>Vorevix helps UAE organisations turn product requirements into journeys, flows, wireframes, prototypes and coherent interface systems.</p><p>Share your product idea, existing screens, target users, required features, technical constraints and expected timeline. We will review the requirements and recommend the next appropriate step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your UI/UX Design Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
