import { useState } from "react";
import { ArrowRight, ChevronDown, PanelsTopLeft } from "lucide-react";
import { uiUxFaqs } from "../uiUxFaqs";
import "./WebDevelopmentPage.css";
import "./UiUxDesignPage.css";

const services = [
  ["UX Research and Discovery", ["Research helps the team understand the problem before committing to a solution. Discovery may include stakeholder discussions, competitor analysis, analytics review, interviews or usability testing.", "The approach depends on scope, user access, timeline and budget. Available evidence is used to identify needs, assumptions and risks."]],
  ["Information Architecture and User Flows", ["Information architecture defines how content, features and navigation are organised. User flows map important tasks such as submitting an enquiry, creating an account or managing information in a dashboard. Clear flows reduce unnecessary decisions and align design with development."]],
  ["Wireframing and Prototyping", ["Wireframes translate requirements and flows into screen structures before detailed visual work begins. They help review hierarchy, content placement and interaction patterns without distraction from colours or decorative choices.", "A clickable prototype demonstrates key journeys without requiring a working build. It supports review, testing and developer understanding."]],
  ["User Interface Design Services", ["Our UI design services turn approved UX structures into polished, consistent and responsive interfaces. We define hierarchy, typography, spacing, colour usage, components and interaction states while respecting the existing brand.", "Each decision should improve clarity, reinforce priorities and make repeated actions easier to understand."]],
  ["Responsive Interface Design", ["Responsive design is not simply shrinking a desktop screen. Content priorities, navigation and controls may need to change as space decreases.", "We design important responsive states so developers understand expected behaviour across desktop, tablet and mobile. This helps prevent inconsistent decisions during implementation."]],
  ["Design Systems and Component Libraries", ["A design system creates reusable rules for a growing digital product. It may include typography, colours, spacing, buttons, forms, cards, tables, navigation and feedback states.", "A focused component library may suit smaller projects, while larger products may need a broader system to improve consistency."]],
  ["UI UX Audits and Redesign", ["An audit reviews an existing experience to identify usability problems, inconsistent patterns, accessibility concerns and possible conversion barriers. Findings can be prioritised by severity and effort.", "A redesign can then improve selected journeys or the complete interface. We avoid changing everything only for visual novelty. Existing patterns that work can remain, while weak areas are rebuilt around clearer evidence and goals."]],
];

const process = [
  ["1. Discovery and Goals", "We begin by understanding the business, users, product purpose, challenges and required outcomes. Existing research, analytics and technical constraints are reviewed where available."],
  ["2. Research and Experience Review", "We select suitable research methods and examine competitors, current journeys and user evidence. Assumptions are recorded so they can be validated."],
  ["3. Structure and User Flows", "We organise content and features, map important journeys and define how users should move through the experience."],
  ["4. Wireframes", "Core screens are structured at low fidelity. The team reviews hierarchy, functionality and missing requirements before detailed visual design begins."],
  ["5. High-Fidelity UI and Prototype", "Approved structures are developed into detailed interfaces and connected into an interactive prototype for review."],
  ["6. Testing and Iteration", "Where included, prototypes or existing experiences are tested. Findings are prioritised and the design is refined."],
  ["7. Design System and Responsive States", "Reusable components, important states and responsive behaviour are documented according to the project’s needs."],
  ["8. Developer Handoff and Design QA", "Final files are organised for implementation. We can answer developer questions, clarify interactions and review the implemented interface against the approved design."],
];

function List({ items }) { return <ul className="wd-checklist">{items.map(item=><li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted=false }) { return <section className={`wd-section uiux-section${tinted?" wd-tinted":""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="uiux-prose">{children}</div></section>; }
function Faq({ faq,index }) { const [open,setOpen]=useState(index===0); const id=`uiux-faq-${index}`; return <article className="uiux-faq"><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)}>{faq.question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{faq.answer}</p></div></article>; }

export default function UiUxDesignPage() {
  return <main className="web-development-page uiux-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">UI UX Design Services</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><h1>UI UX Design Services Built Around Real User Needs</h1><p>Vorevix provides research-led ui ux design services for websites, web applications and digital products that need clearer journeys, usable interfaces and development-ready design systems. We combine user experience thinking with thoughtful interface design to help businesses reduce friction, organise complex information and create experiences that feel natural to use.</p><p>Our work can support a new product, an existing platform that needs improvement or a website that is no longer meeting user and business needs. Every engagement is shaped around the project’s goals, audience, technical requirements and available evidence.</p><div className="wd-actions"><a className="primary" href="/contact">Start Your UI UX Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-software-app.png" alt="UI UX design services for digital products" width="1306" height="1205" fetchPriority="high"/></div></section>

    <Section title="Design Problems That Affect Growth and Usability"><p>A digital product can look polished and still be difficult to use. Confusing navigation, weak hierarchy, inconsistent components and unclear actions can stop users from completing important tasks. Businesses may see low engagement, abandoned forms, repeated support questions or weak conversion paths without knowing where the experience is failing.</p><p>Our design approach addresses these problems by examining how people move through a website or product, what information they need and where uncertainty appears. The goal is not decoration. It is to create a clearer structure, more consistent interactions and an interface that supports both user needs and business priorities.</p><p>Related website projects can also connect interface improvements with our <a href="/services/seo-services">SEO services</a>.</p></Section>

    <Section title="What Is the Difference Between UI and UX Design?" tinted><p>UX design focuses on how an experience works. It considers user needs, information structure, navigation, task flows, usability and the steps people take to reach an outcome.</p><p>UI design focuses on how that experience is presented. It covers visual hierarchy, typography, colour, spacing, components, states and responsive behaviour.</p><p>A beautiful interface cannot repair a confusing journey, while a logical flow still needs clear visual communication. Vorevix combines both disciplines so the final design is useful, coherent and ready for development.</p></Section>

    <section className="wd-section uiux-section"><div className="wd-section-heading"><h2>Our UI UX Design Services</h2><p>We support new websites, software products, dashboards, customer portals and existing experiences that need redesign or improvement.</p></div><div className="wd-card-grid">{services.map(([title,paragraphs])=><article className="wd-card" key={title}><PanelsTopLeft className="wd-card-icon" aria-hidden="true"/><h3>{title}</h3>{paragraphs.map(p=><p key={p}>{p}</p>)}</article>)}</div></section>

    <Section title="Website UX and Product UX Require Different Thinking"><p>Website UX focuses on navigation, content hierarchy, service discovery and conversion paths. Product UX covers repeated tasks inside applications, portals and dashboards, including accounts, permissions, forms, data tables and workflows.</p><p>Our team can support both contexts, but the research, flows and deliverables are adjusted to the type of experience being designed. Website projects can also connect with our <a href="/services/web-design">web design services</a>.</p></Section>

    <Section title="Usability Testing and Iteration" tinted><p>Usability testing reveals whether people understand the interface as intended. Participants complete realistic tasks in a prototype or live product while the team observes confusion and errors.</p><p>Even a focused review can expose assumptions that were invisible to the project team. Findings are used to improve the design before development or during optimisation.</p></Section>

    <Section title="What You Receive"><p>Deliverables are defined in the approved scope and may include:</p><List items={["Discovery findings and recommendations","User journeys and user flows","Information architecture","Low-fidelity wireframes","High-fidelity interface designs","Clickable prototypes","Responsive screen variants","Component libraries or design systems","Interaction notes and export-ready assets","Organised, developer-ready Figma files","Design handoff and implementation support"]}/><p>Exact deliverables depend on project complexity and the approved scope.</p></Section>

    <section className="wd-section uiux-section wd-tinted"><div className="wd-section-heading"><h2>Our UI UX Design Services Process</h2></div><div className="wd-process-grid">{process.map(([title,body])=><article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <Section title="Developer-Ready Design Handoff"><p>A good handoff explains how components behave, what changes across devices and how the system responds to user actions. It can include spacing, typography, assets, component variants, validation, errors and responsive behaviour in organised Figma files.</p><p>When Vorevix also provides <a href="/services/web-development-services">web development services</a>, design and implementation can be coordinated directly. We can also work with an external or in-house development team.</p></Section>

    <Section title="Why Choose Vorevix as Your UI UX Design Agency?" tinted><p>Vorevix combines design thinking with practical awareness of development, content and business goals. We avoid treating UI/UX as an isolated visual exercise.</p><p>Clients choose our ui ux design services for clear communication, research matched to the project, responsive interface thinking, practical design systems, developer-ready files, transparent deliverables and support from discovery through handoff.</p><p>We do not promise guaranteed conversions or growth. Outcomes also depend on the product, market, development quality and business model. Broader identity work can connect with our <a href="/services/branding">branding services</a>.</p></Section>

    <Section title="UI UX Design Pricing Factors"><p>Cost depends on the number of screens, complexity of user flows, research requirements, responsive states, prototype depth and design-system needs.</p><p>A focused website review requires less work than a multi-role application with complex workflows. After reviewing the requirements, Vorevix recommends an appropriate scope instead of applying one fixed package to every project.</p></Section>

    <Section title="Ownership and Editable Files" tinted><p>Final approved design files, agreed assets and relevant access are handed over according to the approved scope, contract and payment terms. Where Figma is used, agreed file or project access can be transferred or shared at handoff.</p><p>Third-party fonts, assets and plugins remain subject to their own licence terms.</p></Section>

    <section className="wd-section uiux-section"><div className="uiux-prose"><p>Vorevix works with businesses worldwide and also provides <a href="/australia/ui-ux-design">UI/UX design services to organisations across Australia</a>, New Zealand and the United Arab Emirates.</p></div></section>

    <section className="wd-section uiux-section"><div className="wd-section-heading"><h2>Frequently Asked Questions About UI UX Design Services</h2></div><div className="uiux-faq-list">{uiUxFaqs.map((faq,index)=><Faq faq={faq} index={index} key={faq.question}/>)}</div></section>

    <section className="wd-final-cta"><h2>Create a Clearer Digital Experience</h2><p>Strong digital experiences are built around real tasks, clear information and consistent interaction patterns. Vorevix provides ui ux design services for businesses that need a new product, a more usable website or a thoughtful redesign of an existing platform.</p><p>Discuss your users, goals and technical requirements with our team to see how our ui ux design services can support the right design scope.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></section>
  </main>;
}
