import { useState } from "react";
import { ArrowRight, ChevronDown, Code2 } from "lucide-react";
import { webDevelopmentNewZealandFaqs } from "../webDevelopmentNewZealandFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";

const discovery = ["business goals and priority services", "target users and essential tasks", "current technical limitations", "required pages and content types", "content-management needs", "forms, accounts or booking requirements", "eCommerce functionality", "third-party platforms and APIs", "migration requirements", "security and access considerations", "approval processes", "launch and maintenance expectations"];
const costs = ["number and complexity of templates", "CMS and content-model requirements", "front-end and back-end development", "custom functionality", "eCommerce requirements", "API and third-party integrations", "content or data migration", "testing requirements", "hosting and deployment responsibilities", "security and access requirements", "stakeholder complexity", "documentation and training", "post-launch maintenance"];
const process = [["Discovery", "We review business requirements, users, existing systems, content and technical dependencies."], ["Technical Planning", "The development scope, content model, functionality, integrations and delivery responsibilities are documented."], ["Implementation", "Front-end components, back-end systems, CMS structures and agreed functionality are developed according to scope."], ["Integration and Migration", "External systems, content or data are connected and migrated where included."], ["Quality Review", "The website is checked across agreed browsers, devices and workflows."], ["Deployment and Handover", "The approved build is prepared for launch, with access, documentation and responsibilities confirmed."]];
const reasons = ["clear technical discovery and scoping", "responsive front-end implementation", "back-end and CMS development", "custom functionality", "eCommerce development coordination", "API and third-party integrations", "migration planning", "performance-conscious implementation", "SEO-aware technical foundations", "accessibility-aware development", "quality assurance and launch support", "remote collaboration across New Zealand business hours"];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="wda-prose">{children}</div></section>; }

export default function WebDevelopmentNewZealandPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/web-development-services">Web Development</a></li><li aria-hidden="true">/</li><li><span aria-current="page">New Zealand</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Web Development New Zealand</span><h1>Website Development for New Zealand Businesses</h1><p>For organisations comparing website development NZ providers, the strongest option is not simply the company that can produce the most features. A successful project should connect business goals, technical requirements, user experience, integrations, testing and long-term maintainability. Without that coordination, a website may launch with unnecessary complexity or technical limitations that become expensive to resolve later.</p><p>Vorevix provides website development for New Zealand businesses through a structured remote process. We plan technical requirements, front-end and back-end implementation, content-management systems, custom functionality, integrations, quality assurance and launch support around the needs of each organisation.</p><p>Our website development NZ approach does not rely on guaranteed rankings, perfect performance, complete security or fixed sales outcomes. Instead, we focus on creating maintainable, responsive and practical website foundations that can support communication, marketing and business operations.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Website Development Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/service-software-app.png" alt="Website development interface by Vorevix" width="1306" height="1205" fetchPriority="high"/></div></section>

    <Section title="Website Development NZ Built Around Clear Requirements"><p>A website development NZ project should begin with a clear understanding of what the website needs to do. Some businesses need a straightforward service website, while others require account areas, eCommerce features, booking workflows, content-management tools or connections with external platforms.</p><p>We translate business requirements into a practical technical scope. This helps distinguish essential functionality from optional features, identify dependencies early and define the responsibilities of design, content, development and internal stakeholders.</p></Section>
    <Section title="Technical Discovery and Project Planning" tinted><p>Before development begins, Vorevix reviews the current website, required functionality, user journeys, content, integrations and operational needs.</p><p>Discovery may cover:</p><List items={discovery}/></Section>
    <Section title="Front-End Development"><p>Front-end development turns approved designs into working interfaces. It includes the layouts, components and interactions visitors see and use.</p><p>Our website development NZ work may include responsive page structures, navigation, forms, reusable components, content layouts and interface states across common screen sizes. The implementation should preserve the approved information hierarchy while remaining practical to maintain.</p></Section>
    <Section title="Back-End Development and CMS Implementation" tinted><p>Back-end development supports the systems behind the visible interface. Depending on the project, this may include content models, databases, user permissions, forms, business rules, integrations or administration tools.</p><p>A content-management system can help internal teams update pages, articles, products or other structured content without editing code directly. The most suitable approach depends on editing needs, security requirements, integrations, budget and ongoing support.</p></Section>
    <Section title="Custom Functionality and Business Workflows"><p>Some websites need functionality beyond standard templates. This may include calculators, directories, gated content, account areas, application forms, booking workflows or searchable resources.</p><p>For website development NZ projects, we document intended behaviour, data requirements, permissions and dependencies before implementation where possible. Complex application development may require a separate technical engagement.</p></Section>
    <Section title="API and Third-Party Integrations" tinted><p>Websites often need to exchange information with payment providers, customer-relationship platforms, email tools, booking systems, accounting software or shipping services.</p><p>Integration planning should consider available APIs, authentication, data formats, rate limits, error handling and ownership of each external platform.</p><p>Vorevix can coordinate integrations included within the agreed scope, but no integration can be guaranteed to operate indefinitely without monitoring and updates.</p></Section>
    <Section title="eCommerce Website Development"><p>eCommerce development may involve category structures, product variations, inventory rules, customer accounts, cart behaviour, checkout, payments, shipping and order communication.</p><p>Our website development NZ scope may include eCommerce implementation where agreed. Platform-specific tax, payment, shipping and legal settings must be verified for the individual business.</p><p>Related projects may also connect with our <a href="/new-zealand/web-design">New Zealand website design service</a>, <a href="/services/web-design">global web design services</a> and <a href="/services/ui-ux-design-services">UI/UX design services</a>.</p></Section>
    <Section title="Website Redesign and Redevelopment" tinted><p>A redesign focuses primarily on structure, user experience and visual presentation. Redevelopment focuses on the technical implementation needed to support the approved experience and functionality.</p><p>Existing websites may require redevelopment because of outdated code, difficult content management, unreliable integrations, poor responsive behaviour or limitations that prevent future updates.</p><p>We review which content, functionality and data should be retained, rebuilt, migrated or removed. A rebuild can address identified technical issues, but it cannot guarantee traffic, rankings, conversions or growth.</p></Section>
    <Section title="Website Migrations"><p>Migrations may involve moving content, users, products, files, URLs or functionality between platforms or environments.</p><p>A structured migration plan can reduce avoidable problems with missing content, broken links, lost redirects and inconsistent data. Important steps may include inventories, mapping, backups, test migrations, redirect planning and post-launch checks.</p><p>Migration outcomes depend on the quality and accessibility of the source data. Legacy systems may contain incomplete or incompatible information requiring additional review.</p></Section>
    <Section title="Performance-Conscious Development" tinted><p>Website speed is influenced by code, images, fonts, hosting, third-party scripts, content and user devices.</p><p>Performance-conscious development aims to reduce avoidable technical weight and loading delays. Work may include component optimisation, image handling, code review, caching considerations and hosting coordination.</p><p>We do not promise perfect Core Web Vitals scores or identical performance in every environment. Measurements vary according to pages, devices, connections, external services and future content changes.</p></Section>
    <Section title="SEO-Aware Technical Foundations"><p>Development decisions can affect crawlability, page structure, internal linking, redirects, metadata delivery and structured content.</p><p>Our website development NZ process can support SEO-aware implementation through semantic markup, logical page relationships and technically accessible content.</p><p>Technical development alone cannot guarantee rankings. Search visibility also depends on competition, content relevance, authority, demand and ongoing optimisation.</p><p>Businesses requiring deeper search support can explore our <a href="/services/seo-services">complete SEO services</a>.</p></Section>
    <Section title="Accessibility-Aware Implementation" tinted><p>Accessibility-aware development considers semantic markup, keyboard interaction, form labels, focus states and meaningful interface behaviour.</p><p>These practices can support a wider range of users and often improve general usability. The level of testing depends on the project, audience and compliance obligations.</p><p>Vorevix does not claim full WCAG compliance unless specific standards, testing methods and remediation work are included and verified.</p></Section>
    <Section title="Quality Assurance and Testing"><p>Testing helps identify avoidable defects before deployment. Review may include page rendering, forms, navigation, responsive behaviour, browser compatibility, integrations and content-management workflows.</p><p>Testing cannot prove that a website will remain error-free forever. Browsers, devices, plugins, platforms and external services continue to change after launch.</p></Section>
    <section className="wd-section wd-tinted"><div className="wd-section-heading"><h2>Our Website Development Process for New Zealand Teams</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p className="wda-note">Our <a href="/services/web-development-services">complete web development services</a> page explains the wider global methodology and technical capabilities.</p></section>
    <Section title="Remote Collaboration Across New Zealand"><p>Vorevix delivers website development NZ projects through remote meetings, written specifications, shared reviews and milestone-based approvals.</p><p>We can work with founders, marketing teams, designers, technical stakeholders and external providers across New Zealand business hours. Clear communication is especially important when several parties are responsible for content, design, development, hosting or integrations.</p><p>National availability does not imply a New Zealand office, local phone number or New Zealand-based development team. The service is delivered through structured remote collaboration.</p></Section>
    <Section title="Website Development Cost Factors in New Zealand" tinted><p>The cost of website development NZ projects depends on technical scope rather than one standard package.</p><p>Important factors may include:</p><List items={costs}/><p>Vorevix prepares a tailored proposal after reviewing the requirements. We do not publish unsupported NZD pricing, GST statements or fixed timelines.</p></Section>
    <section className="wd-section"><div className="wd-section-heading"><h2>Why Choose Our Website Development NZ Approach?</h2><p>Our website development NZ approach combines technical planning, implementation awareness and practical communication without forcing every organisation into the same platform.</p></div><div className="wd-card-grid">{reasons.map((reason) => <article className="wd-card" key={reason}><Code2 className="wd-card-icon" size={25} aria-hidden="true"/><h3>{reason}</h3></article>)}</div><div className="wda-prose"><p>Connected services include <a href="/new-zealand/web-design">website design</a>, <a href="/services/branding">branding</a>, <a href="/services/seo-services">SEO</a> and <a href="/services/digital-marketing">digital marketing</a>. Review our <a href="/portfolio">selected work</a> or begin a <a href="/contact">project discussion</a>.</p><p>Recommendations remain qualified and do not guarantee outcomes.</p></div></section>
    <section className="wd-section wda-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions About Website Development in New Zealand</h2></div><div className="wda-faq-list">{webDevelopmentNewZealandFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `web-development-nz-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Build a Stronger Technical Foundation</h2><p>A successful website development NZ project should connect business requirements, technical architecture, responsive implementation, integrations, testing and long-term maintenance.</p><p>Vorevix helps New Zealand businesses plan and deliver websites that are practical to manage, adaptable and aligned with wider design and marketing goals.</p><p>Share your current website, required functionality, preferred platform, integration needs and expected timeline. We will review the information and discuss the most suitable next step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Website Development Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
