import { useState } from "react";
import { ArrowRight, ChevronDown, Code2 } from "lucide-react";
import { webDevelopmentAustraliaFaqs } from "../webDevelopmentAustraliaFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";

const services = [
  ["Custom Website Development", "Custom development allows the structure, features and content-management experience to match the needs of the organisation. We can build websites that support unique page types, service journeys, forms, user actions and integrations without depending entirely on rigid templates."],
  ["Business Website Development", "Business websites often need to explain services, build trust, collect enquiries and support marketing campaigns. We develop responsive, manageable websites with clear content structures, reusable components and practical administration tools."],
  ["eCommerce Development", "eCommerce development should support product discovery, catalogue management, payments, order workflows and future growth. We can help plan storefront structure, product data, integrations, customer journeys and the technical requirements behind the buying experience."],
  ["CMS Development", "A content-management system should make regular updates easier without allowing the website to become inconsistent. We can create structured content types, reusable page components and editing controls that help teams manage content more confidently."],
  ["Web Application Development", "Some projects require more than a conventional marketing website. Vorevix can support portals, dashboards, workflow tools, authenticated areas and other browser-based applications where the required functionality is clearly defined."],
  ["API and Third-Party Integrations", "Integrations can connect websites with CRMs, payment systems, marketing platforms, booking tools, analytics systems and internal software. We plan how data should move, where failures need to be handled and which system should remain the source of truth."],
];

const capabilities = [
  ["Frontend Development", "Frontend development turns approved designs into responsive interfaces. This includes layout behaviour, components, forms, interactions, accessibility considerations and performance-aware implementation across relevant devices."],
  ["Backend Development", "Backend development manages content, business logic, data, authentication, integrations and administration. The right architecture depends on project size, expected traffic, security needs and the systems the product must connect with."],
  ["Responsive Implementation", "Layouts are tested and refined across screen sizes so navigation, forms, content order and calls to action remain practical. Responsive development is not only about shrinking desktop layouts; it requires decisions about priority, spacing and interaction."],
  ["Performance Optimisation", "Performance affects usability, conversion and search visibility. We consider asset delivery, image handling, caching, code quality, third-party scripts and page structure during implementation."],
  ["Security Considerations", "Security should be treated as an ongoing responsibility. Depending on the project, this may include secure authentication, dependency management, access controls, form protection, backups and update planning."],
  ["Accessibility Considerations", "Accessible implementation supports users who rely on keyboards, assistive technologies, clear focus states and meaningful structure. We use semantic development practices where they fit the agreed scope."],
];

const process = [
  ["Discovery and Technical Requirements", "We begin by understanding the business goals, users, existing systems, content, integrations and internal responsibilities."],
  ["Architecture and Project Planning", "We define the platform approach, content structure, technical dependencies, integration needs and delivery milestones."],
  ["Development Environment and Component Build", "Development begins in a controlled environment using reusable components and agreed coding conventions."],
  ["Integrations and Content Implementation", "Approved integrations are connected and tested. Content implementation can also be coordinated according to the agreed project scope."],
  ["Quality Assurance and User Acceptance Testing", "Testing covers important browsers, devices, forms, user paths, content states and integrations. The client also receives an agreed opportunity to review the product before launch."],
  ["Deployment and Launch", "Launch planning may include backups, DNS coordination, redirects, analytics, environment configuration and final checks."],
  ["Handover and Ongoing Support", "After launch, we can provide documentation, training, maintenance or a structured handover depending on the agreed scope."],
];

const useCases = [
  ["Growing Service Businesses", "Service businesses may need a website that is easier to update, supports lead generation and connects with marketing systems. A scalable component structure can support new service pages, campaigns and resources over time."],
  ["eCommerce Businesses", "Online stores may require catalogue management, payments, shipping, tax settings, product feeds and operational integrations. Development planning should account for both the customer experience and the internal process behind each order."],
  ["Corporate Organisations", "Corporate websites often involve multiple stakeholders, complex content and formal approval processes. Structured content, permissions and reusable components can help maintain consistency."],
  ["SaaS and Digital Products", "Digital products may need landing pages, customer portals, subscriptions, dashboards or integrations with product systems. Scope and architecture should be based on a realistic product roadmap."],
  ["Organisations Replacing Legacy Platforms", "Legacy platforms can create performance, security and maintenance problems. Redevelopment provides an opportunity to simplify workflows, improve content management and remove unnecessary technical debt."],
];

const reasons = ["development shaped around real requirements", "responsive and maintainable implementation", "clear CMS and content structures", "practical API and integration planning", "performance, security and accessibility considerations", "structured testing and launch preparation", "organised remote project delivery", "clear handover and support options", "honest recommendations without unsupported guarantees"];

function Section({ title, children, tinted = false }) { return <section className={`wd-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div>{children}</section>; }
function Cards({ items, className = "wd-card-grid" }) { return <div className={className}>{items.map(([title, body]) => <article className="wd-card" key={title}><Code2 className="wd-card-icon" size={26} aria-hidden="true"/><h3>{title}</h3><p>{body}</p></article>)}</div>; }

export default function WebDevelopmentAustraliaPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/web-development-services">Web Development</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Australia</span></li></ol></nav>

    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Web Development Australia</span><h1>Web Development Services for Australian Businesses</h1><p>A strong digital product needs more than clean code. It needs a clear structure, dependable performance, secure integrations and a development process that supports the goals of the business behind it. Vorevix provides custom website development, CMS implementation, eCommerce builds, web applications and ongoing technical support for organisations that need reliable digital platforms.</p><p>Our approach to web development Australia starts with the problem the product needs to solve. We review the audience, content, workflows, integrations, performance requirements and future growth plans before development begins. The result is a website or application that is easier to manage, easier to scale and better prepared for long-term use.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Development Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual"><img src="/assets/vorevix-laptop.png" alt="Vorevix web development project shown on a laptop" width="1080" height="1080" fetchPriority="high"/></div></section>

    <Section title="Web Development Australia Built Around Real Business Requirements"><div className="wda-prose"><p>A development project should not begin with a platform choice or a list of features. It should begin with a clear understanding of what users need to do, what the organisation needs to manage and which technical decisions will support both.</p><p>Our web development Australia process connects business priorities with practical technical planning. That may involve replacing an outdated website, developing a new digital platform, integrating third-party systems, improving site performance or creating a more flexible content-management experience.</p><p>Every web development Australia engagement is scoped around useful outcomes, responsible technology choices and the people who will operate the finished platform.</p><p>We focus on solutions that are understandable, maintainable and suitable for the scope of the project. Technology should support the business instead of becoming an unnecessary source of complexity.</p></div></Section>

    <Section title="Web Development Services for Australian Businesses" tinted><div className="wda-prose"><p>Our web development Australia service can support standard business websites, content-rich platforms, online stores and more advanced web applications. The final scope is shaped around the project rather than forcing every client into the same technology or delivery model.</p></div><Cards items={services}/><div className="wda-prose"><h3>Website Redevelopment and Migration</h3><p>An existing website may need a full rebuild because of poor performance, outdated technology, difficult content management or limited scalability. We assess what should be retained, what needs to change and how important content, URLs and data should be migrated.</p><p>Where search visibility matters, redevelopment should also include redirect planning and coordination with <a href="/services/seo-services">SEO requirements</a>.</p></div></Section>

    <Section title="Frontend and Backend Development Working Together"><div className="wda-prose"><p>Effective web development Australia requires both the visible user experience and the underlying system to work as one product.</p></div><Cards items={capabilities}/></Section>

    <Section title="Our Web Development Process for Australian Clients" tinted><div className="wda-prose"><p>A clear process helps reduce delays, unclear approvals and technical surprises. Our web development Australia projects use defined stages so the client understands what is being planned, built, reviewed and approved.</p><p>A practical web development Australia roadmap also gives stakeholders clear review points and helps teams prepare content, access and feedback at the right time.</p></div><Cards items={process} className="wd-process-grid"/><div className="wda-prose"><p>Learn more about our complete <a href="/services/web-development-services">global web development services</a> and the capabilities available for projects without a regional focus.</p></div></Section>

    <Section title="Remote Collaboration That Works Across Australia"><div className="wda-prose"><p>For web development Australia projects, Vorevix works remotely through organised communication, documented decisions and agreed milestones. Remote delivery should still provide clarity around responsibilities, progress and review points.</p><p>Meetings can be scheduled around practical overlap with Australian time zones, while written updates help keep the project moving between calls. Feedback is collected in a structured way so development decisions are not lost across separate messages.</p><p>Our web development Australia service is available to businesses across the country without implying a physical Australian office. Reliable communication, visible progress and clear ownership are more important than creating the appearance of local presence.</p></div></Section>

    <Section title="Development for Different Business Needs" tinted><Cards items={useCases}/></Section>

    <Section title="Why Work With Vorevix"><div className="wda-prose"><p>Our development approach combines business understanding, design awareness and technical planning. We do not recommend complexity simply to make a project appear more advanced.</p><p>Clients choose Vorevix for:</p><ul className="wd-checklist">{reasons.map(reason => <li key={reason}>{reason}</li>)}</ul><p>We position web development Australia as part of a wider digital system. Development should connect with web design, UI/UX, SEO, branding, analytics and marketing rather than operating as an isolated technical task.</p></div></Section>

    <Section title="How Web Development Australia Connects to Your Wider Digital Strategy" tinted><div className="wda-prose"><p>A successful digital platform depends on more than development alone. Web design shapes the visual experience, UI/UX improves journeys, SEO supports discoverability and digital marketing helps attract and convert the right audience.</p><p>Depending on the project, Vorevix can connect development with <a href="/services/web-development-services">global web development services</a>, <a href="/services/web-design">web design services</a>, <a href="/services/ui-ux-design-services">UI/UX design services</a>, <a href="/services/seo-services">SEO services</a> and <a href="/services/digital-marketing">digital marketing services</a>. You can also review our <a href="/portfolio">portfolio work</a> or send us your <a href="/contact">project enquiries</a>.</p></div></Section>

    <Section title="Frequently Asked Questions About Web Development in Australia"><div className="wda-faq-list">{webDevelopmentAustraliaFaqs.map((faq, index) => { const open = openFaq === index; const id = `wda-faq-${index}`; return <article className="wda-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{faq.question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}>{faq.answer.map(p => <p key={p}>{p}</p>)}</div></article>; })}</div></Section>

    <section className="wd-final-cta"><h2>Ready to Build a More Reliable Digital Platform?</h2><p>Your website or application should support the way your organisation works, not create more operational friction. Vorevix combines technical planning, responsive development and organised remote delivery to build digital platforms that are practical to manage and prepared for growth.</p><p>For your web development Australia project, share your current website or product, required functionality, integrations and preferred timeframe. We will review the information and discuss the most suitable next step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Development Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
