import { useState } from "react";
import { ArrowRight, ChevronDown, Code2 } from "lucide-react";
import { webDevelopmentAustraliaFaqs } from "../webDevelopmentAustraliaFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";

const services = [
  { title: "Custom Website Development", paragraphs: ["Custom website development is suitable when your business requires a website built around specific goals, user journeys and functionality.", "Instead of adapting your requirements to a restrictive template, we plan the website structure and development approach around the way your business needs to communicate and operate.", "Custom website development may include:"], items: ["Tailored page structures", "Responsive front-end development", "Custom functionality", "Reusable website components", "Lead-generation forms", "Service or product directories", "Customer account areas", "Content filtering", "Interactive website elements", "Third-party integrations", "Conversion tracking", "Content management tools"], closing: ["Our goal is to create a website that can support current requirements without making future improvements unnecessarily difficult."] },
  { title: "Business Website Development", paragraphs: ["Business websites need to establish credibility, explain services clearly and help potential customers move towards an enquiry, consultation or purchase.", "We develop websites for service businesses, professional organisations, B2B companies and growing brands that need a stronger online platform.", "A business website project may include:"], items: ["Service-page development", "Lead-generation journeys", "Contact and enquiry forms", "Case-study sections", "Team and company pages", "Location or market pages", "Resource sections", "CRM integrations", "Analytics and conversion tracking", "Content management functionality"], closing: ["Our web development Australia approach focuses on creating a practical connection between your content, user experience and commercial goals."] },
  { title: "Ecommerce Website Development", paragraphs: ["An ecommerce website must make it easy for customers to discover products, understand their options and complete a purchase.", "It also needs to support the operational requirements behind the customer experience.", "Our ecommerce development services may include:"], items: ["Product catalogue development", "Product filtering and search", "Shopping-cart functionality", "Secure checkout journeys", "Payment-gateway integrations", "Shipping configuration", "Promotional functionality", "Customer account features", "Inventory integrations", "Order-management integrations", "Email and marketing integrations", "Conversion tracking", "Responsive ecommerce development"], closing: ["We consider both the customer-facing experience and the systems required to manage products, orders, payments and ongoing store content.", "The right ecommerce platform depends on your product catalogue, operational workflow, integration requirements and plans for growth."] },
  { title: "Website Redesign and Redevelopment", paragraphs: ["A redesign changes how a website looks and feels. Redevelopment addresses the technical platform, code, functionality or content-management limitations behind it.", "Some websites require both.", "A redesign and redevelopment project may be appropriate when:"], items: ["The website is visually outdated", "Mobile usability is poor", "Pages load slowly", "Content is difficult to manage", "The current platform limits functionality", "The site structure has become confusing", "Integrations are unreliable", "Conversion journeys are unclear", "Previous development work is difficult to maintain", "The website no longer supports business priorities"], closing: ["We review the current platform before recommending whether it should be improved, partially rebuilt or replaced.", "Where a website already receives search traffic, migration planning should also consider URLs, redirects, content structure and existing search visibility."] },
  { title: "Content Management System Development", paragraphs: ["A content management system should allow authorised team members to update appropriate website content without creating unnecessary technical risk.", "CMS development may include:"], items: ["Page and section management", "Reusable content blocks", "Blog or resource publishing", "Product or service management", "Team profiles", "Case studies", "Location content", "Media management", "User permissions", "Custom administrative fields", "Content approval workflows"], closing: ["The CMS should match the way your team manages content. It should not expose every technical setting or make simple updates unnecessarily difficult.", "We select and configure content-management functionality according to the project rather than recommending the same CMS for every business."] },
  { title: "API and Third-Party Integrations", paragraphs: ["A website often needs to connect with other systems used by the business.", "These connections may reduce manual work, improve data consistency or create a better customer experience.", "Integration requirements may include:"], items: ["Customer relationship management systems", "Booking platforms", "Payment gateways", "Email marketing platforms", "Inventory systems", "Accounting tools", "Analytics platforms", "Customer support systems", "Mapping services", "Authentication providers", "Operational databases", "Custom business software"], closing: ["We review the available documentation, data requirements and technical limitations before implementing an integration.", "Where a third-party platform controls part of the process, the reliability and limitations of that system must also be considered."] },
  { title: "Website Maintenance and Support", paragraphs: ["A website continues to require attention after launch.", "Software updates, browser changes, security risks, content requirements and business priorities can all affect how the website performs over time.", "Ongoing support may include:"], items: ["Software and dependency updates", "Technical troubleshooting", "Security monitoring", "Backup checks", "Performance improvements", "Content updates", "New page development", "Form and integration testing", "Browser compatibility checks", "Small functionality improvements", "Technical guidance", "Website health reviews"], closing: ["Maintenance requirements depend on the platform, complexity and level of business reliance on the website."] },
];

const applications = [
  { title: "Web Application Development", paragraphs: ["A web application is designed around tasks and interactions rather than content alone.", "Web application projects may include:"], items: ["Customer portals", "Internal dashboards", "Booking systems", "Reporting tools", "Membership platforms", "Account-management systems", "Workflow applications", "Document-management tools", "Multi-user platforms", "Custom calculators", "Data-entry systems", "Operational tools"], closing: ["Development may involve user roles, permissions, databases, integrations, authentication and custom business logic.", "Before development begins, the required workflows and user types need to be clearly defined."] },
  { title: "SaaS Product Development", paragraphs: ["SaaS development requires both product and technical planning.", "The objective is not simply to build a set of screens. The product needs to support user needs, administration, subscriptions, data handling and future improvements.", "A SaaS project may include:"], items: ["Product discovery", "MVP planning", "User-role definition", "Application architecture", "Account creation and authentication", "Subscription functionality", "Dashboard development", "Payment integrations", "Administrative tools", "Notification systems", "Analytics", "Third-party integrations", "Ongoing product development"], closing: ["The initial scope should focus on the most important user problems and product assumptions rather than attempting to build every possible feature at once."] },
];

const commonRequirements = [
  ["Replacing an Outdated Website", "An outdated website can affect trust, usability and the way a business presents its services. A replacement project may involve new content structures, improved navigation, responsive development, updated technology and clearer conversion journeys."],
  ["Improving Mobile Performance", "Customers may visit a website through phones, tablets and different screen sizes. Responsive development should consider more than whether a page technically fits on a smaller screen. Content order, buttons, forms, navigation and interactive elements must also remain usable."],
  ["Connecting Business Systems", "Manual data entry between a website, CRM, booking system or ecommerce platform can create delays and errors. Suitable integrations may help information move between systems more efficiently."],
  ["Building an Ecommerce Platform", "An ecommerce project may begin with a new store, a migration from another platform or improvements to an existing customer journey. The development approach should consider products, operations, fulfilment, payments, customer communication and reporting."],
  ["Simplifying Content Management", "Businesses should be able to manage approved website content without relying on a developer for every small change. The CMS should provide useful flexibility without making the website inconsistent or difficult to maintain."],
  ["Rebuilding Poor Previous Work", "Some businesses inherit websites with unreliable code, unclear ownership, missing documentation or technical limitations. We first assess the existing system to determine whether the most practical option is repair, refactoring, partial redevelopment or a complete rebuild."],
];

const process = [
  { title: "1. Discovery and Requirements", paragraphs: ["We begin by understanding:"], items: ["Your business and objectives", "Target users", "Current website or platform", "Required functionality", "Content requirements", "Integrations", "Internal workflows", "Technical constraints", "Project priorities", "Long-term expectations"], closing: ["This stage helps distinguish essential requirements from features that may be useful later."] },
  { title: "2. Scope and Technical Planning", paragraphs: ["We translate the requirements into a practical project scope.", "Planning may include:"], items: ["Website architecture", "Feature definitions", "CMS requirements", "Integration requirements", "Technology recommendations", "User roles", "Data requirements", "Delivery stages", "Dependencies", "Technical risks", "Testing requirements"], closing: ["A clear scope creates a shared understanding of what will be delivered."] },
  { title: "3. UX and Interface Planning", paragraphs: ["Before development, the page structure and main user journeys should be clear.", "UX and interface planning may include:"], items: ["Sitemap planning", "User-flow development", "Wireframes", "Content hierarchy", "Navigation planning", "Mobile behaviour", "Form journeys", "Conversion points", "Interface states"], closing: [] },
  { title: "4. Development", paragraphs: ["Development turns the approved structure and designs into a functional digital product.", "Depending on the scope, this stage may include:"], items: ["Responsive front-end development", "Reusable components", "CMS configuration", "Backend functionality", "Database development", "Ecommerce features", "API integrations", "Form development", "User accounts", "Analytics setup", "Technical SEO foundations"], closing: ["Development is reviewed throughout the project rather than being hidden until the final stage."] },
  { title: "5. Testing and Quality Assurance", paragraphs: ["Testing helps identify problems before launch.", "Quality assurance may include:"], items: ["Desktop and mobile testing", "Browser compatibility", "Navigation checks", "Form testing", "Integration testing", "Content review", "CMS testing", "Accessibility checks", "Performance review", "Security checks", "User-role testing", "Error-state testing"], closing: ["The exact testing process depends on the project complexity."] },
  { title: "6. Launch and Migration", paragraphs: ["A launch may involve more than publishing files to a live server.", "Launch activities may include:"], items: ["Production deployment", "Domain configuration", "Redirect implementation", "Analytics checks", "Search Console checks", "Form validation", "Tracking validation", "Final content review", "Backup confirmation", "Post-launch monitoring"], closing: ["Existing websites may also require content, database or URL migration."] },
  { title: "7. Support and Improvement", paragraphs: ["After launch, we can support updates, fixes and future improvements.", "This may include:"], items: ["Performance monitoring", "Technical maintenance", "New page development", "Integration updates", "Conversion improvements", "Feature development", "Content support", "Ongoing testing"], closing: ["A website should be able to evolve as the business changes."] },
];

const foundations = [
  { title: "Website Performance", paragraphs: ["Website speed can affect usability, conversion and search performance.", "Development decisions may consider:"], items: ["Image optimisation", "Responsive media", "Efficient code", "Asset loading", "Caching", "Font delivery", "Third-party scripts", "Server response", "Component performance", "Core Web Vitals"], closing: ["Performance also depends on hosting, content, integrations and external services."] },
  { title: "Technical SEO Foundations", paragraphs: ["Development does not replace an SEO strategy, but it should provide a suitable technical foundation.", "This may include:"], items: ["Semantic HTML", "Crawlable navigation", "Logical heading structure", "Metadata support", "Canonical-tag support", "Structured content", "Sitemap compatibility", "Redirect planning", "Mobile usability", "Page-speed considerations", "Analytics and tracking support"], closing: [] },
  { title: "Accessibility", paragraphs: ["Accessible development aims to make websites more usable for people with different needs and methods of interaction.", "Accessibility considerations may include:"], items: ["Keyboard navigation", "Semantic page structure", "Form labels", "Colour contrast", "Focus states", "Alternative text handling", "Clear error messages", "Screen-reader support", "Responsive text", "Accessible interactive elements"], closing: ["The required level of accessibility should be discussed according to the project, audience and compliance responsibilities."] },
  { title: "Security and Reliability", paragraphs: ["Security needs vary according to the type of website, data being handled and integrations being used.", "Development considerations may include:"], items: ["Secure form handling", "User authentication", "Access permissions", "Software updates", "Dependency management", "Backup planning", "Error monitoring", "Secure integrations", "Data validation", "Recovery planning"], closing: ["No website can be described as completely risk-free, but sensible technical and operational controls can reduce avoidable exposure."] },
];

const technologies = [
  ["Front-End Development", "Front-end development may use modern JavaScript, responsive CSS and component-based interfaces to create consistent experiences across different devices."],
  ["CMS and Website Platforms", "The selected CMS should match the content structure, administrator requirements and future publishing needs. We only recommend platforms that are suitable for the project and can be maintained responsibly."],
  ["Ecommerce Platforms", "Ecommerce technology should be selected according to the product catalogue, checkout needs, operational workflow and integration requirements."],
  ["Backend Development and Integrations", "More advanced projects may require APIs, databases, authentication, server-side functionality and custom business logic."],
  ["Hosting and Deployment", "Hosting decisions should consider reliability, security, performance, deployment workflow and the level of support required."],
];

const businessModels = [
  ["Service Businesses", "Service businesses may require clear service pages, enquiry journeys, booking functionality, case studies and CRM integrations."], ["Ecommerce Businesses", "Ecommerce businesses need reliable product management, checkout experiences, payment systems and operational integrations."], ["B2B Companies", "B2B websites often need to explain complex services, support longer buying journeys and generate qualified enquiries."], ["SaaS and Technology Companies", "Technology companies may require product websites, dashboards, customer portals, web applications or ongoing product development."], ["Startups and Growing Businesses", "Growing businesses may need an initial platform that can support new content, services, integrations and future functionality."], ["Professional Services", "Professional-service websites need clear positioning, credibility, team information, useful resources and straightforward contact journeys."], ["Education and Training Providers", "Education and training platforms may require course information, registrations, learning integrations, member areas or content-management workflows."], ["Multi-Location Businesses", "Multi-location businesses may require structured location pages, consistent service content, local enquiry routing and centralised management."],
];

const why = [
  ["Strategy Before Development", "We begin with the business need, users and required outcomes before recommending a platform or technical approach."], ["Custom Project Scope", "Every project has different requirements. We do not force each business into the same website package or list of features."], ["Connected Design and Development", <>Design and development decisions affect each other. Where required, website development can be combined with our <a href="/services/web-design">web design services</a> and <a href="/services/ui-ux-design-services">UI/UX design services</a>.</>], ["Search and Performance Awareness", "We consider page structure, responsive behaviour, performance and technical SEO foundations during development. This helps reduce the risk of important technical requirements being treated as an afterthought."], ["Clear Communication", "Projects are managed through documented requirements, delivery stages and review points. Changes that affect scope, cost or timelines should be identified clearly."], ["Long-Term Support", "A website may need updates, fixes and improvements after launch. Ongoing support can be included according to the platform and business requirements."], ["Broader Digital Capability", <>Where a project requires wider support, development can also connect with our <a href="/services/branding">branding services</a>, <a href="/services/seo-services">SEO services</a> and <a href="/services/digital-marketing">digital marketing services</a>.</>],
];

function Checklist({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, intro, children, tinted = false }) { return <section className={`wd-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro && <p>{intro}</p>}</div>{children}</section>; }
function RichCard({ item }) { return <article className="wd-card"><Code2 className="wd-card-icon" aria-hidden="true" /><h3>{item.title}</h3>{item.paragraphs.map((p) => <p key={p}>{p}</p>)}<Checklist items={item.items} />{item.closing.map((p) => <p key={p}>{p}</p>)}{item.title === "3. UX and Interface Planning" && <p>Projects requiring dedicated research and interface work can also use our <a href="/services/ui-ux-design-services">UI/UX design services</a>.</p>}{item.title === "Technical SEO Foundations" && <p>Businesses requiring keyword research, content optimisation and ongoing organic growth can use our <a href="/services/seo-services">SEO services</a>.</p>}{item.title === "Accessibility" && <p>We use the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/" target="_blank" rel="noopener noreferrer">Web Content Accessibility Guidelines</a> as an important reference when planning accessible website experiences.</p>}</article>; }
function SimpleCards({ items }) { return <div className="wd-card-grid">{items.map(([title, body]) => <article className="wd-card" key={title}><Code2 className="wd-card-icon" aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>)}</div>; }

export default function WebDevelopmentAustraliaPage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Web Development Australia</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><h1>Web Development Services for Businesses in Australia</h1><p>Vorevix provides web development Australia services for businesses that need more than a basic online presence. We plan, design, develop and support custom websites, ecommerce platforms and web applications around real business requirements.</p><p>Whether you are replacing an outdated website, launching an online store, improving an existing digital platform or building a custom web application, our approach connects user experience, technical performance and long-term maintainability.</p><p>We work remotely with businesses across Australia through clear communication, documented requirements, scheduled reviews and defined delivery milestones.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Web Project <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">View Our Work</a></div><ul className="wda-trust"><li>Custom development around business requirements</li><li>Responsive, accessible and SEO-ready builds</li><li>Ecommerce, CMS and web application capability</li><li>Ongoing maintenance and development support</li></ul></div><div className="wd-hero-visual"><img src="/service-web.png" alt="Web development services for businesses in Australia by Vorevix" width="1183" height="1329" fetchPriority="high" /></div></section>

    <Section title="Web Development for Australian Businesses That Need More Than a Basic Website"><div className="wda-prose"><p>A business website should do more than display information. It should communicate your value clearly, make it easy for visitors to take action and support the way your business operates.</p><p>Many businesses reach a point where their existing website can no longer support their growth. The platform may be slow, difficult to update, poorly optimised for mobile devices or disconnected from important business systems.</p><p>Other businesses need functionality that cannot be delivered through a basic website builder or a generic template.</p><p>Common challenges include:</p><Checklist items={["An outdated website that no longer reflects the business", "Slow loading times and poor mobile performance", "Limited control over website content", "Difficult or confusing customer journeys", "Ecommerce limitations", "Manual processes that should be automated", "CRM, booking or payment systems that are not connected", "Technical problems caused by previous development work", "A platform that cannot support future services or products", "Limited access to reliable technical support"]} /><p>Vorevix approaches web development Australia projects by first understanding the business problem. We then recommend a suitable development approach instead of forcing every project into the same platform, package or technical solution.</p><p>For projects without a geographic focus, explore our <a href="/services/web-development-services">general web development services</a>.</p></div></Section>
    <Section title="Web Development Services for Australian Businesses" intro="Our web development services can support a new project, an existing website or a more advanced digital product."><p className="wda-note">The final scope depends on your business model, users, technical requirements, available content and long-term plans.</p><div className="wd-card-grid">{services.map((item) => <RichCard item={item} key={item.title} />)}</div></Section>
    <Section title="Web Applications and SaaS Development" intro="Some business requirements cannot be delivered through a traditional website. Vorevix can also support the planning and development of web applications and SaaS products where users need to log in, manage information, complete workflows or interact with custom functionality." tinted><div className="wd-card-grid">{applications.map((item) => <RichCard item={item} key={item.title} />)}</div></Section>
    <Section title="Common Web Development Requirements Across Australia" intro="Businesses approach Vorevix with different goals, but many projects begin with similar problems."><SimpleCards items={commonRequirements} /></Section>
    <Section title="How We Deliver Web Development Projects" intro="A clear process helps control scope, reduce misunderstandings and identify technical risks before they become expensive problems." tinted><div className="wd-process-grid">{process.map((item) => <RichCard item={item} key={item.title} />)}</div></Section>
    <Section title="Built for Performance, Search Visibility, Accessibility and Security" intro="Good development should consider how a website performs for users, search engines and the people responsible for managing it."><div className="wd-card-grid">{foundations.map((item) => <RichCard item={item} key={item.title} />)}</div></Section>
    <Section title="Technologies Selected Around the Project" intro="Technology should support the project rather than become the starting point for every decision." tinted><div className="wda-prose"><p>We consider factors such as:</p><Checklist items={["Required functionality", "Content-management needs", "Scalability", "Integration requirements", "Available budget", "Internal technical capability", "Maintenance requirements", "Security", "Performance", "Future development plans"]} /></div><SimpleCards items={technologies} /></Section>
    <Section title="Web Development for Different Australian Business Models" intro="Our web development Australia services can be adapted to different organisations and customer journeys."><SimpleCards items={businessModels} /><p className="wda-note">We do not claim specific industry experience unless it can be supported by verified project work. The final approach is based on the actual requirements of each organisation.</p></Section>
    <Section title="Web Development Support Across Australia" tinted><div className="wda-prose"><p>Vorevix works remotely with businesses across Australia, including teams in Sydney, Melbourne, Brisbane, Perth, Adelaide, Canberra, the Gold Coast, Hobart and other locations.</p><p>Our remote process is based on:</p><Checklist items={["Clear project communication", "Scheduled online meetings", "Documented requirements", "Defined responsibilities", "Shared project milestones", "Review and approval stages", "Written change management", "Accessible project records"]} /><p>Remote delivery allows the project to be managed without claiming a local office or physical presence where one does not exist.</p><p>The objective is to provide a reliable working process regardless of the client’s location.</p></div></Section>
    <Section title="What Your Web Development Project May Include"><div className="wda-prose"><p>The final deliverables depend on the agreed scope.</p><p>A project may include:</p><Checklist items={["Discovery sessions", "Requirements documentation", "Technical planning", "Sitemap development", "User-flow planning", "UX input", "Responsive website development", "CMS configuration", "Ecommerce functionality", "Web application features", "API integrations", "Lead-generation forms", "Analytics and conversion tracking", "Browser and device testing", "Accessibility checks", "Performance optimisation", "Content migration", "Redirect implementation", "Launch support", "Technical documentation", "Administrator guidance", "Maintenance options"]} /><p>All included work should be defined before development begins.</p></div></Section>
    <Section title="Why Choose Vorevix for Web Development in Australia" tinted><SimpleCards items={why} /><div className="wda-prose"><p>Learn more <a href="/about">about Vorevix</a> and our approach to digital projects.</p></div></Section>
    <Section title="Selected Website and Web Development Work"><div className="wda-prose"><p>Explore selected projects completed by Vorevix across branding, user experience, website design and development.</p><p>Each project should present verified information about the business problem, scope and delivered solution.</p><p>Traffic, revenue, conversion or performance results should only be published when accurate data and permission are available.</p><a className="wd-text-link" href="/portfolio">View Our Portfolio <ArrowRight size={18} aria-hidden="true" /></a></div></Section>
    <Section title="How Web Development Pricing Is Determined" tinted><div className="wda-prose"><p>Web development pricing in Australia varies according to the size, complexity and technical requirements of the project.</p><p>Important pricing factors include:</p><Checklist items={["Number of pages or templates", "UX and design requirements", "Custom functionality", "Ecommerce requirements", "CMS configuration", "Web application features", "User accounts and permissions", "API integrations", "Content migration", "Data migration", "Accessibility requirements", "Performance requirements", "Testing complexity", "Technical documentation", "Training requirements", "Hosting and deployment", "Ongoing maintenance"]} /><p>A smaller business website and a custom web application require very different levels of planning, development and testing.</p><p>Vorevix prepares a tailored proposal after reviewing the business goals, required functionality, technical environment and available assets.</p><p>Advertising, hosting, paid software, third-party subscriptions and external platform charges should be identified separately where applicable.</p><a className="wd-text-link" href="/contact">Request a Project Estimate <ArrowRight size={18} aria-hidden="true" /></a></div></Section>
    <Section title="Web Development Australia FAQs"><div className="wda-faq-list">{webDevelopmentAustraliaFaqs.map((faq, index) => { const open = openFaq === index; const id = `wda-faq-${index}`; return <article className="wda-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{faq.question}<ChevronDown aria-hidden="true" /></button></h3><div id={id} hidden={!open}>{faq.answer.map((p) => <p key={p}>{p}</p>)}</div></article>; })}</div></Section>
    <section className="wd-final-cta"><h2>Plan Your Web Development Project in Australia</h2><p>Tell us what you need to build, improve or replace.</p><p>Vorevix will review your goals, users, technical requirements and current website before recommending a practical development approach.</p><p>Whether the project involves a business website, ecommerce platform, custom integration or web application, our web development Australia services can be structured around your priorities and long-term plans.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Web Project <ArrowRight size={18} aria-hidden="true" /></a><a href="/portfolio">Explore Our Work</a></div></section>
  </main>;
}
