import { useState } from "react";
import { ArrowRight, ChevronDown, LayoutTemplate } from "lucide-react";
import { webDesignAustraliaFaqs } from "../webDesignAustraliaFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";

const services = [
  { title: "Custom Website Design", paragraphs: ["Custom website design is suitable when the website needs to reflect specific business goals, brand requirements and customer journeys.", "Rather than adjusting your business to fit a restrictive theme, we create a visual and structural direction around the actual project requirements.", "Custom website design may include:"], items: ["Custom page layouts", "Visual direction", "Content hierarchy", "Navigation design", "Responsive layouts", "Service and product page templates", "Calls to action", "Form interfaces", "Reusable content sections", "Custom components", "Mobile interaction patterns", "Developer-ready design specifications"], closing: ["The objective is to create a website that feels specific to the business and remains practical to develop and maintain."] },
  { title: "Business Website Design", paragraphs: ["Business websites need to explain services clearly, build trust and help potential customers make contact.", "We design websites for service businesses, B2B companies, professional organisations and growing brands that need a stronger digital presence.", "A business website design project may include:"], items: ["Homepage design", "Service page templates", "About and team pages", "Case study layouts", "Lead-generation forms", "Resource or blog sections", "Contact journeys", "Location page templates", "Calls to action", "Trust elements", "Responsive mobile layouts"], closing: ["Our web design Australia process connects the website’s visual presentation with the information customers need before making an enquiry."] },
  { title: "Ecommerce Website Design", paragraphs: ["Ecommerce design should help customers discover products, compare options and complete purchases with minimal unnecessary friction.", "The design also needs to work with the technical and operational requirements behind the store.", "Ecommerce website design may include:"], items: ["Homepage and campaign layouts", "Product category pages", "Product detail pages", "Search and filtering interfaces", "Cart design", "Checkout journeys", "Customer account areas", "Mobile shopping interfaces", "Promotional sections", "Trust and delivery information", "Product recommendations", "Email sign-up journeys", "Empty and error states"], closing: ["A good ecommerce experience must balance visual presentation with product information, usability and checkout clarity."] },
  { title: "Website Redesign", paragraphs: ["A website redesign may be appropriate when the current website no longer reflects the business or creates difficulties for users.", "Common redesign triggers include:"], items: ["Outdated visual design", "Weak mobile layouts", "Confusing navigation", "Inconsistent branding", "Poor content hierarchy", "Low-quality page templates", "Difficult conversion journeys", "New services or products", "Changes in business positioning", "Technical redevelopment requirements"], closing: ["Before recommending a redesign, we review what already works and what needs improvement.", "A redesign does not always require changing every visual element. The most useful approach may involve improving the structure, messaging, navigation and page system while preserving recognisable brand elements."] },
  { title: "Landing Page Design", paragraphs: ["Landing pages are designed around a focused campaign, service, product or conversion goal.", "They may support paid advertising, service campaigns, product launches, lead magnets, event registrations, consultation bookings, promotional offers, email campaigns and market-specific services.", "Landing page design may consider:"], items: ["Message alignment", "Headline clarity", "Benefit structure", "Trust elements", "Form length", "CTA placement", "Mobile usability", "Visual emphasis", "Reduced navigation", "Conversion tracking requirements"], closing: ["A landing page should remain focused without removing information users genuinely need."] },
  { title: "Responsive Website Design", paragraphs: ["Responsive design helps a website adapt to phones, tablets, laptops and larger screens.", "This may involve:"], items: ["Flexible grids", "Responsive typography", "Mobile navigation", "Touch-friendly buttons", "Adaptive image placement", "Reordered content", "Responsive tables", "Mobile forms", "Scalable spacing", "Device-specific interaction considerations"], closing: ["The goal is not to make every screen look identical. The goal is to maintain clarity and usability across different devices."] },
  { title: "UI/UX Design", paragraphs: ["More complex websites and digital products may require dedicated user experience and interface design.", "This can include:"], items: ["User flows", "Information architecture", "Wireframes", "Interactive prototypes", "Interface states", "Form journeys", "Dashboards", "Portal interfaces", "Customer accounts", "Usability improvements"], closing: [] },
  { title: "Design Systems and Reusable Components", paragraphs: ["A design system provides a consistent set of interface rules and reusable components.", "It may define:"], items: ["Typography", "Colours", "Buttons", "Forms", "Cards", "Navigation", "Spacing", "Icons", "Alerts", "Tables", "Modal windows", "Content blocks", "Responsive behaviour"], closing: ["Reusable components can improve consistency and make future page development more efficient."] },
];

const benefits = [["Clearer Communication", "Design helps organise what the business provides, who it serves, why the offer is relevant, where more information is available and what action visitors should take."], ["Stronger Trust and Credibility", "Consistent visual design, clear page structures and reliable interactions can help a business appear more organised and credible."], ["Better Mobile Usability", "Mobile design should keep navigation, buttons, forms, content order and interactive elements usable on smaller screens."], ["More Effective User Journeys", "Good web design reduces unnecessary choices and keeps important actions visible."], ["Greater Content Flexibility", "A structured design system can support new pages, campaigns, services and content without making the website feel inconsistent."], ["Better Alignment Between Brand and Website", <>The website should reflect the wider brand. Where deeper work is required, it can be combined with our <a href="/services/branding">branding services</a>.</>]];
const goals = [["Service Websites", "Service websites need clear offers, useful supporting information and simple enquiry journeys."], ["Ecommerce Websites", "Ecommerce websites need product discovery, comparison, trust and checkout usability."], ["B2B Websites", "B2B websites often need to explain complex services and support longer decision-making journeys."], ["SaaS and Product Websites", "SaaS websites need to explain product value, features, use cases and onboarding paths."], ["Portfolio Websites", "Portfolio websites need to present work clearly without allowing visual presentation to make navigation confusing."], ["Multi-Location Websites", "Multi-location websites may require reusable page systems, location navigation and locally relevant calls to action."], ["Campaign Websites", "Campaign websites may focus on a specific launch, event, service or audience."], ["Membership and Portal Interfaces", "Membership or portal designs may require accounts, dashboards, content libraries and task-based workflows."]];
const process = [
  { title: "1. Discovery", items: ["The business", "Target audience", "Website goals", "Existing website", "Competitors", "Available content", "Brand assets", "Required pages", "Functionality", "Development constraints", "Project priorities"], closing: "Discovery helps establish what the website must communicate and support." },
  { title: "2. Website Strategy", items: ["Page goals", "Sitemap", "User journeys", "Conversion paths", "Content priorities", "Feature requirements", "Key trust elements", "Navigation structure", "Market or audience considerations"], closing: "This creates a foundation before visual design begins." },
  { title: "3. Content Structure", items: ["Heading hierarchy", "Section planning", "CTA placement", "Content gaps", "Message priorities", "Proof requirements", "Internal linking opportunities"], closing: "Content structure determines what information belongs on each page and how sections should be ordered." },
  { title: "4. Wireframes", items: ["Navigation", "Content placement", "Section order", "Forms", "Calls to action", "Image areas", "Mobile behaviour", "Interactive elements"], closing: "Wireframes allow structural issues to be addressed before more time is invested in visual design." },
  { title: "5. Visual Design", items: ["Typography", "Colour", "Imagery", "Cards", "Buttons", "Forms", "Navigation", "Desktop layouts", "Mobile layouts", "Interactive states", "Reusable components"], closing: "The visual design stage applies brand and interface decisions." },
  { title: "6. Design Review and Refinement", items: ["Message clarity", "User journeys", "Visual consistency", "Brand alignment", "Responsive behaviour", "Usability", "Development practicality"], closing: "The number and type of revisions should be defined in the project scope." },
  { title: "7. Development Handover or Build", items: ["Design specifications", "Component definitions", "Responsive layouts", "Exported assets", "Interaction notes", "Content references", "Developer collaboration"], closing: "Approved designs can be prepared for development or continued through Vorevix development." },
];
const models = [["Small Businesses", "A clear, professional website that explains services and creates simple enquiry paths."], ["Professional Services", "Strong credibility, clear expertise, team information and useful resources."], ["Ecommerce Brands", "Product discovery, mobile shopping and conversion-focused checkout journeys."], ["B2B Companies", "Detailed service information, case studies and longer decision-making journeys."], ["SaaS and Technology Businesses", "Product pages, feature explanations, pricing interfaces and onboarding journeys."], ["Startups", "A flexible first website that can evolve with the product and business model."], ["Education and Training Providers", "Course information, registrations, resources and member journeys."], ["Multi-Location Businesses", "Repeatable location templates and consistent local enquiry paths."], ["Not-for-Profit Organisations", "Accessible information, donation journeys, resources and clear stakeholder communication."]];
const why = [["Strategy Before Visual Design", "We begin with the business goals, audience and content before deciding how the website should look."], ["Custom Design Direction", "Projects are not forced into the same visual template or package."], ["Connected Branding and UX", <>Website design can be combined with <a href="/services/branding">branding services</a> and <a href="/services/ui-ux-design-services">UI/UX design services</a>.</>], ["Design and Development Collaboration", <>Design decisions are planned with development practicality in mind. See our <a href="/services/web-development-australia">Web Development Australia page</a>.</>], ["SEO and Performance Awareness", "We consider content structure, mobile usability, page hierarchy and performance implications during design."], ["Clear Review Process", "Feedback and revision stages are defined so the project can move forward without unclear approval cycles."], ["Ongoing Design Support", "Support may include new page designs, campaign landing pages, ecommerce improvements, design-system expansion and mobile experience improvements."], ["Broader Digital Capability", <>Website design can connect with our <a href="/services/digital-marketing">digital marketing services</a>, <a href="/services/seo-services">SEO services</a> and <a href="/services/branding">branding services</a>.</>]];

function List({ items }) { return <ul className="wd-checklist">{items.map((x) => <li key={x}>{x}</li>)}</ul>; }
function Section({ title, intro, children, tinted=false }) { return <section className={`wd-section wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2>{intro && <p>{intro}</p>}</div>{children}</section>; }
function Cards({ items }) { return <div className="wd-card-grid">{items.map(([title, body]) => <article className="wd-card" key={title}><LayoutTemplate className="wd-card-icon" aria-hidden="true"/><h3>{title}</h3><p>{body}</p></article>)}</div>; }
function ServiceCard({ item }) { return <article className="wd-card"><LayoutTemplate className="wd-card-icon" aria-hidden="true"/><h3>{item.title}</h3>{item.paragraphs.map((p)=><p key={p}>{p}</p>)}<List items={item.items}/>{item.closing.map((p)=><p key={p}>{p}</p>)}{item.title === "Ecommerce Website Design" && <p>Where both design and development are required, explore our <a href="/services/web-development-services">web development services</a>.</p>}{item.title === "UI/UX Design" && <p>Learn more about our <a href="/services/ui-ux-design-services">UI/UX design services</a>.</p>}</article>; }

export default function WebDesignAustraliaPage(){
  const [openFaq,setOpenFaq]=useState(0);
  return <main className="web-development-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services">Services</a></li><li aria-hidden="true">/</li><li><span aria-current="page">Web Design Australia</span></li></ol></nav>
    <section className="wd-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Web Design Australia</span><h1>Web Design Services for Businesses in Australia</h1><p>Vorevix provides web design Australia services for businesses that need clear messaging, intuitive user experiences and websites designed around practical commercial goals.</p><p>We design responsive business websites, ecommerce experiences, landing pages and digital interfaces that connect brand identity, content, usability and conversion.</p><p>Whether you are launching a new website, replacing an outdated design or improving an existing customer journey, our process helps turn business requirements into a clear and usable digital experience.</p><p>Vorevix works remotely with businesses across Australia through structured discovery, collaborative design reviews and clearly defined project stages.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Website <ArrowRight size={18}/></a><a href="/portfolio">View Our Work</a></div><ul className="wda-trust"><li>Custom design around business requirements</li><li>Responsive and mobile-friendly layouts</li><li>UX, conversion and content hierarchy</li><li>Design ready for development and ongoing growth</li></ul></div><div className="wd-hero-visual"><img src="/service-web.png" alt="Web design services for businesses in Australia by Vorevix" width="1183" height="1329" fetchPriority="high"/></div></section>
    <Section title="Web Design for Australian Businesses That Need More Than a Template"><div className="wda-prose"><p>A website should do more than look professional. It should make the business easier to understand, help visitors find relevant information and guide them towards the next useful action.</p><p>Generic templates can provide a quick starting point, but they often create limitations when a business needs clearer positioning, stronger user journeys or more flexible content structures.</p><p>Common website design problems include:</p><List items={["An outdated visual style","Unclear service or product messaging","Confusing navigation","Weak mobile usability","Inconsistent branding","Difficult-to-scan pages","Important calls to action being hard to find","Ecommerce journeys that create unnecessary friction","Page layouts that cannot support new content","Design decisions that do not reflect customer needs","Limited flexibility for future website growth"]}/><p>Our web design Australia approach begins with the business, audience and purpose of the website.</p><p>We do not begin by forcing the project into a fixed template. Instead, we consider the required pages, user journeys, content, functionality and future development needs before establishing a suitable design direction.</p><p>For businesses requiring broader location-neutral support, explore our <a href="/services/web-design">general web design services</a>.</p></div></Section>
    <Section title="Why Professional Web Design Matters" tinted><Cards items={benefits}/></Section>
    <Section title="Web Design Services for Australian Businesses" intro="Our website design services can support new websites, redesign projects, ecommerce platforms and digital products. The final scope depends on your business model, audience, content, functionality and development requirements."><div className="wd-card-grid">{services.map((x)=><ServiceCard item={x} key={x.title}/>)}</div></Section>
    <Section title="Websites Designed Around Different Business Goals" intro="Different websites need different structures. The most suitable design approach depends on the audience, content and action the website needs to support." tinted><Cards items={goals}/><p className="wda-note">Capability does not automatically mean verified industry experience. Project claims should always be supported by real portfolio evidence.</p></Section>
    <Section title="Connecting Brand, Content and Website Design"><div className="wda-prose"><p>A website can look polished and still fail if the messaging is unclear.</p><p>Brand, content and interface design should support each other through consistent identity, content hierarchy, imagery and meaningful calls to action.</p><p>Website design may apply existing brand elements such as logo, colours, typography, graphic language, imagery, iconography, tone and personality.</p><p>Content hierarchy determines what users notice first and how information is grouped. Images should support the message rather than simply fill space.</p></div></Section>
    <Section title="Designed for Clear User Journeys and Better Conversion Opportunities" tinted><div className="wda-prose"><p>Conversion-focused design is not about adding more buttons.</p><p>It is about reducing avoidable friction and making important actions easier to understand and complete.</p><p>Visitors may arrive with different needs, so clear navigation, scannable content, meaningful calls to action, usable forms and verified trust signals should support different levels of intent.</p><p>No design can guarantee a specific conversion increase, but a clearer experience can remove common usability barriers.</p></div></Section>
    <Section title="Our Website Design Process" intro="A structured process helps keep design decisions connected to business requirements."><div className="wd-process-grid">{process.map((x)=><article className="wd-card" key={x.title}><h3>{x.title}</h3><List items={x.items}/><p>{x.closing}</p>{x.title.startsWith("3.")&&<p>Businesses requiring content and organic-search support can also use our <a href="/services/seo-services">SEO services</a>.</p>}{x.title.startsWith("7.")&&<p>Where design and development are combined, Vorevix can continue through our <a href="/services/web-development-services">web development services</a>.</p>}</article>)}</div></Section>
    <Section title="Responsive Web Design for Modern Devices" tinted><div className="wda-prose"><p>Users may access the website through different devices, browsers and screen sizes.</p><p>Responsive design should preserve clarity and usability rather than simply reduce the width of a desktop layout.</p><List items={["Navigation behaviour","Heading length","Content order","Button size","Form fields","Image cropping","Tables","Cards","Spacing","Touch interactions","Sticky elements","Modal windows"]}/><p>Our responsive web design Australia work is planned around the actual page system rather than creating a separate disconnected mobile website.</p></div></Section>
    <Section title="Web Design That Supports Search Visibility"><div className="wda-prose"><p>Web design and SEO are different disciplines, but design decisions can support or obstruct search visibility.</p><List items={["Logical page hierarchy","Crawlable navigation","Clear heading structures","Internal links","Mobile usability","Readable content","Metadata-ready templates","Image placement","Page performance","Accessible content","Avoiding hidden or inaccessible text","Consistent URL planning"]}/><p>Businesses requiring keyword research, content strategy and ongoing optimisation can use our <a href="/services/seo-services">SEO services</a>.</p><p>SEO-aware design does not guarantee rankings.</p></div></Section>
    <Section title="Accessible and Inclusive Website Design" tinted><div className="wda-prose"><p>Accessible design aims to make a website easier to use for people with different needs, devices and methods of interaction.</p><List items={["Readable typography","Suitable colour contrast","Clear focus states","Keyboard navigation","Logical content order","Form labels","Error messages","Link clarity","Alternative text planning","Captions or transcripts","Accessible menus","Predictable interactions"]}/><p>We use the <a href="https://www.w3.org/WAI/standards-guidelines/wcag/" target="_blank" rel="noopener noreferrer">Web Content Accessibility Guidelines</a> as an important reference when planning accessible website experiences.</p><p>A design review can support accessibility, but final implementation and testing also depend on development and content.</p></div></Section>
    <Section title="Designed with Performance in Mind"><div className="wda-prose"><p>Visual design decisions can affect website performance.</p><p>Large images, excessive animation, multiple font files and unnecessary interface effects can increase loading time and make the website harder to use.</p><List items={["Image dimensions","Responsive imagery","Animation restraint","Font selection","Component simplicity","Page length","Video placement","Interaction complexity","Third-party embeds","Mobile loading behaviour"]}/><p>Final performance also depends on development, hosting, content and third-party services.</p></div></Section>
    <Section title="What Your Web Design Project May Include" tinted><div className="wda-prose"><p>The final deliverables depend on the agreed scope.</p><List items={["Discovery workshop","Competitor review","Website strategy","Sitemap","Content planning","User journeys","Wireframes","Desktop page designs","Mobile page designs","Homepage design","Service page templates","Ecommerce layouts","Landing page templates","Form design","Navigation design","Reusable UI components","Design-system documentation","Image direction","Accessibility considerations","SEO-aware page structures","Design review stages","Developer handover","Design assets","Launch design review","Ongoing design improvements"]}/><p>Each deliverable should be confirmed before work begins.</p></div></Section>
    <Section title="Web Design for Different Australian Business Models" intro="Our web design Australia services can be adapted to different organisations and customer journeys."><Cards items={models}/><p className="wda-note">We do not claim sector experience unless it is supported by verified project work.</p></Section>
    <Section title="Web Design Support Across Australia" tinted><div className="wda-prose"><p>Vorevix works remotely with businesses across Australia, including teams in Sydney, Melbourne, Brisbane, Perth, Adelaide, Canberra, the Gold Coast, Hobart and other locations.</p><p>Our remote design process uses:</p><List items={["Scheduled online meetings","Shared project documentation","Structured design reviews","Clear approval stages","Written feedback","Defined project milestones","Centralised design files","Documented change requests"]}/><p>This allows projects to be managed across different locations without claiming an Australian office or physical presence where one does not exist.</p><p>The objective is to provide a clear working process regardless of the client’s location.</p></div></Section>
    <Section title="Why Choose Vorevix for Web Design in Australia"><Cards items={why}/><p className="wda-note">Learn more <a href="/about">about Vorevix</a>.</p></Section>
    <Section title="Selected Web Design Work" tinted><div className="wda-prose"><p>Explore selected Vorevix projects across branding, user experience, website design and development.</p><p>Each portfolio entry should present verified information about the business challenge, project scope, design requirements, delivered solution and relevant outcomes where data is available.</p><p>Traffic, revenue, conversion or performance improvements should only be published when they are accurate and supported by permission or evidence.</p><a className="wd-text-link" href="/portfolio">View Our Portfolio <ArrowRight size={18}/></a></div></Section>
    <Section title="How Web Design Pricing Is Determined"><div className="wda-prose"><p>Web design prices in Australia vary according to the size of the website, level of custom design, UX requirements, number of page templates, ecommerce functionality and whether development is included.</p><List items={["Number of pages","Number of unique page templates","Custom visual design","UX research","User journeys","Sitemap and content planning","Wireframes","Ecommerce interfaces","Responsive layouts","Design-system requirements","Illustrations or custom graphics","Copywriting scope","Brand development","Revision stages","Development requirements","Accessibility requirements","Ongoing design support"]}/><p>Vorevix prepares a tailored proposal after reviewing the project goals, required pages, available brand assets, content and technical scope.</p><a className="wd-text-link" href="/contact">Request a Website Estimate <ArrowRight size={18}/></a></div></Section>
    <Section title="Web Design Australia FAQs" tinted><div className="wda-faq-list">{webDesignAustraliaFaqs.map((faq,i)=>{const open=openFaq===i,id=`wdesign-au-faq-${i}`;return <article className="wda-faq" key={faq.question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={()=>setOpenFaq(open?-1:i)}>{faq.question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}>{faq.answer.map((p)=><p key={p}>{p}</p>)}</div></article>})}</div></Section>
    <section className="wd-final-cta"><h2>Plan Your Website Design Project in Australia</h2><p>Tell us what you need to design, improve or replace.</p><p>Vorevix will review your goals, audience, current website, available content and technical requirements before recommending a practical design approach.</p><p>Whether the project involves a business website, ecommerce platform, redesign or campaign landing page, our web design Australia services can be structured around your priorities and future plans.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Website <ArrowRight size={18}/></a><a href="/portfolio">Explore Our Work</a></div></section>
  </main>
}
