import { useState } from "react";
import { ArrowRight, ChevronDown, Palette } from "lucide-react";
import { webDesignUaeFaqs } from "../webDesignUaeFaqs";
import "./WebDevelopmentPage.css";
import "./WebDevelopmentAustraliaPage.css";
import "./WebDesignPage.css";

const scope = ["website strategy", "sitemap planning", "page hierarchy", "responsive layouts", "corporate websites", "service-business websites", "landing pages", "eCommerce design", "website redesign", "CMS website design", "design systems", "development handoff"];
const strategy = ["the main purpose of the website", "priority audiences", "primary conversion actions", "required pages", "trust information", "mobile requirements", "content responsibilities", "development considerations", "feedback and approval stages"];
const sitemap = ["Home", "About", "Services", "Individual service pages", "Industries", "Portfolio or case studies", "Insights", "Contact", "Legal pages"];
const corporate = ["company information", "services and capabilities", "industry pages", "leadership content", "governance information", "investor resources", "careers", "multiple contact paths"];
const ecommerce = ["product categories", "collection pages", "product-detail layouts", "search and filters", "promotional sections", "trust information", "cart and checkout journeys", "mobile shopping behaviour", "email-capture opportunities"];
const redesign = ["current navigation", "page structure", "content gaps", "outdated visual patterns", "inconsistent branding", "mobile usability", "conversion paths", "CMS limitations", "SEO migration requirements"];
const multilingual = ["language switching", "duplicated page structures", "navigation length", "translation workflows", "content ownership", "mobile presentation", "right-to-left layout requirements"];
const components = ["typography rules", "spacing", "buttons", "forms", "cards", "navigation patterns", "image treatments", "icons", "reusable page sections"];
const handoff = ["desktop and mobile layouts", "component states", "spacing guidance", "typography details", "image requirements", "interaction notes", "form behaviour", "asset exports", "developer annotations"];
const costs = ["number of pages", "sitemap complexity", "audience groups", "custom layouts", "eCommerce requirements", "landing pages", "redesign depth", "content readiness", "copywriting needs", "multilingual planning", "design-system requirements", "stakeholder approvals", "review rounds", "development coordination", "project timeline"];
const reasons = ["business and audience discovery", "competitor research", "sitemap and page planning", "clear content hierarchy", "custom responsive layouts", "corporate websites", "service-business websites", "eCommerce design", "landing pages", "website redesign", "design systems", "SEO, Branding and Development coordination", "remote collaboration during UAE business hours", "practical recommendations without guaranteed commercial outcomes"];
const process = [["Discovery", "We review the business, audience, competitors, current website, content and objectives."], ["Strategy and Sitemap", "We define page priorities, user paths, conversion actions and the proposed site structure."], ["Wireframes and Content Hierarchy", "We organise major sections and content placement before applying detailed visual styling."], ["Visual Design", "We create responsive layouts using the approved brand direction and project requirements."], ["Review and Refinement", "Stakeholders review designs through agreed feedback rounds and approval stages."], ["Design Handoff", "Final layouts, components and implementation notes are prepared for development."]];

function List({ items }) { return <ul className="wd-checklist">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Section({ title, children, tinted = false }) { return <section className={`wd-section web-design-content wda-section${tinted ? " wd-tinted" : ""}`}><div className="wd-section-heading"><h2>{title}</h2></div><div className="web-design-prose">{children}</div></section>; }

export default function WebDesignUaePage() {
  const [openFaq, setOpenFaq] = useState(0);
  return <main className="web-development-page web-design-page wda-page">
    <nav className="wd-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li aria-hidden="true">/</li><li><a href="/services/web-design">Web Design</a></li><li aria-hidden="true">/</li><li><span aria-current="page">United Arab Emirates</span></li></ol></nav>
    <section className="wd-hero web-design-hero"><div className="wd-hero-copy"><span className="wd-eyebrow">Web Design United Arab Emirates</span><h1>Website Design for UAE Businesses</h1><p>For organisations comparing web design company UAE providers, the right partner should do more than create attractive pages. A strong website must organise information clearly, support different screen sizes, guide visitors towards relevant actions and provide a practical foundation for development, marketing and future growth.</p><p>Vorevix supports UAE businesses through remote website strategy and design. As a web design company UAE partner, we help organisations plan page structures, clarify content priorities, create responsive layouts and prepare approved designs for development.</p><p>Our approach is suitable for startups, small and medium businesses, professional-service firms, eCommerce brands and established organisations seeking a credible and commercially focused online presence.</p><p>We do not claim that a new website will automatically guarantee rankings, traffic, leads or sales. Instead, we focus on clear planning, structured communication, responsive design and practical design handoff.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Website Design Project <ArrowRight size={18} aria-hidden="true"/></a><a href="/portfolio">View Our Work</a></div></div><div className="wd-hero-visual web-design-visual"><img src="/service-web.png" alt="Responsive website design by Vorevix" width="1183" height="1329" fetchPriority="high"/></div></section>

    <Section title="Website Design Built Around Business Priorities"><p>A website should reflect what the business offers, who it serves and what visitors need to do next.</p><p>A web design company UAE engagement should begin by understanding the organisation, its audience, services, competitors, existing website and commercial objectives. This helps prevent design decisions based only on trends or personal preference.</p><p>Depending on the project, our work may cover:</p><List items={scope}/><p>The aim is to create a website that communicates clearly and gives development, SEO and marketing teams a more organised structure to work from.</p></Section>
    <Section title="Discovery and Website Strategy" tinted><p>Discovery provides the foundation for the project.</p><p>We review the business model, target audiences, services, customer questions, current website, competitor activity, content readiness and technical requirements.</p><p>This stage may include remote workshops, questionnaires, content reviews and competitor analysis.</p><p>A website strategy can define:</p><List items={strategy}/><p>For web design company UAE projects, meetings and review sessions can be arranged around UAE business hours. Clearly documented approvals help reduce confusion and prevent repeated changes during later stages.</p></Section>
    <Section title="Audience, Competitor and Sitemap Planning"><p>A useful website structure should follow visitor needs rather than internal company departments alone.</p><p>Audience planning may consider what users are looking for, what information they need before making contact and what concerns may delay a decision.</p><p>Competitor research can identify common page structures, service gaps and opportunities to communicate more clearly.</p><p>Sitemap planning defines the main website structure before detailed design begins. Depending on the organisation, this may include:</p><List items={sitemap}/><p>The final structure depends on the business. Vorevix does not force every project into the same page template.</p></Section>
    <Section title="Custom and Responsive Website Design" tinted><p>Responsive design helps layouts adapt across common desktop, tablet and mobile screen sizes.</p><p>Our design process considers navigation, content width, typography, calls to action, forms, image behaviour and spacing. Mobile-first planning may be used so important information remains clear on smaller screens.</p><p>As a web design company UAE provider, Vorevix creates layouts around the approved brand, content hierarchy and project requirements.</p><p>Custom design means developing a practical visual system suited to the organisation rather than applying a generic template with minor changes. The design may include reusable sections, cards, navigation patterns, forms and content modules.</p></Section>
    <Section title="Corporate and Business Website Design"><p>Corporate websites may need to communicate with customers, partners, investors, employees and media contacts.</p><p>A corporate website may include:</p><List items={corporate}/><p>Small and medium businesses may need a simpler structure focused on services, proof, frequently asked questions and enquiries.</p><p>Vorevix adjusts architecture and design depth according to real requirements and does not add unnecessary pages simply to make a project appear larger.</p></Section>
    <Section title="Service-Business Websites" tinted><p>Professional and service-based companies depend on clarity and trust. Visitors should quickly understand what the company provides, who the service is for, how the process works, what evidence is available and how to make an enquiry.</p><p>A web design company UAE project for a service business may include a service overview, detailed service pages, case studies, FAQs, consultation calls to action and contact forms.</p><p>This can support organisations in professional services, construction, healthcare, hospitality, technology and consulting. Industry-specific claims should only be used where genuine capability and evidence exist.</p></Section>
    <Section title="eCommerce Website Design"><p>eCommerce design should support product discovery, comparison and checkout journeys without creating unnecessary friction.</p><p>Depending on the project, Vorevix may help plan:</p><List items={ecommerce}/><p>The design stage focuses on the visual and structural experience. Platform configuration, payments, integrations, migration and implementation belong to Web Development.</p><p>Approved eCommerce designs can later be implemented through our <a href="/services/web-development-services">UAE web-development service</a>, including CMS setup, integrations, testing and launch support.</p></Section>
    <Section title="Landing Pages and Campaign Design" tinted><p>Landing pages are usually designed around one campaign, audience or conversion action.</p><List items={["lead generation", "consultation bookings", "event registration", "product launches", "paid advertising", "downloadable resources", "service promotions"]}/><p>The page should keep its message aligned with the campaign and make the next action easy to identify.</p><p>Vorevix can coordinate landing-page design with <a href="/services/digital-marketing">Digital Marketing</a> requirements. Design cannot guarantee conversions because results also depend on targeting, traffic quality, offer strength, messaging and follow-up.</p></Section>
    <Section title="Website Redesign for Growing UAE Businesses"><p>A redesign may be suitable when the current website no longer reflects the business, is difficult to use on mobile, contains outdated content or has become hard to maintain.</p><p>The redesign process may review:</p><List items={redesign}/><p>A web design company UAE redesign should not remove useful content or URLs without review.</p><p>Existing rankings, analytics, redirects and technical dependencies should be considered before major structural changes. Vorevix can coordinate with SEO and development teams to reduce avoidable migration risks, but a redesign cannot guarantee improved rankings or conversions.</p></Section>
    <Section title="Multilingual and Arabic Website Planning" tinted><p>Many UAE organisations communicate with audiences using different languages.</p><p>Multilingual website planning may consider:</p><List items={multilingual}/><p>Arabic interfaces may require specialist typography, content review and RTL implementation.</p><p>A web design company UAE project includes native Arabic copywriting, translation, Arabic research or specialist RTL delivery only when verified. Otherwise, designs can be structured so translated content may be added by specialists.</p></Section>
    <Section title="Design Systems and Consistent Components"><p>A design system can help maintain visual consistency across pages and future updates.</p><p>Depending on scope, it may include:</p><List items={components}/><p>For larger websites, reusable components can make design review and development more efficient. The system should remain practical because a business website does not always require a large digital-product framework.</p></Section>
    <Section title="Design Handoff and Development Coordination" tinted><p>Approved designs need clear documentation before implementation.</p><p>The handoff may include:</p><List items={handoff}/><p>Vorevix can coordinate with the client's development team, another provider or our <a href="/services/web-development-services">Web Development service</a>. Interfaces can use our <a href="/services/ui-ux-design-services">UAE UI/UX design service</a>.</p><p>Web Design owns strategy, page planning and visual direction. Web Development owns implementation, back-end functionality, CMS setup, integrations, testing, deployment, security and maintenance.</p></Section>
    <Section title="SEO-Aware Website Structure"><p>Web Design and SEO support each other, but they are different services.</p><p>Website design can support SEO through clear page hierarchy, crawlable navigation, content organisation, mobile usability and space for relevant copy.</p><p>Complete keyword research, technical SEO, on-page optimisation, structured data, indexing and backlink strategy remain within SEO.</p><p>A web design company UAE should not promise Google rankings based on design alone.</p><p>Projects can coordinate with <a href="/services/seo-services">UAE SEO services</a> so approved search requirements are reflected in structure and implementation.</p></Section>
    <section className="wd-section wd-tinted"><div className="wd-section-heading"><h2>Our Website Design Process</h2></div><div className="wd-process-grid">{process.map(([title, body]) => <article className="wd-process-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p className="web-design-regional-note">The exact process may be adjusted according to project size and complexity.</p></section>
    <Section title="Remote Collaboration Across the UAE"><p>As a web design company UAE partner, Vorevix works remotely with organisations throughout the United Arab Emirates.</p><p>Collaboration may include scheduled video meetings, shared design files, written updates, feedback documents and staged approvals.</p><p>We can work with founders, directors, marketing teams, brand teams, writers and developers during suitable UAE business hours.</p><p>National availability does not imply a physical UAE office, a local UAE phone number or a UAE-based design team.</p></Section>
    <Section title="What Influences Website Design Cost in the UAE?" tinted><p>The cost of working with a web design company UAE depends on the scope and complexity of the project.</p><p>Common factors include:</p><List items={costs}/><p>Design fees, development costs, hosting, content production and third-party software should be treated as separate items where relevant.</p><p>Vorevix prepares a tailored proposal after reviewing the requirements. We do not publish unsupported AED prices, UAE VAT statements, guaranteed outcomes or fixed timelines for every project.</p></Section>
    <section className="wd-section"><div className="wd-section-heading"><h2>Why Work With Vorevix?</h2><p>Our web design company UAE approach combines website strategy, responsive design and structured handoff without forcing every organisation into the same template.</p></div><div className="wd-card-grid">{reasons.map((reason) => <article className="wd-card" key={reason}><Palette className="wd-card-icon" size={25} aria-hidden="true"/><h3>{reason}</h3></article>)}</div><div className="web-design-prose"><p>For broader methodology, <a href="/services/web-design">explore our complete web design services</a>.</p></div></section>
    <section className="wd-section web-design-content wda-section wd-tinted"><div className="wd-section-heading"><h2>Frequently Asked Questions</h2></div><div className="wda-faq-list">{webDesignUaeFaqs.map(([question, answer], index) => { const open = openFaq === index; const id = `web-design-uae-faq-${index}`; return <article className="wda-faq" key={question}><h3><button type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpenFaq(open ? -1 : index)}>{question}<ChevronDown aria-hidden="true"/></button></h3><div id={id} hidden={!open}><p>{answer}</p></div></article>; })}</div></section>
    <section className="wd-final-cta"><h2>Plan Your UAE Website Project</h2><p>A strong website should connect business priorities, audience needs, content structure, responsive design and development requirements.</p><p>Vorevix helps UAE businesses plan and design websites that communicate clearly and provide an organised foundation for implementation.</p><p>Share your current website, required pages, target audience, preferred features, content status and expected timeline. We will review the requirements and discuss the next step.</p><div className="wd-actions"><a className="primary" href="/contact">Discuss Your Website Design Project <ArrowRight size={18} aria-hidden="true"/></a></div></section>
  </main>;
}
