export const architecturePages = [
  {
    path: "/services/web-design",
    title: "Web Design Services | Vorevix",
    description: "Explore Vorevix web design services and start planning a clear, responsive website experience for your business.",
    eyebrow: "Service",
    h1: "Web Design Services",
    intro: "A dedicated space for Vorevix web design services, prepared for future service details, process information and project examples.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Web Design" },
    ],
  },
  {
    path: "/services/digital-marketing",
    title: "Digital Marketing Services | Vorevix",
    description: "Explore the Vorevix digital marketing service area and discuss a practical campaign strategy for your business.",
    eyebrow: "Service",
    h1: "Digital Marketing Services",
    intro: "A dedicated space for Vorevix digital marketing services, ready for future campaign, channel and growth strategy information.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Digital Marketing" },
    ],
  },
  {
    path: "/blog",
    title: "Blog | Vorevix",
    description: "Visit the Vorevix blog area for future insights about web design, development, SEO, branding and digital marketing.",
    eyebrow: "Insights",
    h1: "Vorevix Blog",
    intro: "The future home of Vorevix articles, practical guides and perspectives across design, development, search and digital growth.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Blog" },
    ],
  },
  {
    path: "/locations",
    title: "Locations | Vorevix",
    description: "Explore the Vorevix locations hub for businesses seeking digital services across Australia, New Zealand and the UAE.",
    eyebrow: "Locations",
    h1: "Locations We Serve",
    intro: "Explore the regional areas prepared for Vorevix services across Australia, New Zealand and the United Arab Emirates.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Locations" },
    ],
  },
  {
    path: "/locations/australia",
    title: "Digital Services in Australia | Vorevix",
    description: "Explore the Vorevix Australia service area for future information about web, SEO, branding and digital support.",
    eyebrow: "Location",
    h1: "Digital Services in Australia",
    intro: "A regional page prepared for future information about Vorevix services for businesses across Australia.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Locations", href: "/locations" },
      { label: "Australia" },
    ],
  },
  {
    path: "/locations/new-zealand",
    title: "Digital Services in New Zealand | Vorevix",
    description: "Explore the Vorevix New Zealand service area for future information about web, SEO, branding and digital support.",
    eyebrow: "Location",
    h1: "Digital Services in New Zealand",
    intro: "A regional page prepared for future information about Vorevix services for businesses across New Zealand.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Locations", href: "/locations" },
      { label: "New Zealand" },
    ],
  },
  {
    path: "/locations/united-arab-emirates",
    title: "Digital Services in the UAE | Vorevix",
    description: "Explore the Vorevix UAE service area for future information about web, SEO, branding and digital support.",
    eyebrow: "Location",
    h1: "Digital Services in the United Arab Emirates",
    intro: "A regional page prepared for future information about Vorevix services for businesses across the United Arab Emirates.",
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Locations", href: "/locations" },
      { label: "United Arab Emirates" },
    ],
  },
];
