export const brandingFaqs = [
  { question: "What are branding services?", answer: ["Branding services help define how a business is understood, recognised and experienced. They may include research, strategy, positioning, messaging, naming, logo design, visual identity, brand guidelines, rebranding, applications and rollout support."] },
  { question: "What do branding services include?", answer: ["The scope can include discovery, audience and competitor research, brand strategy, positioning, messaging, naming, visual identity design, guidelines, priority applications and activation planning.", "The exact deliverables depend on the needs and stage of the business."] },
  { question: "What is the difference between branding and logo design?", answer: ["A logo is one identifiable visual asset.", "Branding is the wider system that influences how a business is understood and experienced. It includes strategy, positioning, messaging, personality, visual identity, guidelines and consistent application."] },
  { question: "What is the difference between a logo and a visual identity?", answer: ["A logo is a symbol, wordmark or combination mark used to identify the business.", "A visual identity includes the logo as well as colour, typography, imagery, graphic language, layouts, icons and application rules."] },
  { question: "How much do branding services cost?", answer: ["The price of branding services depends on business complexity, research requirements, strategic scope, number of stakeholders, deliverables, applications and rollout support.", "We review the project requirements before preparing a tailored estimate."] },
  { question: "How long does a branding project take?", answer: ["The timeline depends on the scope, stakeholder availability, feedback process and number of deliverables.", "A focused identity project may require less time than a complete rebrand involving research, strategy, naming, messaging, guidelines and implementation support."] },
  { question: "When should a business consider rebranding?", answer: ["Rebranding may be appropriate when the business has changed direction, entered new markets, expanded its services, outgrown its current identity or developed inconsistent communication.", "It may also be needed when customers no longer understand what the business offers or the identity does not support its future plans."] },
  { question: "Can you refresh an existing identity without replacing it completely?", answer: ["Yes.", "Some businesses need an identity refresh rather than a complete rebrand. We can assess which parts still hold value and decide whether individual elements should be retained, refined or replaced."] },
  { question: "Do you provide brand guidelines?", answer: ["Yes.", "We can create guidelines covering strategy, messaging, logo usage, colour, typography, imagery, graphic elements, layouts and practical applications."] },
  { question: "Do you provide rollout and implementation support?", answer: ["Yes.", "Support can include website coordination, templates, presentations, company profiles, social media assets, packaging, print materials and staged brand rollout recommendations."] },
];
