export const brandingAustraliaFaqs = [
  { question: "What branding services do you provide in Australia?", answer: ["Our branding services Australia offering may include discovery, strategy, positioning, naming, messaging, logo design, visual identity, guidelines, rebranding, packaging, collateral and digital applications.", "The final scope depends on the business, current identity and required deliverables."] },
  { question: "How much do branding services cost in Australia?", answer: ["Pricing depends on the level of research, strategy, identity development, messaging, applications, guidelines and stakeholder involvement required.", "Vorevix prepares a tailored proposal after reviewing the project requirements."] },
  { question: "Is branding the same as logo design?", answer: ["No. Logo design is one part of branding.", "Branding may also include strategy, positioning, messaging, tone of voice, visual identity, guidelines and applications."] },
  { question: "What is included in a brand identity package?", answer: ["A brand identity package may include a logo suite, colour palette, typography system, graphic elements, imagery direction, usage rules and selected templates.", "The exact deliverables depend on the agreed scope."] },
  { question: "Do you provide brand strategy services?", answer: ["Yes. Brand strategy may cover audience definition, positioning, value proposition, personality, purpose, values and brand architecture."] },
  { question: "Can you rebrand an existing business?", answer: ["Yes. Rebranding may include an audit, strategy review, positioning, messaging, logo development, visual identity, guidelines and rollout planning."] },
  { question: "Can you refresh a brand without replacing everything?", answer: ["Yes. A brand refresh or evolution may improve selected parts of the system while retaining useful recognition and existing equity."] },
  { question: "Do you create brand guidelines?", answer: ["Yes. Guidelines may cover logo use, spacing, colours, typography, imagery, graphics, tone of voice and digital or print applications."] },
  { question: "Can you design packaging and marketing collateral?", answer: ["Yes. Packaging, brochures, stationery, presentations, signage and other collateral may be included in the agreed project scope."] },
  { question: "Do you provide naming services?", answer: ["Yes. Naming support may include criteria, territories, shortlists and rationale.", "Formal legal and trade mark clearance should be completed by suitably qualified professionals."] },
  { question: "What files are provided at the end of a branding project?", answer: ["The handover may include vector, print and web formats, guidelines and agreed templates.", "The exact file list is confirmed in the project scope."] },
  { question: "Do you work remotely with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia through online sessions, shared documentation, design presentations, feedback stages and organised handover."] },
];
