export const digitalMarketingAustraliaFaqs = [
  { question: "What digital marketing services do you provide in Australia?", answer: ["Our digital marketing services Australia offering may include strategy, SEO, Google Ads, social media advertising, content marketing, email marketing, ecommerce campaigns, lead generation, landing pages, analytics and ongoing optimisation.", "The final scope depends on the business goals, audience, budget and existing marketing activity."] },
  { question: "How much do digital marketing services cost in Australia?", answer: ["Pricing depends on the number of channels, advertising budget, campaign complexity, creative requirements, tracking setup and level of ongoing management.", "Vorevix prepares a tailored proposal after reviewing the business and campaign requirements."] },
  { question: "Which digital marketing channels should my business use?", answer: ["The most suitable channels depend on the target audience, offer, budget, customer journey and business goals.", "A strategy may use one channel initially or combine SEO, paid search, social, content and email where appropriate."] },
  { question: "How long does digital marketing take to show results?", answer: ["Timelines vary by channel.", "Paid campaigns can generate traffic quickly, while SEO and content usually require longer-term work. Email and conversion optimisation depend on the available audience, traffic and data."] },
  { question: "Do you provide SEO and paid advertising together?", answer: ["Yes. SEO and paid advertising can be managed as connected parts of a broader strategy.", "Paid campaigns may support immediate visibility, while SEO can strengthen longer-term organic discovery."] },
  { question: "How do you measure digital marketing performance?", answer: ["Performance may be measured through traffic, leads, sales, conversion rate, cost per lead, campaign costs, organic visibility, email activity and landing-page performance.", "The most relevant metrics depend on the campaign goals."] },
  { question: "Can you manage an existing campaign?", answer: ["Yes. We can review existing campaign structure, tracking, audiences, creative, budgets, landing pages and performance before recommending changes.", "Existing activity should be audited before it is expanded or rebuilt."] },
  { question: "Do you work with small businesses?", answer: ["Yes. Small-business campaigns can be designed around realistic priorities, available budget and the channels most closely connected to customer demand.", "The scope should remain focused rather than spreading resources across too many platforms."] },
  { question: "Do you provide ecommerce digital marketing?", answer: ["Yes. Ecommerce marketing may include shopping campaigns, ecommerce SEO, email automation, paid social, remarketing, product landing pages and conversion tracking."] },
  { question: "Can you set up email marketing and automation?", answer: ["Yes. Email support may include campaigns, welcome sequences, lead nurturing, abandoned-cart flows, customer segmentation and reporting.", "The exact setup depends on the email platform and available customer data."] },
  { question: "Do you create landing pages?", answer: ["Yes. Landing-page support may include content structure, messaging, design, development, forms, mobile usability and conversion tracking."] },
  { question: "Do you work remotely with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia.", "Projects and campaigns are managed through online meetings, shared documentation, approval stages, regular reporting and structured reviews."] },
];
