export const digitalMarketingFaqs = [
  { question: "What do digital marketing services include?", answer: ["Digital marketing services may include strategy, paid search, paid social, social media marketing, content marketing, email marketing, lead generation, conversion tracking, campaign optimisation and reporting.", "The final scope depends on your objectives, audience, budget and selected channels."] },
  { question: "Which digital marketing channels are right for my business?", answer: ["The right channels depend on your audience, offer, goals, budget, sales cycle and available marketing assets.", "Some businesses benefit from one focused channel, while others need a coordinated approach across paid media, social media, content and email."] },
  { question: "How much do digital marketing services cost?", answer: ["The cost of digital marketing services depends on the number of channels, campaign complexity, research, creative production, tracking requirements, campaign duration and reporting needs.", "Advertising spend is generally separate from strategy and campaign-management fees."] },
  { question: "How much advertising budget do I need?", answer: ["There is no universal advertising budget suitable for every campaign.", "The appropriate amount depends on the market, platform costs, audience size, campaign goal, level of competition and amount of testing required."] },
  { question: "How long does digital marketing take to produce results?", answer: ["Paid campaigns can begin producing performance data soon after launch, but reliable optimisation normally requires enough traffic and conversion information.", "Timelines vary according to the channel, budget, sales cycle and campaign objective."] },
  { question: "Do you manage PPC and paid social campaigns?", answer: ["Yes. Depending on the agreed scope, Vorevix can support paid search and paid social campaigns, including strategy, setup, targeting, tracking, testing and optimisation."] },
  { question: "Can you help with landing pages and conversion tracking?", answer: ["Yes. Campaign support can include landing-page recommendations, conversion planning and tracking requirements.", "Where needed, this can be connected with our web design, UI/UX design and web development services."] },
  { question: "How do you measure campaign performance?", answer: ["Performance is measured according to the campaign objective.", "Metrics may include qualified leads, enquiries, purchases, sign-ups, conversion rate, cost per result, cost per acquisition and return on advertising spend."] },
  { question: "Is SEO included in digital marketing services?", answer: ["SEO can support a broader digital strategy, but it requires dedicated technical, content and authority work.", "Vorevix provides SEO through a separate SEO services scope to avoid mixing long-term organic growth with short-term campaign management."] },
  { question: "Will I receive regular reports?", answer: ["Yes. Reporting can be included in ongoing campaign management.", "The reporting frequency depends on the engagement, but reports may include performance, completed changes, observations and recommended next actions."] },
];
