export const seoAustraliaFaqs = [
  { question: "What SEO services do you provide in Australia?", answer: ["Our SEO services Australia offering may include keyword research, technical SEO, on-page optimisation, content strategy, local SEO, ecommerce SEO, website audits, migration support, link-authority work and ongoing reporting.", "The final scope depends on the website, market, competition and business goals."] },
  { question: "How much do SEO services cost in Australia?", answer: ["SEO pricing depends on the website size, competition, technical condition, target services, target locations, content requirements and implementation scope.", "Vorevix prepares a tailored proposal after reviewing the website and priorities."] },
  { question: "How long does SEO take to show results?", answer: ["SEO timelines vary according to the website, competition, content, authority and speed of implementation.", "Some technical improvements may be completed quickly, but sustainable organic growth generally requires consistent work over time."] },
  { question: "Can you guarantee first-page rankings?", answer: ["No.", "Search rankings are controlled by search engines and affected by competition, algorithms, website quality and market changes. An ethical SEO provider should not guarantee a specific ranking position."] },
  { question: "Do you work with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia.", "Campaigns are managed through online meetings, shared documentation, prioritised action plans and regular reporting."] },
  { question: "What is included in an SEO campaign?", answer: ["A campaign may include discovery, website auditing, keyword research, technical recommendations, on-page optimisation, content work, local SEO, authority-building activity and reporting.", "The exact deliverables are defined in the agreed scope."] },
  { question: "Do you provide local SEO services?", answer: ["Yes. Local SEO may include local keyword research, location-page strategy, Google Business Profile guidance, citations, local internal linking and business-information consistency.", "We do not create false offices or misleading location claims."] },
  { question: "Can you improve an unsuccessful SEO campaign?", answer: ["We can review the campaign history, website changes, technical issues, content, keywords and backlinks to identify possible causes.", "The findings determine whether the existing strategy should be corrected, narrowed or rebuilt."] },
  { question: "How do you measure SEO performance?", answer: ["Performance may be measured through organic traffic, search visibility, landing-page activity, leads, sales where tracked, local visibility and completed technical improvements.", "The most suitable metrics depend on the business model and campaign goals."] },
  { question: "Is SEO still worth it with AI search?", answer: ["Search behaviour is changing, but businesses still need useful content, technically accessible websites, authority and clear information.", "AI search adds new visibility considerations, but it does not remove the need for strong SEO foundations."] },
  { question: "Can you help with ecommerce SEO?", answer: ["Yes. Ecommerce SEO may include product and category optimisation, faceted-navigation review, duplicate-content management, structured data, internal linking and technical indexation."] },
  { question: "Can you support a website redesign or migration?", answer: ["Yes. SEO migration support may include URL mapping, redirects, canonical checks, metadata migration, internal-link updates, sitemap review and post-launch monitoring."] },
];
