export const seoServiceFaqs = [
  { question: "What is included in professional SEO services?", answer: "A campaign may include auditing, keyword research, technical SEO, on-page optimisation, content planning, internal linking, authority analysis, reporting and implementation support." },
  { question: "How long does SEO take?", answer: "Some improvements may be recognised within weeks, while meaningful growth in competitive markets often takes several months. Timelines depend on competition, authority, content quality and implementation speed." },
  { question: "How much do SEO services cost?", answer: "Cost varies according to website size, competition, required content, technical complexity and whether implementation is included. A review is needed before an accurate scope and price can be provided." },
  { question: "Do you guarantee first-page rankings?", answer: "No. Search engines control their results, and rankings change continuously. We provide evidence-led strategy without making guarantees that cannot be responsibly supported." },
  { question: "What is the difference between SEO and paid advertising?", answer: "SEO aims to improve organic visibility over time, while paid advertising purchases immediate placement. Both can support growth, but they use different budgets and timelines." },
  { question: "Can you work with our existing developers?", answer: "Yes. We can provide technical requirements, answer implementation questions and review completed work. Responsibilities are agreed at the start." },
  { question: "Do you provide content optimisation?", answer: "Yes. We can assess existing pages, recommend improvements and create briefs for new content. Writing and publishing can be included where agreed." },
  { question: "How do you measure SEO performance?", answer: "Measurement may include qualified organic traffic, conversions, keyword visibility, indexation, technical health and content performance." },
  { question: "Is AI SEO different from traditional SEO?", answer: "AI discovery creates additional visibility opportunities, but it still depends on accessible websites, useful content, clear information and authority. It does not replace traditional SEO foundations." },
];
