export const uiUxFaqs = [
  { question: "What are UI UX design services?", answer: "UI UX design services cover the research, planning, structure, visual interface and testing involved in creating a digital experience. Depending on the project, this may include UX audits, user research, information architecture, user flows, wireframes, interface design, prototypes, usability testing, design systems and developer handoff." },
  { question: "What is the difference between UI and UX design?", answer: "UX design focuses on how an experience works, including research, structure, journeys, flows and usability. UI design focuses on how the experience is visually presented and interacted with, including layout, typography, colours, controls and interface states. Strong digital products require UX and UI to work together." },
  { question: "What types of projects do you design?", answer: "Vorevix designs experiences for business websites, mobile applications, SaaS products, web applications, dashboards, portals and eCommerce journeys. The exact approach depends on the users, product complexity and technical requirements." },
  { question: "Can you improve an existing website or product?", answer: "Yes. An existing product can be reviewed through a UX audit, heuristic evaluation, analytics review or usability testing. Improvements may focus on specific journeys, navigation, forms, mobile usability, onboarding, interface consistency or a broader redesign." },
  { question: "Do you conduct user research and usability testing?", answer: "Yes, when they are relevant to the agreed project scope. Research may include interviews, surveys, analytics review and existing feedback. Usability testing can evaluate wireframes, prototypes or live products through defined user tasks." },
  { question: "What will we receive at the end of the project?", answer: "Deliverables depend on the agreed scope. They may include research findings, personas, journey maps, information architecture, user flows, wireframes, high-fidelity interface designs, responsive layouts, clickable prototypes, component libraries and developer handoff documentation." },
  { question: "Do you design responsive interfaces?", answer: "Yes. Desktop, tablet and mobile behaviour can be considered throughout the design process. Layouts, navigation, components and interactions are adapted according to the needs of each screen size and product." },
  { question: "Can you work with our development team?", answer: "Yes. We can provide organised design files, responsive layouts, component states, assets, interaction notes and implementation support. We can also review the developed interface to identify differences from the approved design." },
  { question: "How long does a UI UX design project take?", answer: "The timeline depends on the number of screens, research scope, product complexity, testing requirements and feedback cycles. A focused UX audit may take less time than a complete SaaS product or mobile application design. A project timeline is defined after the scope has been reviewed." },
  { question: "How much do UI UX design services cost?", answer: "The cost depends on research requirements, screen count, platform complexity, responsive layouts, prototypes, testing, design systems and developer support. Vorevix provides a project estimate after reviewing the required scope and deliverables." },
];
