export const uiUxAustraliaFaqs = [
  { question: "What is included in a UI/UX design project?", answer: ["Scope may include strategy, workshops, research, information architecture, user flows, wireframes, prototypes, interface design, usability testing, design systems and developer handoff. The final deliverables depend on the product and agreed objectives."] },
  { question: "How much does UI/UX design cost in Australia?", answer: ["Cost depends on product complexity, number of screens, research needs, testing, design-system requirements and stakeholder involvement. Vorevix provides a tailored proposal after reviewing the scope."] },
  { question: "Do you work with businesses across Australia?", answer: ["Yes. Vorevix works remotely with Australian businesses and product teams through scheduled workshops, written updates, milestone reviews and consolidated feedback."] },
  { question: "Can you improve an existing product?", answer: ["Yes. We can review an existing website or application, identify usability issues and redesign selected journeys or the wider experience."] },
  { question: "Do you conduct user research and usability testing?", answer: ["Research and testing can be included where they support the project questions. The method, participant requirements and deliverables are agreed before work begins."] },
  { question: "Can you design SaaS products and web applications?", answer: ["Yes. We can support dashboards, onboarding, account areas, forms, workflows and other digital-product interfaces where the required scope is clearly defined."] },
  { question: "Will you work with our developers?", answer: ["Yes. We can provide organised design files, components, states, assets and documentation, then collaborate with the development team during handoff."] },
  { question: "Do you guarantee conversion improvements or accessibility compliance?", answer: ["No. Good UX can reduce friction and support better outcomes, but conversion and compliance depend on implementation, traffic, content, testing and other factors. Formal accessibility claims require a specific audit and compliance scope."] },
];
