export const uiUxFaqs = [
  { question: "What is included in UI UX design services?", answer: "The scope may include discovery, UX research, information architecture, user flows, wireframes, prototypes, high-fidelity UI, responsive variants, design systems, usability testing and developer handoff." },
  { question: "How is UI/UX different from web design?", answer: "Web design commonly focuses on the structure and appearance of a website. UI/UX can also cover complex applications, dashboards, SaaS products and repeated workflows, with deeper attention to research, usability and interaction states." },
  { question: "How much does a UI/UX design project cost?", answer: "Cost depends on screen count, complexity, research, responsive requirements, prototype depth and whether a design system is needed. A focused audit costs less than designing a complete multi-role product." },
  { question: "How long does UI/UX design take?", answer: "A small, defined engagement may take a few weeks, while a larger product can require several phases. Timeline depends on scope, feedback speed, user access and the number of screens." },
  { question: "Can you redesign an existing website or product?", answer: "Yes. We can audit the current experience, identify priority problems and redesign selected journeys or the full interface. Existing elements that perform well do not need to be replaced without reason." },
  { question: "Do you provide UX research and usability testing?", answer: "Yes, where appropriate to the scope. Research may include stakeholder discussions, analytics review, user interviews, competitor analysis, surveys or usability testing." },
  { question: "Will the designs be responsive and ready for development?", answer: "Responsive requirements and developer handoff can be included. Final files may contain screen variants, components, states, assets and interaction notes." },
  { question: "Can you work with our development team?", answer: "Yes. Vorevix can collaborate with an internal or external team, answer design questions and review implementation through design QA. We also provide web development for projects that need both design and implementation." },
];
