export const uiUxAustraliaFaqs = [
  { question: "What UI/UX design services do you provide in Australia?", answer: ["Our UI UX design services Australia offering may include UX research, stakeholder workshops, user journeys, information architecture, wireframes, UI design, interactive prototypes, usability testing, accessibility reviews, design systems, UX audits and developer handoff.", "The final scope depends on the product, users and required deliverables."] },
  { question: "How much do UI/UX design services cost in Australia?", answer: ["Pricing depends on the project scope, number of screens, research, user journeys, prototype depth, testing, accessibility requirements and handoff.", "Vorevix prepares a tailored proposal after reviewing the product and project requirements."] },
  { question: "What is the difference between UI and UX design?", answer: ["UX design focuses on how the experience works, including research, journeys, structure and usability.", "UI design focuses on the visual and interactive interface, including typography, colour, layout, components and states."] },
  { question: "Do I need UX research before interface design?", answer: ["Research is useful when the project involves unclear user needs, complex workflows, existing usability issues or significant product decisions.", "The research scope can be adjusted according to the project, available users, timeline and budget."] },
  { question: "Can you redesign an existing website or app?", answer: ["Yes. We can review the current experience, identify usability issues and develop an improved structure, interface and design system.", "The scope may begin with a UX audit before the redesign."] },
  { question: "Do you design mobile apps and SaaS products?", answer: ["Yes. Mobile-app and SaaS work may include user flows, onboarding, dashboards, account journeys, permissions, prototypes, interface design and design systems."] },
  { question: "What is included in a UI/UX design project?", answer: ["A project may include discovery, research, information architecture, user flows, wireframes, interface screens, prototypes, testing, design systems and developer handoff.", "The exact deliverables are confirmed in the agreed scope."] },
  { question: "Do you create interactive prototypes?", answer: ["Yes. Interactive prototypes may be created to demonstrate key journeys, review interactions, support testing and clarify development requirements."] },
  { question: "Do you provide usability testing?", answer: ["Yes, where testing is included in the scope and suitable participants are available.", "Testing may involve selected tasks, observations, findings and design recommendations."] },
  { question: "Do you consider accessibility?", answer: ["Yes. Accessibility may be considered through colour contrast, typography, focus states, keyboard interaction, forms, content hierarchy and component behaviour.", "Final conformance depends on development and should be tested in the implemented product."] },
  { question: "Do you provide developer handoff?", answer: ["Yes. Handoff may include design files, assets, component states, responsive rules, interaction notes, prototypes and implementation support."] },
  { question: "Do you work remotely with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia through online workshops, collaborative design files, prototype reviews, structured feedback and documented developer handoff."] },
];
