export const webDevelopmentAustraliaFaqs = [
  { question: "How much does web development cost in Australia?", answer: ["Cost depends on project scope, platform, integrations, custom functionality, content requirements, testing and ongoing support. After reviewing the requirements, Vorevix can provide a tailored proposal rather than relying on an unsupported fixed price."] },
  { question: "How long does a web development project take?", answer: ["Timelines depend on complexity, content readiness, integration requirements, approvals and feedback. A clear project plan should define milestones, responsibilities and review stages."] },
  { question: "Do you work with businesses across Australia?", answer: ["Yes. Vorevix works remotely with Australian businesses through scheduled meetings, written updates, milestone reviews and structured feedback."] },
  { question: "Can you take over an existing website?", answer: ["Yes, subject to access, platform condition and technical review. We first assess the codebase, hosting, integrations and documentation before confirming the safest approach."] },
  { question: "Can you migrate a website without losing SEO visibility?", answer: ["Migration can be planned to reduce avoidable risk through URL mapping, redirects, metadata checks and technical coordination. No provider can guarantee that rankings will remain unchanged."] },
  { question: "Which platforms do you develop on?", answer: ["Platform recommendations depend on the website or application requirements. We select tools based on content, integrations, scalability, maintenance needs and internal capability."] },
  { question: "Do you offer ongoing maintenance and support?", answer: ["Ongoing support can be included when agreed in the project scope. This may cover updates, monitoring, fixes, backups or future development work."] },
  { question: "Will we own the website and receive access?", answer: ["Ownership, licences, hosting, source access and handover terms should be documented in the proposal. Vorevix aims to keep these responsibilities clear before development begins."] },
];
