export const webDevelopmentAustraliaFaqs = [
  { question: "What web development services do you provide in Australia?", answer: ["Our web development Australia services may include custom websites, business websites, ecommerce development, CMS development, web applications, SaaS products, API integrations, website redevelopment and ongoing maintenance.", "The final scope depends on your business goals and technical requirements."] },
  { question: "How much does web development cost in Australia?", answer: ["Web development costs vary according to the number of pages, design requirements, functionality, ecommerce needs, integrations, content migration, testing and support.", "A tailored estimate can be prepared after the requirements have been reviewed."] },
  { question: "How long does a website development project take?", answer: ["The timeline depends on the project scope, design requirements, content readiness, integrations, feedback process and testing complexity.", "A straightforward website may take less time than a custom ecommerce platform or web application.", "The expected delivery stages should be defined in the project proposal."] },
  { question: "Do you work remotely with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia.", "Projects are managed through online meetings, documented requirements, scheduled reviews and defined delivery milestones.", "We do not claim a physical Australian office unless one has been formally established and verified."] },
  { question: "Can you redesign or rebuild an existing website?", answer: ["Yes. We can review an existing website and recommend whether it should be redesigned, improved, partially redeveloped or completely rebuilt.", "The recommendation depends on the current platform, code quality, content, integrations and business requirements."] },
  { question: "Do you develop ecommerce websites?", answer: ["Yes. Ecommerce development may include product management, shopping carts, checkout journeys, payment gateways, shipping configuration, customer accounts and third-party integrations.", "The platform should be selected according to your products, operations and plans for growth."] },
  { question: "Can you build custom web applications or SaaS platforms?", answer: ["Yes. We can support web applications and SaaS products such as portals, dashboards, booking systems, account platforms and custom workflows.", "These projects normally require detailed product, user and technical planning before development begins."] },
  { question: "Which CMS and technologies do you use?", answer: ["Technology is selected according to the functionality, content-management needs, integrations, scalability and maintenance requirements of the project.", "We do not recommend the same platform for every website."] },
  { question: "Will the website be SEO-ready and accessible?", answer: ["Development can include technical SEO foundations and accessibility considerations such as semantic structure, metadata support, crawlable navigation, keyboard usability, form labels and responsive behaviour.", "This does not guarantee search rankings or automatically confirm compliance with every legal accessibility requirement."] },
  { question: "Do you provide maintenance and support after launch?", answer: ["Yes. Ongoing support may include technical updates, security checks, performance improvements, troubleshooting, content changes and additional development.", "The support scope and response expectations should be agreed before ongoing work begins."] },
];
