export const webDesignAustraliaFaqs = [
  { question: "What web design services do you provide in Australia?", answer: ["Our web design Australia services may include custom website design, business websites, ecommerce design, website redesign, landing pages, responsive layouts, design systems and UI/UX design.", "The final scope depends on the business goals, content, functionality and development requirements."] },
  { question: "How much does web design cost in Australia?", answer: ["Web design costs vary according to the number of pages, custom design level, wireframes, responsive layouts, ecommerce requirements, content support and whether development is included.", "A tailored estimate can be prepared after the project requirements have been reviewed."] },
  { question: "How long does a web design project take?", answer: ["The timeline depends on the number of pages, content readiness, design complexity, feedback process, ecommerce requirements and whether branding or development is included.", "The expected stages and review periods should be defined in the project proposal."] },
  { question: "Do you work remotely with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia.", "Projects are managed through online meetings, shared documentation, structured design reviews and defined approval stages."] },
  { question: "What is included in a web design project?", answer: ["A project may include discovery, strategy, sitemap planning, content structure, wireframes, desktop and mobile layouts, reusable components, review stages and developer handover.", "The exact deliverables depend on the agreed scope."] },
  { question: "Will my website be mobile-friendly?", answer: ["Responsive layouts can be designed for phones, tablets, laptops and larger screens.", "This includes considerations such as mobile navigation, readable typography, button size, content order and form usability."] },
  { question: "Can you redesign an existing website?", answer: ["Yes. We can review the current design, content structure, navigation, branding and user journeys before recommending an appropriate redesign approach.", "Where technical limitations are involved, redesign may need to be combined with redevelopment."] },
  { question: "Do you design ecommerce websites?", answer: ["Yes. Ecommerce design may include product categories, product pages, search and filtering, cart journeys, checkout interfaces, customer accounts and mobile shopping layouts."] },
  { question: "Will the website be SEO-friendly?", answer: ["Website design can support SEO through logical content structures, crawlable navigation, internal linking, mobile usability and metadata-ready templates.", "Design alone cannot guarantee rankings."] },
  { question: "Can you also develop the website?", answer: ["Yes. Website design can be combined with Vorevix web development services.", "The combined scope may include design, responsive development, CMS configuration, ecommerce functionality, integrations, testing and launch support."] },
];
