export const webDesignAustraliaFaqs = [
  { question: "How much does web design cost in Australia?", answer: ["Cost depends on the number of pages, design complexity, content requirements, eCommerce features, integrations, development scope and support needs. After understanding the project, Vorevix can provide a tailored proposal instead of using an unsupported fixed price."] },
  { question: "How long does a website design project take?", answer: ["Timelines vary according to scope, stakeholder availability, content readiness and revision requirements. The agreed schedule should define review stages and client responsibilities."] },
  { question: "Do you work with businesses across Australia?", answer: ["Yes. Vorevix works remotely with businesses across Australia through planned meetings, written updates, milestone reviews and documented feedback."] },
  { question: "Can you design and develop the website?", answer: ["Yes. Design can be connected with development where it matches the agreed scope. Design-only projects can also be prepared for an approved development team."] },
  { question: "Will the website be mobile-friendly?", answer: ["Responsive behaviour is planned as part of the process. Layouts, navigation, content order, forms and calls to action are considered across relevant screen sizes."] },
  { question: "Can you redesign an existing website?", answer: ["Yes. We can assess the current website, identify what should be retained and create a clearer structure and visual system. Technical migration and redirects should also be considered when development is included."] },
  { question: "Will the website be SEO-ready?", answer: ["The design can support SEO through logical structure, crawlable navigation, content hierarchy and internal-link opportunities. Rankings cannot be guaranteed because they depend on technical, content, competition and authority factors."] },
  { question: "Can we provide feedback during the project?", answer: ["Yes. Feedback is built into agreed review stages. Consolidated feedback usually produces clearer decisions and more efficient revisions."] },
];
