export const webDevelopmentFaqs = [
  { question: "What is included in web development services?", answer: "A development engagement can include technical planning, frontend and backend development, CMS configuration, databases, eCommerce functionality, APIs, testing, deployment and post-launch support. The exact deliverables depend on the approved scope." },
  { question: "What is the difference between web design and web development?", answer: "Web design focuses on structure, user experience and visual layouts. Web development turns those designs into a working website or application using frontend code, backend systems, databases, CMS tools and integrations." },
  { question: "How much does custom web development cost?", answer: "Cost depends on pages, functionality, user roles, integrations, design complexity, content requirements and testing. We provide an estimate after reviewing the requirements because a business website and a custom application have very different technical needs." },
  { question: "How long does a web development project take?", answer: "Timelines vary according to scope, feedback speed, content readiness and technical complexity. A standard website may require several weeks, while a custom application can take longer. The expected schedule is defined during planning." },
  { question: "Can you develop both the frontend and backend?", answer: "Yes. We can handle frontend interfaces, backend logic, databases, CMS functionality and integrations as part of a full-stack project. Responsibilities are confirmed before work begins." },
  { question: "Can you integrate third-party APIs?", answer: "Yes, where the platform provides suitable access and documentation. We can integrate payment gateways, CRM systems, booking tools, analytics platforms, email services and other supported APIs." },
  { question: "Will my website be mobile responsive?", answer: "Responsive development is included in modern website projects unless the scope states otherwise. Layouts and functionality are reviewed across relevant desktop, tablet and mobile screen sizes." },
  { question: "Can web development support answer engines and AI search?", answer: "Clear semantic structure, accessible content, consistent entities and valid structured data can help search engines and AI-powered systems interpret a website. Inclusion or citation in generated results cannot be guaranteed." },
  { question: "Do you provide support after launch?", answer: "Yes. An initial support period or ongoing maintenance arrangement can be included according to the project agreement. Long-term support may cover updates, backups, bug fixes, monitoring and future improvements." },
];
